### ISSUE TITLE
[BUG/Help] 疑似测试数据泄露，CEval榜单结果不够靠谱

### ISSUE THREAD

**Issue by songt96** [THUDM/ChatGLM2-6B#10]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

疑似测试数据泄露，llm榜单结果不够靠谱
![image](https://github.com/THUDM/ChatGLM2-6B/assets/22572525/18fbc0b2-f1e9-4e34-9367-5b1f11ebde9d)
![image](https://github.com/THUDM/ChatGLM2-6B/assets/22572525/9cc01a0b-8f02-49ce-9e47-c02ea714dae7)

### Steps To Reproduce

疑似测试数据泄露，llm榜单结果不够靠谱

### Environment

```markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by duzx16** [comment]
因为模型是在大量的网页数据上训练的，其中必然包含教辅类的网站，所以给定题干之后可以补全对应的解析。具体到这两道题，第一题在 CEval 中的完整版是
```
下列关于资本结构理论的说法中，不正确的是____。\nA. 代理理论、权衡理论、有企业所得税条件下的MM理论，都认为企业价值与资本结构有关\nB. 按照优序融资理论的观点，考虑信息不对称和逆向选择的
影响，管理者偏好首选留存收益筹资，然后是发行新股筹资，最后是债务筹资\nC. 权衡理论是对有企业所得税条件下的MM理论的扩
展\nD. 代理理论是对权衡理论的扩展\n答案:A
```
第二题是
```
对于传输层来说错误的是____\nA. TCP是全双工协议\nB. TCP是字节流协议\nC. TCP和UDP协议不能使用同一个端口\nD. TSAD是IP和端口的组合\n答案:C
```
可以看出模型生成的内容和答案跟 CEval 里面的基本不相关，所以不足以证明有泄漏。
