### ISSUE TITLE
[BUG/Help] Is this model a fine-tuned model or a pre-trained one?

### ISSUE THREAD

**Issue by aereobert** [THUDM/ChatGLM2-6B#105]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi, thanks for the contribution, this work is amazing for the MMLU benchmark given the model size!

I am wondering if there is a way to fine-tune it with my own data, so **I would like to know whether this model a fine-tuned model or a pre-trained one.**

Thank you!

### Steps To Reproduce

None

### Environment

```markdown
None
```

**Comment by duzx16** [comment]
It was first pre-trained when fine-tuned.
