### ISSUE TITLE
[BUG/Help] 运行语句AutoTokenizer.from_pretrained出错

### ISSUE THREAD

**Issue by SitaraJin** [THUDM/ChatGLM2-6B#109]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

输入代码调用示例，运行第二句出错，tokenizer = AutoTokenizer.from_pretrained("THUDM/chatglm2-6b", trust_remote_code=True)

### Steps To Reproduce

输入代码调用示例，运行第二句出错，tokenizer = AutoTokenizer.from_pretrained("THUDM/chatglm2-6b", trust_remote_code=True)
错误信息如下：
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\xtxxadmin\Envs\myenv\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 719, in from_pretrained
    raise ValueError(
ValueError: Unrecognized configuration class <class 'transformers_modules.THUDM.chatglm2-6b.e186c891cf64310ac66ef10a87e6635fa6c2a579.configuration_chatglm.ChatGLMConfig'> to build an AutoTokenizer.
Model type should be one of AlbertConfig, AlignConfig, BartConfig, BertConfig, BertGenerationConfig, BigBirdConfig, BigBirdPegasusConfig, BioGptConfig, BlenderbotConfig, BlenderbotSmallConfig, BlipConfig, Blip2Config, BloomConfig, BridgeTowerConfig, CamembertConfig, CanineConfig, ChineseCLIPConfig, ClapConfig, CLIPConfig, CLIPSegConfig, CodeGenConfig, ConvBertConfig, CpmAntConfig, CTRLConfig, Data2VecTextConfig, DebertaConfig, DebertaV2Config, DistilBertConfig, DPRConfig, ElectraConfig, ErnieConfig, ErnieMConfig, EsmConfig, FlaubertConfig, FNetConfig, FSMTConfig, FunnelConfig, GitConfig, GPT2Config, GPT2Config, GPTBigCodeConfig, GPTNeoConfig, GPTNeoXConfig, GPTNeoXJapaneseConfig, GPTJConfig, GPTSanJapaneseConfig, GroupViTConfig, HubertConfig, IBertConfig, JukeboxConfig, LayoutLMConfig, LayoutLMv2Config, LayoutLMv3Config, LEDConfig, LiltConfig, LlamaConfig, LongformerConfig, LongT5Config, LukeConfig, LxmertConfig, M2M100Config, MarianConfig, MBartConfig, MegaConfig, MegatronBertConfig, MgpstrConfig, MobileBertConfig, MPNetConfig, MT5Config, MvpConfig, NezhaConfig, NllbMoeConfig, NystromformerConfig, OneFormerConfig, OpenAIGPTConfig, OPTConfig, OwlViTConfig, PegasusConfig, PegasusXConfig, PerceiverConfig, Pix2StructConfig, PLBartConfig, ProphetNetConfig, QDQBertConfig, RagConfig, RealmConfig, ReformerConfig, RemBertConfig, RetriBertConfig, RobertaConfig, RobertaPreLayerNormConfig, RoCBertConfig, RoFormerConfig, RwkvConfig, Speech2TextConfig, Speech2Text2Config, SpeechT5Config, SplinterConfig, SqueezeBertConfig, SwitchTransformersConfig, T5Config, TapasConfig, TransfoXLConfig, ViltConfig, VisualBertConfig, Wav2Vec2Config, Wav2Vec2ConformerConfig, WhisperConfig, XCLIPConfig, XGLMConfig, XLMConfig, XLMProphetNetConfig, XLMRobertaConfig, XLMRobertaXLConfig, XLNetConfig, XmodConfig, YosoConfig.

### Environment

```markdown
- OS:window
- Python:3.8.0
```

**Comment by duzx16** [comment]
What is the version of `transformers` you used?

**Comment by boundles** [comment]
> transformers

4.27.1

**Comment by starphantom666** [comment]
> What is the version of `transformers` you used?

我也是突然出现这个问题了，4.30.2遇到这个问题，用dev版本也遇到这个问题。更新前的版本没有问题

**Comment by necrophagists** [comment]
我是遇到了这个问题:Tokenizer class ChatGLMTokenizer does not exist or is not currently imported.
python版本3.10.1 transformers 4.30.2 系统 windows10

**Comment by ClarkWain** [comment]
我也是遇到这个问题，transformers 4.30.2, Python 3.10.6, windows11

**Comment by starphantom666** [comment]
大家可以先用历史版本

**Comment by ClarkWain** [comment]
> 大家可以先用历史版本

请问哪个版本可以？

**Comment by starphantom666** [comment]
model_path =“/home/用户名/.cache/huggingface/hub/models--THUDM--chatglm2-6b/snapshots/e186c891cf64310ac66ef10a87e6635fa6c2a579”

上面这个e186c891cf64310ac66ef10a87e6635fa6c2a579 
只要不是/home/用户名/.cache/huggingface/hub/models--THUDM--chatglm2-6b/refs/main的值就行

从/home/用户名/.cache/huggingface/hub/models--THUDM--chatglm2-6b/snapshots/下面随便选一个

**Comment by starphantom666** [comment]
或者用revision参数去指定版本号，可以在加载时附上这个参数，可以填上面的值，理论上应该也可以填v1.0(这个没测过，但应该可以)

**Comment by baowenqing** [comment]
+1

**Comment by alibabadoufu** [comment]
遇见同样的问题

**Comment by ClarkWain** [comment]
已经跑起来了

**Comment by starphantom666** [comment]
我找到原因了，好像是hug在下载模型相关文件到本地的.cathe目录时，偶尔会下载不全，导致自动加载找不到相关文件报错，可以把原来下载的目录删掉重下即可

**Comment by necrophagists** [comment]
> 我是遇到了这个问题:Tokenizer class ChatGLMTokenizer does not exist or is not currently imported. python版本3.10.1 transformers 4.30.2 系统 windows10

我解决了 原来是自作聪明去掉了trust_remote_code=True 兄弟们补上就好了
