### ISSUE TITLE
[Help] <ChatGLM2-6B 和 ChatGLM2-6B (base) 有什么区别呢>

### ISSUE THREAD

**Issue by leonall** [THUDM/ChatGLM2-6B#11]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

看到实验对比，有一个疑问。

`ChatGLM2-6B`和 `ChatGLM2-6B (base)` 有什么区别呢？本次开放的是 `ChatGLM2-6B`吧 

### Steps To Reproduce

没有。

### Environment

```markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by duzx16** [comment]
`ChatGLM2-6B (base)` 指的是只经过预训练，没有和人类意图对齐的模型，也就是常说的“基座模型”。
