### ISSUE TITLE
eos和pad token id 一样

### ISSUE THREAD

**Issue by luyuntao92** [THUDM/ChatGLM2-6B#113]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://github.com/THUDM/ChatGLM2-6B/assets/31723852/48e4e15c-9661-4e0d-bf8f-a6fdaaa51f89)
两个token id 一样，是不是改错了？

https://huggingface.co/THUDM/chatglm2-6b/commit/22f6409e8bd748d9f5e81bba5d29d1e7544d4f0f

### Steps To Reproduce

有人反映微调出现重复词，停不下来，是不是和这个有关系？

### Environment

```markdown
- OS:Ubuntu 20.04
- Python:3.9
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :11.7
```

**Comment by Yuang-Deng** [comment]
我觉得也是唉
![image](https://github.com/THUDM/ChatGLM2-6B/assets/51474616/e026f76b-f0bc-4ceb-893e-f96f57c11de2)
这块pad和eos都等于eos了
输出“self.sp_model.pad_id() = -1"

**Comment by luyuntao92** [comment]
> 

更新了，这个改掉了。
![image](https://github.com/THUDM/ChatGLM2-6B/assets/31723852/799d6389-05ba-426c-bbf5-395937df2b80)
![image](https://github.com/THUDM/ChatGLM2-6B/assets/31723852/2d33dca5-022d-47d3-be91-a5e34fdf4b6c)
但是，好奇怪，pad给的是unk，感觉预训练阶段没有pad这个token？

**Comment by Yuang-Deng** [comment]
> > 
> 
> 更新了，这个改掉了。 ![image](https://user-images.githubusercontent.com/31723852/249967047-799d6389-05ba-426c-bbf5-395937df2b80.png) ![image](https://user-images.githubusercontent.com/31723852/249967205-2d33dca5-022d-47d3-be91-a5e34fdf4b6c.png) 但是，好奇怪，pad给的是unk，感觉预训练阶段没有pad这个token？

我自己在special token里面加上了pad，微调之后不会出现停不下来的情况，但是训练时loss一个epoch之后会上升
![image](https://github.com/THUDM/ChatGLM2-6B/assets/51474616/3d2c1ce1-9941-40b8-bb32-47ea1e21b84d)
代码里面attention mask和position id的产生逻辑和glm1不一样了，我改了一下可能还是有点问题

**Comment by ArtificialZeng** [comment]
这个问题我也有，没有人解决吗

**Comment by ArtificialZeng** [comment]
我也不断出现重复词。直到把输出占满。无法终止。

**Comment by ArtificialZeng** [comment]
> > > 
> > 
> > 
> > 更新了，这个改掉了。 ![image](https://user-images.githubusercontent.com/31723852/249967047-799d6389-05ba-426c-bbf5-395937df2b80.png) ![image](https://user-images.githubusercontent.com/31723852/249967205-2d33dca5-022d-47d3-be91-a5e34fdf4b6c.png) 但是，好奇怪，pad给的是unk，感觉预训练阶段没有pad这个token？
> 
> 我自己在special token里面加上了pad，微调之后不会出现停不下来的情况，但是训练时loss一个epoch之后会上升 ![image](https://user-images.githubusercontent.com/51474616/249974698-3d2c1ce1-9941-40b8-bb32-47ea1e21b84d.png) 代码里面attention mask和position id的产生逻辑和glm1不一样了，我改了一下可能还是有点问题

这个具体怎么操作啊。怎么在special token里面加上pad

**Comment by Yuang-Deng** [comment]
> 

我是在下载的模型文件里有个tokenization_chatglm.py 里面改的 sptokenizer有个special token，加上pad，然后把pad_id重新设置一下
