### ISSUE TITLE
[显存占用问题] <QLoRA微调显存占用远高于chatglm-6b？>

### ISSUE THREAD

**Issue by shuxueslpi** [THUDM/ChatGLM2-6B#116]
### Is your feature request related to a problem? Please describe.

我写了一份用QLoRA微调chatglm-6b/chatglm2-6B的代码，在这：https://github.com/shuxueslpi/chatGLM-6B-QLoRA
主要依赖peft库，代码仓库里做了一些1代和2代的比对，发现2代模型在训练时的显存占用明显高于1代，这是为什么？

### Solutions

需要做什么配置吗？

**Comment by JungYeepen** [comment]
同求 感觉 2.0 显存要求突然高了不少……

**Comment by duzx16** [comment]
之前模型没有实现 activation checkpointing，今天实现了，你可以再尝试一下

**Comment by Mou-Mou-L** [comment]
> 之前模型没有实现 activation checkpointing，今天实现了，你可以再尝试一下

坐等大佬更新支持ptuning微调

**Comment by shuxueslpi** [comment]
@duzx16 试了下，确实可以了，感谢大佬，棒极了！

**Comment by JungYeepen** [comment]
> @duzx16 试了下，确实可以了，感谢大佬，棒极了！

请问大大的训练 repo 现在也能正常微调训练了吗？ 最近有个业务点希望能微调结合一下呜呜呜

**Comment by shuxueslpi** [comment]
现在其实就能正常训练，就是显存占用大，我尽快把这个最新的更新上去

**Comment by JungYeepen** [comment]
> 

thx a lot 感谢各位大大

**Comment by JungYeepen** [comment]
> 
thx a lot 感谢各位大大

**Comment by Mou-Mou-L** [comment]
> 之前模型没有实现 activation checkpointing，今天实现了，你可以再尝试一下

ptuning微调报错
Loading checkpoint shards: 100%|▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒| 7/7 [00:09<00:00,  1.42s/it]
[INFO|modeling_utils.py:3032] 2023-06-30 10:26:43,545 >> All model checkpoint weights were used when initializing ChatGLMForConditionalGeneration.

[WARNING|modeling_utils.py:3034] 2023-06-30 10:26:43,545 >> Some weights of ChatGLMForConditionalGeneration were not initialized from the model checkpoint at THUDM/chatglm2-6b and are newly initialized: ['transformer.prefix_encoder.embedding.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
[INFO|modeling_utils.py:2690] 2023-06-30 10:26:43,926 >> Generation config file not found, using a generation config created from the model config.
Quantized to 4 bit
Traceback (most recent call last):
  File "main.py", line 430, in <module>
    main()
  File "main.py", line 248, in main
    train_dataset = train_dataset.map(
  File "E:\ProgramData\anaconda3\envs\glm2\lib\site-packages\datasets\arrow_dataset.py", line 578, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "E:\ProgramData\anaconda3\envs\glm2\lib\site-packages\datasets\arrow_dataset.py", line 543, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "E:\ProgramData\anaconda3\envs\glm2\lib\site-packages\datasets\arrow_dataset.py", line 3073, in map
    for rank, done, content in Dataset._map_single(**dataset_kwargs):
  File "E:\ProgramData\anaconda3\envs\glm2\lib\site-packages\datasets\arrow_dataset.py", line 3449, in _map_single
    batch = apply_function_on_filtered_inputs(
  File "E:\ProgramData\anaconda3\envs\glm2\lib\site-packages\datasets\arrow_dataset.py", line 3330, in apply_function_on_filtered_inputs
    processed_inputs = function(*fn_args, *additional_args, **fn_kwargs)
  File "main.py", line 219, in preprocess_function_train
    context_length = input_ids.index(tokenizer.bos_token_id)
ValueError: None is not in list

**Comment by Mou-Mou-L** [comment]
> 现在其实就能正常训练，就是显存占用大，我尽快把这个最新的更新上去

大佬可以 ptuning微调了么

**Comment by Mou-Mou-L** [comment]
大佬，按照您的代码  这一块不用推荐环境docker的话
推荐使用docker镜像，如下：

docker pull huggingface/transformers-pytorch-gpu:4.29.1
docker run -tid -v /your/data/path:/home -p 58323:58323 --gpus all huggingface/transformers-pytorch-gpu:4.29.1
 需要怎么处理  
我直接手动安装了下边的几个依赖  然后建了个.sh文件 把python train_qlora.py \
--train_args_json chatGLM_6B_QLoRA.json \
--model_name_or_path THUDM/chatglm2-6b \
--train_data_path data/train.jsonl \
--eval_data_path data/dev.jsonl \
--lora_rank 4 \
--lora_dropout 0.05 \
--compute_dtype fp32
然后 git bush运行 报错
CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

**Comment by shuxueslpi** [comment]
@Mou-Mou-L 
是不是要运行这个，我好像写漏了？
pip install -q -U bitsandbytes

**Comment by shuxueslpi** [comment]
> > 现在其实就能正常训练，就是显存占用大，我尽快把这个最新的更新上去
> 
> 大佬可以 ptuning微调了么

额，我那个代码只有qlora的训练

**Comment by Mou-Mou-L** [comment]
> > > 现在其实就能正常训练，就是显存占用大，我尽快把这个最新的更新上去
> > 
> > 
> > 大佬可以 ptuning微调了么
> 
> 额，我那个代码只有qlora的训练

我就是用的qlora  我没有docker环境  从那往下的运行 一直报我gpu的错误 https://github.com/THUDM/ChatGLM2-6B/issues/116#issuecomment-1614305639

**Comment by Alwin4Zhang** [comment]
> > > > 现在其实就能正常训练，就是显存占用大，我尽快把这个最新的更新上去
> > > 
> > > 
> > > 大佬可以 ptuning微调了么
> > 
> > 
> > 额，我那个代码只有qlora的训练
> 
> 我就是用的qlora 我没有docker环境 从那往下的运行 一直报我gpu的错误 [#116 (comment)](https://github.com/THUDM/ChatGLM2-6B/issues/116#issuecomment-1614305639)

peft更新一下
