### ISSUE TITLE
内存还是不足，有人可以分享 量化后的模型吗？

### ISSUE THREAD

**Issue by Wulx2050** [THUDM/ChatGLM2-6B#12]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

这是之前 chatglm-6b-int4 的代码：
```python
# 默认情况下，模型以 FP16 精度加载，运行上述代码需要大概 13GB 显存。
# model = AutoModel.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True).half().cuda()

# 按需修改，目前只支持 4/8 bit 量化
# model = AutoModel.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True).quantize(4).half().cuda()

# 如果你的内存不足的话，可以直接加载量化后的模型，仅需大概 5.2GB 的内存：
model = AutoModel.from_pretrained("THUDM/chatglm-6b-int4", trust_remote_code=True).half().cuda()
```

### Steps To Reproduce

【占位符】

### Environment

```markdown
- OS: Linux 5.15.107+
- Python: 3.10.12
- Transformers: 4.27.1
- PyTorch: 2.0.1+cu118
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) : True
```

### Anything else?

【占位符】

**Comment by duzx16** [comment]
https://huggingface.co/THUDM/chatglm2-6b-int4

**Comment by shirubei** [comment]
没用啊，改为 -int4 的那个模型也照样报错，就跟楼主开贴描述的一样。

**Comment by Wulx2050** [comment]
> 没用啊，改为 -int4 的那个模型也照样报错，就跟楼主开贴描述的一样。

可以啊，你试一试？
```python
from transformers import AutoTokenizer, AutoModel
tokenizer = AutoTokenizer.from_pretrained("THUDM/chatglm2-6b", trust_remote_code=True)
# 直接加载量化后的模型
model = AutoModel.from_pretrained("THUDM/chatglm2-6b-int4", trust_remote_code=True).half().cuda()

model = model.eval()
```

Python 3 Google Compute Engine 后端 (GPU)
显示09:12到09:20之间的资源
系统 RAM
4.4 / 12.7 GB
 
GPU RAM
5.3 / 15.0 GB

**Comment by Wulx2050** [comment]
https://colab.research.google.com/drive/1vzNKismQN0oRyVisZOFfzOlWqn_54IRC?usp=sharing

**Comment by shirubei** [comment]
> https://colab.research.google.com/drive/1vzNKismQN0oRyVisZOFfzOlWqn_54IRC?usp=sharing

多谢啊，难道是我在windows上的所以不行？ 我的是win11, 64GB RAM,  11GB GPU RAM

**Comment by OrdinaryChen** [comment]
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (2.2.1) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Load parallel cpu kernel failed /root/.cache/huggingface/modules/transformers_modules/THUDM/chatglm2-6b-int4/66ecaf1db3a5085714e133357ea4824b69698743/quantization_kernels_parallel.so: Traceback (most recent call last):
  File "/root/.cache/huggingface/modules/transformers_modules/THUDM/chatglm2-6b-int4/66ecaf1db3a5085714e133357ea4824b69698743/quantization.py", line 148, in __init__
    kernels = ctypes.cdll.LoadLibrary(kernel_file)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 451, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /lib/aarch64-linux-gnu/libgomp.so.1: cannot allocate memory in static TLS block

Killed
