### ISSUE TITLE
提高编程语言认知

### ISSUE THREAD

**Issue by mfjiang** [THUDM/ChatGLM2-6B#122]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```python
response,history = model.chat(tokenizer,"请用markdown格式化回答：C#语言与Java语言的详细区别",history=[]
```
此问题回答得十分荒谬，对C#语言的认知停留在10年前，随着.NET平台的开源和跨CPU架构、跨操作系统的发展，C#已经可以运行在龙芯架构、ARM架构、三星Tizen架构、x86和x64硬件架构之上，同时也可以运行在树莓派设备上。无论是Windows还是Linux都是可以运行.NET 和 C# 程序。

而且.NET技术平台已经全面介入AI的应用开发领域，比如tensorflow.net、ONNX、ML.net、SemanticKernel。

然后，java也不是一个弱类型语言，应该是一个强类型语言。

关于C#语言比较小众的观点也要纠正，C#在企业级应用和互联网应用上都是有很高水准的应用，比如特斯拉的ERP系统中就有C#程序，Bing.com这个全球第2的搜索引擎也是C#实现的。

希望研究团队尽快能更新这个领域的知识，避免误导公众的认知。

### Expected Behavior

答案要符合最新的知识

### Steps To Reproduce

response,history = model.chat(tokenizer,"请用markdown格式化回答：C#语言与Java语言的详细区别",history=[]

### Environment

```markdown
- OS: google colab
- Python: 3.10
- Transformers: 4.20.2
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :true
```

**Comment by duzx16** [comment]
感谢反馈

**Comment by geffzhang** [comment]
说的挺好，其中有点小错误：三星Tizen架构 其实不是架构，是属于arm架构 ，Tizen是 三星的一个操作系统
