### ISSUE TITLE
[Python、cuda版本] <请问推荐的Python、cuda版本是多少？>

### ISSUE THREAD

**Issue by GoogleLLP** [THUDM/ChatGLM2-6B#127]
请问官方推荐的Python版本是多少？或者说开发该项目的Python版本是多少？cuda版本是多少？

正在考虑制作一个docker镜像，需要明确推荐的版本号

**Comment by won-i** [comment]
nvidia-smi查看适配显卡的CUDA版本。根据CUDA版本去torch下载页面查有哪些可用的torch版本，后面就会出现适配的python版本号
下载地址：https://download.pytorch.org/whl/torch_stable.html
![9903fe5fa9064ffee8682539ab20d79](https://github.com/THUDM/ChatGLM2-6B/assets/83972970/7bfa57bd-4b12-4667-a056-79784f687f01)

**Comment by GoogleLLP** [comment]
> nvidia-smi查看适配显卡的CUDA版本。根据CUDA版本去torch下载页面查有哪些可用的torch版本，后面就会出现适配的python版本号 下载地址：https://download.pytorch.org/whl/torch_stable.html ![9903fe5fa9064ffee8682539ab20d79](https://user-images.githubusercontent.com/83972970/249993020-7bfa57bd-4b12-4667-a056-79784f687f01.png)

不是，我是问这个项目的Python版本和cuda版本

**Comment by duzx16** [comment]
测试的时候用的是 Python 3.10，CUDA 12.0

**Comment by cristianohello** [comment]
@duzx16 
@GoogleLLP 
你好，能提供制作docker镜像的代码命令吗？感谢，小白

**Comment by nlpchen** [comment]
> @duzx16 @GoogleLLP 你好，能提供制作docker镜像的代码命令吗？感谢，小白

可以打包成支持gpu的镜像分享一下吗？多谢。nlp_chen@163.com
