### ISSUE TITLE
[Help] 推理速度中的“字符/秒“是什么含义

### ISSUE THREAD

**Issue by zhuochen13** [THUDM/ChatGLM2-6B#128]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://github.com/THUDM/ChatGLM2-6B/assets/55526352/42d68ef0-5d0e-4a2b-9561-3bc373f828ce)
这里的字符是什么含义，是token吗，还是character。chatGLM2-6b的tokens-per-second是多少

### Steps To Reproduce

null

### Environment

```markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by duzx16** [comment]
指的是 token
