### ISSUE TITLE
[Feature] 11GB 显存还是报CUDA out of memory

### ISSUE THREAD

**Issue by shirubei** [THUDM/ChatGLM2-6B#13]
### Is your feature request related to a problem? Please describe.

torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 108.00 MiB (GPU 0; 11.00 GiB total capacity; 10.29 GiB already allocated; 0 bytes free; 10.29 GiB reserved in total by PyTorch)

### Solutions

要能跑起来该怎么设置或者修改代码呢？谢谢！

**Comment by shirubei** [comment]
Dupli of #12

**Comment by shirubei** [comment]
改为 -int4 的那个模型也照样报错

**Comment by SZ-ing** [comment]
我跑的web_demo.py，改成“.quantize(4).cuda()”之后，32G内存，6G显存的机器，跑起来没有问题。

**Comment by shirubei** [comment]
> 我跑的web_demo.py，改成“.quantize(4).cuda()”之后，32G内存，6G显存的机器，跑起来没有问题。

多谢！

model = AutoModel.from_pretrained("THUDM/chatglm2-6b-int4", trust_remote_code=True, device='cuda').quantize(4).cuda()
windows11, 64GBRAM, 11GB GPU, 这样还是报错
torch: 2.0.0+cu118

**Comment by SZ-ing** [comment]
你加载的模型是hugging face上面的那个吗？我是从hugging face上面下载之后，本地加载的

**Comment by SZ-ing** [comment]
![image](https://github.com/THUDM/ChatGLM2-6B/assets/96756560/6dfc7d6c-9b82-4bc1-a2d8-d584b2b0de0e)

**Comment by SZ-ing** [comment]
![image](https://github.com/THUDM/ChatGLM2-6B/assets/96756560/0601f86a-40ea-41c0-9cf3-f7d659c5b61d)
'2.0.1+cu117'

**Comment by shirubei** [comment]
> ![image](https://user-images.githubusercontent.com/96756560/248633207-6dfc7d6c-9b82-4bc1-a2d8-d584b2b0de0e.png)

多谢！ 我是跑程序后它自动下载的。我手动下载试看看

**Comment by Sunnylee0101** [comment]
32G内存，6G显存的机器，能跑起来的那哥们吗，你跑的怕不是chatglm之前的版本吧，chatglm2根本运行不了

**Comment by Sunnylee0101** [comment]
32G内存，6G显存的机器，跑起来没有的这个哥们，你好好看看你跑的是之前的版本还是现在的版本，版本2这个配置int4都跑不起来

**Comment by SZ-ing** [comment]
> 32G内存，6G显存的机器，跑起来没有的这个哥们，你好好看看你跑的是之前的版本还是现在的版本，版本2这个配置int4都跑不起来

是2，权重是从[hugging face](https://huggingface.co/THUDM/chatglm2-6b/tree/main)这个网址上面下载下来的，一共7个权重，chatGLM-6B的是8个权重。我问了ChagGLM2-6B，他回答的也是2.
![image](https://github.com/THUDM/ChatGLM2-6B/assets/96756560/8206437d-829a-4e8e-ae60-7142eb824656)

**Comment by SZ-ing** [comment]
> > 32G内存，6G显存的机器，跑起来有没有这哥们，你好好看看你跑的是之前的版本还是现在的版本，版本2这个配置int4都跑不起来
> 
> 是2，权重是从[抱脸](https://huggingface.co/THUDM/chatglm2-6b/tree/main)这个网址上面下载下来的，一共7个权重，聊天GLM-6B8个权重。我问了ChagGLM2-6B，他回答的也是2。 ![图像](https://user-images.githubusercontent.com/96756560/248637030-8206437d-829a-4e8e-ae60-7142eb824656.png)

我没有用[hugging face](https://huggingface.co/THUDM/chatglm2-6b-int4)上面的int4版本，会不会是这个问题

**Comment by shirubei** [comment]
我2个都试过了，非int4和int4 都报显卡内存不足

**Comment by SZ-ing** [comment]
> 我2个都试过了，非int4和int4 都报显卡内存不足

那好奇怪，我这个用的还是笔记本
![image](https://github.com/THUDM/ChatGLM2-6B/assets/96756560/1a998ab2-ee01-4e9a-af9a-269acc60caab)
![image](https://github.com/THUDM/ChatGLM2-6B/assets/96756560/34b667a4-6c59-45ab-94c0-f3b9e0c1b620)

**Comment by SZ-ing** [comment]
> > 我2个都试过了，非int4和int4 都报显卡内存不足
> 
> 那好奇怪，我这个用的还是笔记本 ![image](https://user-images.githubusercontent.com/96756560/248637583-1a998ab2-ee01-4e9a-af9a-269acc60caab.png) ![image](https://user-images.githubusercontent.com/96756560/248637607-34b667a4-6c59-45ab-94c0-f3b9e0c1b620.png)

int4跑起来内存和GPU都没占满

**Comment by Sunnylee0101** [comment]
我RTX3070的显卡 8G显存，两个模型权重都用了  也是显存溢出，你的6G显存用的是什么显卡

**Comment by SZ-ing** [comment]
> 我RTX3070的显卡 8G显存，两个模型权重都用了 也是显存溢出，你的6G显存用的是什么显卡

RTX2060

**Comment by Sunnylee0101** [comment]
奇了怪了  我量化和非量化的模型也都是从hugging face手动下载的，两个都用了，全是显存溢出  无语了

**Comment by SZ-ing** [comment]
> 奇了怪了 我量化和非量化的模型也都是从hugging face手动下载的，两个都用了，全是显存溢出 无语了

难道是我哪个地方代码不小心被我给更改，导致用了1的版本的代码？
链接：https://pan.baidu.com/s/1RKmZq-gE_Jv0jIZKuZ7jPA?pwd=tg8j 
提取码：tg8j 
--来自百度网盘超级会员V5的分享
这个是我现在用的代码， 要不你们试试？

**Comment by Sunnylee0101** [comment]
好的 我试试，不过我下载的时候发现你这个是10M多，原始的2.0版本只有5M左右  我先看看

**Comment by Sunnylee0101** [comment]
还行不行，你torch用的是什么版本的

**Comment by Sunnylee0101** [comment]
不是 我猜测，大概率是torch版本的问题，你用的torch版本和官方的是一样的，楼主用的是2.0.0所以不行，我用的是2.0以下的torch也不行  感觉破案了

**Comment by SZ-ing** [comment]
> 不是 我猜测，大概率是torch版本的问题，你用的torch版本和官方的是一样的，楼主用的是2.0.0所以不行，我用的是2.0以下的torch也不行 感觉破案了

所以，2.0.1优化了显存占用？好奇怪呀，小版本改动应该不会这么大才对呀。

**Comment by shirubei** [comment]
我的显卡驱动是cuda11.8，刚刚把torch也升到2.0.1了，也就是现在是 torch2.0.1+cu118 ，但int4还是不行

**Comment by SZ-ing** [comment]
> 我的显卡驱动是cuda11.8，刚刚把torch也升到2.0.1了，也就是现在是 torch2.0.1+cu118 ，但int4还是不行

那你们拿我刚才发的那个百度网盘的代码试试？

**Comment by shirubei** [comment]
好的，估计要晚上才有时间了，有结果我会尽快反馈，多谢！

**Comment by Sunnylee0101** [comment]
> 我的显卡驱动是cuda11.8，刚刚把torch也升到2.0.1了，也就是现在是 torch2.0.1+cu118 ，但int4还是不行

你这个环境还是跑不通吗？transformers的版本呢  是4,27.1的好像

**Comment by Sunnylee0101** [comment]
> > 不是 我猜测，大概率是torch版本的问题，你用的torch版本和官方的是一样的，楼主用的是2.0.0所以不行，我用的是2.0以下的torch也不行 感觉破案了
> 
> 所以，2.0.1优化了显存占用？好奇怪呀，小版本改动应该不会这么大才对呀。

RTX2070可以安装cuda11.7吗，30系以下的显卡不是没法安装11.0以上的cuda吗

**Comment by SZ-ing** [comment]
> > > 不是 我猜测，大概率是torch版本的问题，你用的torch版本和官方的是一样的，楼主用的是2.0.0所以不行，我用的是2.0以下的torch也不行 感觉破案了
> > 
> > 
> > 所以，2.0.1优化了显存占用？好奇怪呀，小版本改动应该不会这么大才对呀。
> 
> RTX2060可以安装cuda11.7吗，30系以下的显卡不是没法安装11.0以上的cuda吗

可以装的
![image](https://github.com/THUDM/ChatGLM2-6B/assets/96756560/ed112e00-9876-4bf6-9515-2465cc633545)

**Comment by Sunnylee0101** [comment]
好的 谢谢  我再琢磨一下到底是为啥

**Comment by shirubei** [comment]
> > 我的显卡驱动是cuda11.8，刚刚把torch也升到2.0.1了，也就是现在是 torch2.0.1+cu118 ，但int4还是不行
> 
> 那你们拿我刚才发的那个百度网盘的代码试试？
发现问题所在了，安装百度网盘的那样，把device=“cuda”这个参数删除就可以了。
model = AutoModel.from_pretrained("THUDM/chatglm2-6b-int4", trust_remote_code=True).quantize(4).cuda()

**Comment by duzx16** [comment]
> 发现问题所在了，像百度网盘的代码那样，把device=“cuda”这个参数删除就可以了。 model = AutoModel.from_pretrained("THUDM/chatglm2-6b-int4", trust_remote_code=True).quantize(4).cuda()

这个是 README 里说明的加载量化模型的方式。如果在 `from_pretrained` 里传入 `device='cuda'`，会把量化前的模型构建在 GPU上。

**Comment by shirubei** [comment]
首页上的那个readme的代码没改啊

**Comment by Sunnylee0101** [comment]
> 发现问题所在了，像百度网盘的代码那样，把device=“cuda”这个参数删除就可以了。 model = AutoModel.from_pretrained("THUDM/chatglm2-6b-int4", trust_remote_code=True).quantize(4).cuda()
我报了RuntimeError: "arange_cpu" not implemented for 'Half'这样的错，早晨就试过了，我的问题应该就是torch不匹配导致的

**Comment by ferdyzhang** [comment]
> 
改完这个报这个错？？
RuntimeError: Library cudart is not initialized

**Comment by StarDxxx** [comment]
在windows笔记本上可以运行吗？RTX4050， 4060。谢谢

**Comment by shirubei** [comment]
> > 
> 
> 改完这个报这个错？？ RuntimeError: Library cudart is not initialized

它找不到cuda驱动安装目录下的dll文件，具体哪个文件忘了，把dll文件的路径加到path里就OK

**Comment by shirubei** [comment]
> 在windows笔记本上可以运行吗？RTX4050， 4060。谢谢

只要驱动安装正确，显卡内存够的话应该是没有问题才对

**Comment by zysNLP** [comment]
> > > 
> > 
> > 
> > 改完这个报这个错？？ RuntimeError: Library cudart is not initialized
> 
> 它找不到cuda驱动安装目录下的dll文件，具体哪个文件忘了，把dll文件的路径加到path里就OK

@shirubei 请问是哪个文件。。。我也报这个错

**Comment by shirubei** [comment]
安装cuda驱动的目录下的cuda 对应版本号下的bin目录
我的是 C:\Program Files\Nvidia\CUDA\v11.8\bin
