### ISSUE TITLE
m1max芯片，卡住不动

### ISSUE THREAD

**Issue by stoneLee81** [THUDM/ChatGLM2-6B#130]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

from transformers import AutoTokenizer, AutoModel
tokenizer = AutoTokenizer.from_pretrained("THUDM/chatglm2-6b", trust_remote_code=True)
model = AutoModel.from_pretrained("THUDM/chatglm2-6b", trust_remote_code=True).half().to('mps')
model = model.eval()
response, history = model.chat(tokenizer, "你好", history=[])
print(response)

/Users/haowmazs/testdata/ChatGLM2-6B/venv/bin/python /Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevd.py --multiprocess --qt-support=auto --client 127.0.0.1 --port 53339 --file /Users/haowmazs/testdata/ChatGLM2-6B/demo.py 
Connected to pydev debugger (build 231.9161.41)
Loading checkpoint shards: 100%|██████████| 7/7 [00:06<00:00,  1.16it/s]

加载完模型没问题，但在执行，一直卡在model.chat不动了

### Steps To Reproduce

null

### Environment

```markdown
- OS: 13.4.1 m1max 64G
- Python: 3.9.7
- Transformers:4.30.2
- PyTorch: 2.1.0.dev20230629
- MPS Support (` python -c "import torch; print(torch.backends.mps.is_built())"`) :True
```

**Comment by linpan** [comment]
4/8 bit 量化，
