### ISSUE TITLE
[BUG/Help] 32k 上下文效果是崩的？训练并不是32k 的上下文训得？

### ISSUE THREAD

**Issue by daxia-daxia** [THUDM/ChatGLM2-6B#133]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

从这里看到的：https://lmsys.org/blog/2023-06-29-longchat/
![44b19765-9203-4f1a-8e6a-b9f4bc3c0874](https://github.com/THUDM/ChatGLM2-6B/assets/24487097/1968b057-8fc7-4d0e-bce4-7b0759009de5)

本地A100 单卡试了一下20k token 的推理，发现显存不足

### Steps To Reproduce

none

### Environment

```markdown
none
```

**Comment by piaomiaoju** [comment]
我们将基座模型的上下文长度（Context Length）由 ChatGLM-6B 的 2K 扩展到了 32K，并在对话阶段使用 8K 的上下文长度训练。是啥意思，是说推理只有8K的长度么？ 为啥训练的和推理的还不一样。

**Comment by duzx16** [comment]
对话模型微调的长度是 8k，所以超出 8k 长度的性能会受到影响

**Comment by daxia-daxia** [comment]
> 对话模型微调的长度是 8k，所以超出 8k 长度的性能会受到影响

从图中的性能来看， pretrain 阶段的长度也不是32k? 所以是否是说这个模型理论上支持了32k 的推理（不会炸显存），但训练各种还是在小于32 k下做的？
