### ISSUE TITLE
[BUG/Help] <title>微调后输出长度不够长

### ISSUE THREAD

**Issue by dragononly** [THUDM/ChatGLM2-6B#137]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

微调后输出长度不够长

### Steps To Reproduce

微调后输出长度不够长

### Environment

```markdown
- OS:ok
- Python:ok
- Transformers:ok
- PyTorch:ok
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :ok
```

### Anything else?

微调后输出长度不够长

**Comment by duzx16** [comment]
You can set `min_length` argument to `chat` or `stream_chat`
