### ISSUE TITLE
[Feature] <模型文件是否有提供国内较快的下载地址>

### ISSUE THREAD

**Issue by sgyh** [THUDM/ChatGLM2-6B#14]
### Solutions

辛苦提供国内下载速度较快的模型文件地址，类似chatglm-6b中的清华云地址，谢谢~

**Comment by Nico0416** [comment]
https://huggingface.co/THUDM/chatglm2-6b/tree/main

**Comment by sgyh** [comment]
> https://huggingface.co/THUDM/chatglm2-6b/tree/main

谢谢兄弟！
不过我的网络太差了，从huggingface下载，一个bin预估需要3h不说，每下载20M还会中断一次

**Comment by linzeyang** [comment]
I've found that there is the folder for ChatGLM2 in https://cloud.tsinghua.edu.cn/d/674208019e314311ab5c/ but it is currenty empty at the time I am writing this comment.
Perhaps the maintainers have not uploaded the model there yet :)

**Comment by xuzhiang** [comment]
git clone git@hf.co:THUDM/chatglm2-6b
用ssh下载，比Https要稳定很多，没有科学上网也可以下载，偶尔中断

**Comment by ysyx2008** [comment]
链接：https://pan.baidu.com/s/1rn1ZtjgfMZg_Kw4PNd3jVQ?pwd=aiha 
提取码：aiha 
--来自百度网盘超级会员V6的分享

好像百度会关这类分享，不确定能用多久，你先试试看吧。

**Comment by sgyh** [comment]
> I've found that there is the folder for ChatGLM2 in https://cloud.tsinghua.edu.cn/d/674208019e314311ab5c/ but it is currenty empty at the time I am writing this comment. Perhaps the maintainers have not uploaded the model there yet :)

A link worth bookmarking, thank you~

**Comment by sgyh** [comment]
> 链接：https://pan.baidu.com/s/1rn1ZtjgfMZg_Kw4PNd3jVQ?pwd=aiha 提取码：aiha --来自百度网盘超级会员V6的分享
> 
> 好像百度会关这类分享，不确定能用多久，你先试试看吧。

谢谢兄弟！
正在下载中，起码不中断了

**Comment by sgyh** [comment]
> git clone [git@hf.co](mailto:git@hf.co):THUDM/chatglm2-6b 用ssh下载，比Https要稳定很多，没有科学上网也可以下载，偶尔中断

几种方法试下来，科学上网之后，这个还是相对最快速稳定的

**Comment by linzeyang** [comment]
> > I've found that there is the folder for ChatGLM2 in https://cloud.tsinghua.edu.cn/d/674208019e314311ab5c/ but it is currenty empty at the time I am writing this comment. Perhaps the maintainers have not uploaded the model there yet :)
> 
> A link worth bookmarking, thank you~

这是清华大学云盘链接，今天他们已经把量化和非量化的模型上传了
