### ISSUE TITLE
[BUG/Help] <网页版修改端口号>

### ISSUE THREAD

**Issue by guoguolord** [THUDM/ChatGLM2-6B#153]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

我在Linux服务器上部署的，想用windows电脑在网页端访问，尝试修改主机号127.0.0.1，但是并未能修改的地方

### Expected Behavior

希望可以提供修改的地方

### Steps To Reproduce

Linux

### Environment

```markdown
- OS:Ubantu20.04
- Python:3.10
- Transformers:4.26
- PyTorch:2.0
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :True
```

**Comment by qiaohui** [comment]
web_demo.py
修改最后的 launch 方法的参数：
demo.queue().launch(share=False, inbrowser=True, **server_name="0.0.0.0"**)

**Comment by tjsky** [comment]
以web_demo为例：

```python
demo.queue().launch(share=False, inbrowser=True, server_name='0.0.0.0', server_port=8071)
```

分别设置server_name与server_port的值即可。

**Comment by wys2641970184** [comment]
> ```python
> demo.queue().launch(share=False, inbrowser=True, server_name='0.0.0.0', server_port=8071)
> ```

按照你说的这样设置，不管端口设置什么 都会提示端口被占用
