### ISSUE TITLE
32G显存纯推理提示显存不足

### ISSUE THREAD

**Issue by LivinLuo1993** [THUDM/ChatGLM2-6B#157]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://github.com/THUDM/ChatGLM2-6B/assets/44887637/bc9eaf41-6ac5-47d2-80c6-f556485a5f0c)
请问使用单击多卡进行推理时提示显存不足如何调整，早前使用chatglm-6b可以正常允许，chatglm2-6b却出现显存不足提示

### Steps To Reproduce

 None

### Environment

```markdown
- OS:CentOS7.6
- Python:3.10
- Transformers:4.27.1
- PyTorch:1.13
- CUDA Support:True
```

**Comment by emojilearning** [comment]
同问

**Comment by duzx16** [comment]
什么叫使用单机多卡进行推理？

**Comment by xs1997zju** [comment]
The issue is not settle, why close this issue??

**Comment by xs1997zju** [comment]
Weird
