### ISSUE TITLE
[BUG/Help] <title>Unsupport bit-width

### ISSUE THREAD

**Issue by Ashionnal** [THUDM/ChatGLM2-6B#160]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

参照官网的教程，自己单独下载了模型，放到了THUDM/chatgpt2-6b下面，然后直接运行 python web_demo.py，进入web页面中输入hello ，直接报错，在控制台中，爆出了Unsupport bi-width相关的错误。
PS:因为我的显卡是12G，所以我在开始的时候单独设置了10，如下，其他都没有动
model = AutoModel.from_pretrained("THUDM/chatglm2-6b", trust_remote_code=True).**quantize(10)**.cuda()

![微信截图_20230703144453](https://github.com/THUDM/ChatGLM2-6B/assets/23193694/8e5d88bc-ae6d-4925-b35a-61181fe9c430)
![微信截图_20230703144514](https://github.com/THUDM/ChatGLM2-6B/assets/23193694/01999705-be8f-411c-983d-c8d2773bb7b2)

### Steps To Reproduce

1. git clone THUDM/ChatGLM2-6B
2. download offline Model
3. modify model = AutoModel.from_pretrained("THUDM/chatglm2-6b", trust_remote_code=True).quantize(10).cuda()
4. python web_demo.py
5. send 'hello' on web
6. error

### Environment

```markdown
- OS:Ubuntu20
- Python:3.10.11
- Transformers:4.30.2
- PyTorch:2.0.1
- CUDA Support: true
```

**Comment by shuxueslpi** [comment]
@Ashionnal 这个量化要么8要么4吧，10不行的
