### ISSUE TITLE
chatglm2-6b-int4和chatglm2-6b的模型效果区别大吗？

### ISSUE THREAD

**Issue by cristianohello** [THUDM/ChatGLM2-6B#162]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

chatglm2-6b-int4和chatglm2-6b的模型效果区别大吗？

### Expected Behavior

chatglm2-6b-int4和chatglm2-6b的模型效果区别大吗？

### Steps To Reproduce

chatglm2-6b-int4和chatglm2-6b的模型效果区别大吗？

### Environment

```markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by duzx16** [comment]
https://github.com/THUDM/ChatGLM2-6B#%E6%8E%A8%E7%90%86%E6%80%A7%E8%83%BD 有是否使用 int4 推理的准确率对比
