### ISSUE TITLE
[BUG/Help] 用什么指令可以让模型写反义句

### ISSUE THREAD

**Issue by calvinzhan** [THUDM/ChatGLM2-6B#17]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

给的指令是 
"""请写出下面句子的5个反义句
民生银行应向客户事先送达有关机关的协助冻结、扣划存款通知书，方有权办理冻结、扣划手续。
 """

得到如下回复：

1. 事先送达有关机关的协助冻结、扣划存款通知书不是民生银行的义务。
2. 民生银行没有权利办理冻结、扣划手续，除非事先送达有关机关的协助冻结、扣划存款通知书。
3. 向客户送达有关机关的协助冻结、扣划存款通知书不是民生银行的职责。
4. 民生银行不能办理冻结、扣划手续，除非事先得到有关机关的协助。
5. 事先送达有关机关的协助冻结、扣划存款通知书是民生银行的限制条件。

感觉并没有把反义写出来。不知构造什么样的指令能让它工作得好点？

### Steps To Reproduce
    temperature = 0.95
    max_length=600

    original_llm = load_model_on_gpus(original_model_path, config)
    original_llm.eval()

    original_response, _ = original_llm.chat(tokenizer=tokenizer, query=query,max_length=max_length, temperature=temperature)

### Environment

```markdown
- OS: centos 7.4
- Python: 3.9
- Transformers:4.29.2
- PyTorch:1.13.1+cu117
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) : yes
```

**Comment by thsno02** [comment]
试试，我感觉好很多。

```
任务：你是一个职业秘书，所以你能很好地完成指定的文案任务。现在请你写出给定文本的五个反义句。

示例文本：我不喜欢你。

示例答案：我喜欢你。

文本：民生银行应向客户事先送达有关机关的协助冻结、扣划存款通知书，方有权办理冻结、扣划手续。
```

**Comment by calvinzhan** [comment]
@thsno02 不知你那边跑出来什么结果，我试了下还是不行。见下面2个例子：

query = """任务：你是一个职业秘书，所以你能很好地完成指定的文案任务。现在请你写出给定文本的五个反义句。

示例文本：我不喜欢你。

示例答案：我喜欢你。

文本：民生银行应向客户事先送达有关机关的协助冻结、扣划存款通知书，方有权办理冻结、扣划手续。"""

1. 民生银行应向客户事先送达有关机关的协助冻结、扣划存款通知书，方可办理冻结、扣划手续。
2. 民生银行不得向客户事先送达有关机关的协助冻结、扣划存款通知书，否则将无法办理冻结、扣划手续。
3. 民生银行在办理冻结、扣划手续前，需先向客户送达有关机关的协助冻结、扣划存款通知书。
4. 民生银行有权向客户事先送达有关机关的协助冻结、扣划存款通知书，并依据此通知书办理冻结、扣划手续。
5. 民生银行不得在未向客户送达有关机关的协助冻结、扣划存款通知书的情况下，办理冻结、扣划手续。
----------------------------
query = """任务：你是一个职业秘书，所以你能很好地完成指定的文案任务。现在请你写出给定文本的五个反义句。

示例文本：客户可在民生银行允许的前提下内支取资金。

示例答案：客户在任何情况下不允许支取资金。

文本：民生银行应向客户事先送达有关机关的协助冻结、扣划存款通知书，方有权办理冻结、扣划手续。"""
1. 民生银行不得向客户提前送达有关机关的协助冻结、扣划存款通知书，否则将无法办理冻结、扣划手续。
2. 客户需要事先向民生银行提供有关机关的冻结、扣划通知书，民生银行才能办理相关手续。
3. 民生银行在办理冻结、扣划手续前，需先向客户送达冻结、扣划通知书。
4. 客户必须在收到民生银行有关机关的冻结、扣划通知书后，才能进行冻结、扣划操作。
5. 若民生银行在办理冻结、扣划手续时未向客户送达有关机关的冻结、扣划通知书，则冻结、扣划操作将无法进行。

**Comment by calvinzhan** [comment]
我在chatglm 130b上试了下，感觉达到大部分要求了。

指令：
“请写出下面句子的5个反义句
民生银行应向客户事先送达有关机关的协助冻结、扣划存款通知书，方有权办理冻结、扣划手续。”

回复：
民生银行不应向客户事先送达有关机关的协助冻结、扣划存款通知书，方有权办理冻结、扣划手续。
民生银行在办理冻结、扣划手续前，无需向客户送达有关机关的协助冻结、扣划存款通知书。
民生银行有权在未事先送达有关机关的协助冻结、扣划存款通知书的情况下，办理冻结、扣划手续。
民生银行向客户事先送达有关机关的协助冻结、扣划存款通知书，并非办理冻结、扣划手续的必要条件。
民生银行在办理冻结、扣划手续时，可以不考虑是否已向客户送达有关机关的协助冻结、扣划存款通知书。

**Comment by thsno02** [comment]
我在 chatglm2 上尝试了多次，效果看起来好了一些，但是质量和你的输出差不多。gpt-4 这样的输出的可能是你想要的：

```
1. "民生银行无需向客户事先送达任何有关机关的协助冻结、扣划存款通知书，就可以自行办理冻结、扣划手续。"
2. "民生银行在没有通知客户的情况下，可以由相关机关协助冻结、扣划存款。"
3. "即使没有相关机关的协助冻结、扣划存款通知书，民生银行也有权利直接办理冻结、扣划手续。"
4. "民生银行可以无需提前通知客户，即可由相关机关协助办理冻结、扣划存款手续。"
5. "民生银行可以在没有客户事先确认的情况下，直接办理冻结、扣划手续。"
```

尝试了几次调整 prompt，效果不是非常理想，但是比之前的好一些
```
任务：你是一个职业秘书，所以你能很好地完成指定的文案任务。现在请你使用准确、全面、详细、通畅的中文写出给定文本的五个反义句。

文本：民生银行应向客户事先送达有关机关的协助冻结、扣划存款通知书，方有权办理冻结、扣划手续。
```
