### ISSUE TITLE
[BUG/Help] 接入chatgpt-web 无法及时结束光标

### ISSUE THREAD

**Issue by codeleep** [THUDM/ChatGLM2-6B#170]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

在使用openAI的流式接口时，前端项目使用chatgpt-web会出现光标无法结束的情况。
![image](https://github.com/THUDM/ChatGLM2-6B/assets/56161468/7ec3ae6e-d5bb-48e7-a044-6854daad122a)

### Expected Behavior

期望是光标正常结束

### Steps To Reproduce

1. 启动模型
2. 启动前端

### Environment

```markdown
- OS: MacOS 
- Python: 3.10
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by duzx16** [comment]
https://github.com/THUDM/ChatGLM2-6B/pull/152 应该修复了这个问题，已经 merge 到 main分支了，可以试一下

**Comment by codeleep** [comment]
> #152 应该修复了这个问题，已经 merge 到 main分支了，可以试一下

事实上我已经合并了，但确实还是没有解决

**Comment by codeleep** [comment]
> #152 应该修复了这个问题，已经 merge 到 main分支了，可以试一下

提交的pr并没有在main分支，在dev_api分支
