### ISSUE TITLE
[Help] chatglm系列的预训练怎么做？

### ISSUE THREAD

**Issue by calvinzhan** [THUDM/ChatGLM2-6B#171]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

请问chatglm系列模型的预训练可以在发放的权重上用自回归的方式做吗？还是需要在glm上面做？如果是，训练方式可以用自回归吗？

想用chatglm进行继续预训练的目的是不想用大量语料再训练一个领域训练好的glm。我目前测下来，用chatglm直接在纯文本上用自回归训练，会导致丧失了对话能力。

谢谢回答！

### Steps To Reproduce

无

### Environment

```markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by duzx16** [comment]
请参考 GLM 和 GLM-130B 的论文
