### ISSUE TITLE
RuntimeError: CUDA error: unknown error

### ISSUE THREAD

**Issue by Hzzhang-nlp** [THUDM/ChatGLM2-6B#172]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

两个3060显卡...
![image](https://github.com/THUDM/ChatGLM2-6B/assets/39661319/0337f425-f193-4df6-8976-6259c6c15230)

### Steps To Reproduce

Run python cli_demo.py report
![image](https://github.com/THUDM/ChatGLM2-6B/assets/39661319/4854b6a8-6421-4d41-b217-feed8b9de767)

### Environment

```markdown
- OS:Ubuntu 20.04
- Python:3.10
- Transformers:4.30.2
- PyTorch:2.0.1
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :True
```

**Comment by duzx16** [comment]
环境本身有问题吧，可以试一下 `torch.randn(10,10).cuda() ** 2` 这种简单的 cuda 计算能否跑通
