### ISSUE TITLE
[Help] <关于Flash-Attention的一些疑惑>

### ISSUE THREAD

**Issue by yeeeqichen** [THUDM/ChatGLM2-6B#174]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

想请问一下作者，所提到的训练及推理使用了Flash-Attention优化，我查阅文档后发现，目前Flash-Attention已经被整合进`torch 2.0`当中，具体文档参考：

- https://huggingface.co/docs/transformers/v4.30.0/en/perf_train_gpu_one#using-pytorch-native-attention

我的疑问在于：我并没有在代码中发现 `model.to_bettertransformer()`的调用，或者 `torch.backends.cuda.enable_flash_sdp()`

按照PyTorch 官方文档的说明，默认会视情况自动使用flash_sdp 或者 mem_efficient_sdp

因此想请问一下作者，`README`文档中的表述是否不够严谨，抑或是代码中有特殊的语句保证了使用了这一特定 CUDA 核心？

### Steps To Reproduce

如题

### Environment

```markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by Youggls** [comment]
`PreTrainedModel.to_bettertransformer()` 只适用于官方支持的模型，从 [optimum](https://github.com/huggingface/optimum/blob/main/optimum/bettertransformer/models/__init__.py#L49)的支持模型列表可以看到，目前 ChatGLM 并未被支持。

`flash sdp` 功能应该是默认开启了，我在 `torch 2.0.1` 和 `cuda 12.1` 环境下，通过 `torch.backends.cuda.flash_sdp_enabled()` API 发现默认已经开启了 fash attention。

**Comment by yeeeqichen** [comment]
@Youggls 感谢解答
