### ISSUE TITLE
main.py 的preprocess_function_train函数 是不是有问题

### ISSUE THREAD

**Issue by GUORUIWANG** [THUDM/ChatGLM2-6B#179]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Current Behavior

训练几个steps迭代后出现：

transformers/tokenization_utils_b │ ase.py:718
❱  718 │   │   │   │   │   tensor = as_tensor(value)
ValueError: expected sequence of length 1280 at dim 1 (got 1281)

main.py:363  
│ ❱ 363 │   │   train_result = trainer.train(resume_from_checkpoint=checkpoint)  
ValueError: Unable to create tensor, you should probably activate truncation and/or padding with 'padding=True' 'truncation=True' to have batched tensors with the same length. Perhaps your features (`input_ids` in this case) have excessive nesting (inputs type `list` where type `int` is expected).

### Expected Behavior

帮忙看下

### Steps To Reproduce

默认

### Environment

```markdown
默认
```

### Anything else?

none

**Comment by FLLLIGHT** [comment]
> 

同出现这个问题，怀疑是和max_source_length以及max_target_length的配置有关，超出长度后没有截断？

**Comment by lilongxian** [comment]
友情链接：复现清华chatGLM2-6B模型指令微调训练模型（2023-07-04 18：00）开源：
https://github.com/THUDM/ChatGLM2-6B
可以支持GPU  CPU训练、支持chatGLM-6B微调训练数据格式，和alpaca指令微调训练数据格式。
但CPU训练我用了fp32未量化微调训练，很是耗费内存。推荐大家使用GPU训练。
相关文档我会加紧编辑上传，力挺清华GLM社区！

**Comment by GUORUIWANG** [comment]
> > 
> 
> 同出现这个问题，怀疑是和max_source_length以及max_target_length的配置有关，超出长度后没有截断？

应该是的，你有解决吗

**Comment by GUORUIWANG** [comment]
> 友情链接：复现清华chatGLM2-6B模型指令微调训练模型（2023-07-04 18：00）开源： https://github.com/THUDM/ChatGLM2-6B 可以支持GPU CPU训练、支持chatGLM-6B微调训练数据格式，和alpaca指令微调训练数据格式。 但CPU训练我用了fp32未量化微调训练，很是耗费内存。推荐大家使用GPU训练。 相关文档我会加紧编辑上传，力挺清华GLM社区！

？？？有遇到这个问题

**Comment by duzx16** [comment]
已经修复了，可以再尝试一下

**Comment by GUORUIWANG** [comment]
> 已经修复了，可以再尝试一下

谢谢回复，我试了一下，还是存在，看了下代码没有看到有变更的记录呀

**Comment by smilelight** [comment]
+1,同样有问题

**Comment by mantianlong** [comment]
+1,同样有问题

**Comment by GUORUIWANG** [comment]
可以多留2个token 长度
max_seq_length = data_args.max_source_length + data_args.max_target_length+2

**Comment by FLLLIGHT** [comment]
> 可以多留2个token 长度 max_seq_length = data_args.max_source_length + data_args.max_target_length+2

用这个方法可以训了，但是我训到1000个step之后loss开始变大了，用的指令数据量是261k，你有碰到这个问题嘛

**Comment by smilelight** [comment]
> 可以多留2个token 长度 max_seq_length = data_args.max_source_length + data_args.max_target_length+2

确实可行，感谢 @GUORUIWANG

**Comment by GUORUIWANG** [comment]
> > 可以多留2个token 长度 max_seq_length = data_args.max_source_length + data_args.max_target_length+2
> 
> 用这个方法可以训了，但是我训到1000个step之后loss开始变大了，用的指令数据量是261k，你有碰到这个问题嘛
我这边是正常的，建议你调整一下学习率 和batch大小

**Comment by GUORUIWANG** [comment]
> > 可以多留2个token 长度 max_seq_length = data_args.max_source_length + data_args.max_target_length+2
> 
> 用这个方法可以训了，但是我训到1000个step之后loss开始变大了，用的指令数据量是261k，你有碰到这个问题嘛

我这边是正常的，建议你调整一下学习率 和batch大小

**Comment by FLLLIGHT** [comment]
> > > 可以多留2个token 长度 max_seq_length = data_args.max_source_length + data_args.max_target_length+2
> > 
> > 
> > 用这个方法可以训了，但是我训到1000个step之后loss开始变大了，用的指令数据量是261k，你有碰到这个问题嘛
> 
> 我这边是正常的，建议你调整一下学习率 和batch大小

改了学习率之后可以了，感谢

**Comment by Julylmm** [comment]
> 

+1，没看到代码有变更记录，拉取了最新的代码，还是有这个问题

**Comment by ZacharyWaseda** [comment]
+1，没看到代码有变更记录，拉取了最新的代码，还是有这个问题

**Comment by lilongxian** [comment]
可以参考我7月4日同一时间开源的项目：
https://github.com/lilongxian/LL-BaiYang/tree/main
复现chatGLM2-6B微调训练过程中预先对于这类问题做了控制，并且支持alpaca数据格式的指令微调，支持单任务多任务的知识挖掘、摘要、对话，支持GPU、CPU

**Comment by yongshuai** [comment]
> > > > 可以多留2个token 长度 max_seq_length = data_args.max_source_length + data_args.max_target_length+2
> > > 
> > > 
> > > 用这个方法可以训了，但是我训到1000个step之后loss开始变大了，用的指令数据量是261k，你有碰到这个问题嘛
> > 
> > 
> > 我这边是正常的，建议你调整一下学习率 和batch大小
> 
> 改了学习率之后可以了，感谢

请问学习率是改成多少才可以的？

**Comment by FLLLIGHT** [comment]
> > > > > 可以多留2个token 长度 max_seq_length = data_args.max_source_length + data_args.max_target_length+2
> > > > 
> > > > 
> > > > 用这个方法可以训了，但是我训到1000个step之后loss开始变大了，用的指令数据量是261k，你有碰到这个问题嘛
> > > 
> > > 
> > > 我这边是正常的，建议你调整一下学习率 和batch大小
> > 
> > 
> > 改了学习率之后可以了，感谢
> 
> 请问学习率是改成多少才可以的？

5e-4，供参考
