### ISSUE TITLE
[BUG/Help] 使用本地部署报错Tokenizer class ChatGLMTokenizer does not exist or is not currently imported

### ISSUE THREAD

**Issue by WannaTen** [THUDM/ChatGLM2-6B#184]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

tokenizer = AutoTokenizer.from_pretrained("/ai/chatglm2-6b/", trust_romote_code=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 688, in from_pretrained
    raise ValueError(
ValueError: Tokenizer class ChatGLMTokenizer does not exist or is not currently imported.

### Expected Behavior

无报错

### Steps To Reproduce

执行GIT_LFS_SKIP_SMUDGE=1 git clone https://huggingface.co/THUDM/chatglm2-6b
然后从https://cloud.tsinghua.edu.cn/d/674208019e314311ab5c/?p=%2Fchatglm2-6b&mode=list下载文件覆盖本地bin文件，

再执行示例代码：
\>\>\> from transformers import AutoTokenizer, AutoModel
\>\>\> tokenizer = AutoTokenizer.from_pretrained("/ai/chatglm2-6b/", trust_romote_code=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 688, in from_pretrained
    raise ValueError(
ValueError: Tokenizer class ChatGLMTokenizer does not exist or is not currently imported.

其中，"/ai/chatglm2-6b/"就是本地绝对路径。
版本：
# pip3 list | grep trans
transformers             4.30.2

### Environment

```markdown
- OS: Linux fedora37
- Python: 3.10
- Transformers:  4.30.2
- PyTorch: 2.0.1
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) : True
```

**Comment by duzx16** [comment]
设置 `trust_romote_code=True`

**Comment by WannaTen** [comment]
> 设置 `trust_romote_code=True`
抱歉, 贴了一个误导报错, 实际上, 我设置为true也是这个报错

![image](https://github.com/THUDM/ChatGLM2-6B/assets/16740055/32d69cb1-c6d0-4315-b619-52be8276eae7)

**Comment by Hansen06** [comment]
解决了吗

**Comment by wbok** [comment]
可能是transformers版本问题
transformers==4.27.1

**Comment by jesuswa** [comment]
对呀，这个问题解决了吗？

**Comment by li-yang23** [comment]
> > 设置 `trust_romote_code=True`
> 
> 抱歉, 贴了一个误导报错, 实际上, 我设置为true也是这个报错
> 
> ![image](https://private-user-images.githubusercontent.com/16740055/250936650-32d69cb1-c6d0-4315-b619-52be8276eae7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzMDU4MDAsIm5iZiI6MTcxNTMwNTUwMCwicGF0aCI6Ii8xNjc0MDA1NS8yNTA5MzY2NTAtMzJkNjljYjEtYzZkMC00MzE1LWI2MTktNTJiZTgyNzZlYWU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEwVDAxNDUwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxYWY1MjczM2ZmM2E4MzcyMjNiMDlhZDg0OWEwNzVmNDdmNTA5NDFlZGVlOGVmNGQ3ZGQyNGI2YzU5NzdjZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VK5BTAqQCRQsjdZO2MZlZI_F6-oQbum40pXwoQPsTbw)

 我把模型文件下到本地，然后设置`trust_remote_code=True`就能正常运行了，不知道是什么原因...我使用的模型id是`ZhipuAI/chatglm3-6b`
