### ISSUE TITLE
[BUG/Help] 想明白模型代码里的multi_query_group_num参数是如何确定为2的，是综合考虑性能和指标吗

### ISSUE THREAD

**Issue by DeerEyre** [THUDM/ChatGLM2-6B#190]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Current Behavior

看到本项目中使用的muti_query_attention 的group数为2，想知道这个2是如何确定下来的，为什么不是1，3或者其他数字

### Expected Behavior

麻烦有志之士给个解答。

### Steps To Reproduce

看到本项目中使用的muti_query_attention 的group数为2，想知道这个2是如何确定下来的，为什么不是1，3或者其他数字

### Environment

```markdown
OS: Ubuntu 20.04
Python: 3.8
Transformers: 4.26.1
PyTorch: 1.12
CUDA Support: True
```

### Anything else?

nothing

**Comment by duzx16** [comment]
因为预训练的时候 tensor parallel 数是2
