### ISSUE TITLE
[Help]  multi query attention kv的参数少了 为什么模型的效果更好呢 

### ISSUE THREAD

**Issue by HJT9328** [THUDM/ChatGLM2-6B#194]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

看过源码，是否可以理解为，在模型大小相同的情况下，与query相关的参数更多了，效果更好呢？

### Steps To Reproduce

如题

### Environment

```markdown
非环境问题
```

**Comment by duzx16** [comment]
multi-query 是为了节省显存和加速计算，跟模型效果无关
