### ISSUE TITLE
[BUG/Help] <用文档中方式训练时报错>:AttributeError: 'Seq2SeqTrainer' object has no attribute 'is_deepspeed_enabled'

### ISSUE THREAD

**Issue by shopflyer-df** [THUDM/ChatGLM2-6B#196]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

我在按照文档中的方式训练时，报错，具体定位在:
 /ChatGLM2-6B/ptuning/main.py:350 in main                                        
                                                                                          
│ ❱ 350 │   │   train_result = trainer.train(resume_from_checkpoint=checkpoint)

│ /ChatGLM2-6B/ptuning/trainer.py:1636 in train                                             

│   1633 │   │   inner_training_loop = find_executable_batch_size(                          
│   1634 │   │   │   self._inner_training_loop, self._train_batch_size, args.auto_find_batch_size                                                            
│ ❱ 1636 │   │   return inner_training_loop(                                                 
                                                                                        
│ /ChatGLM2-6B/ptuning/trainer.py:1982 in _inner_training_loop                                                                           
│ ❱ 1982 │   │   │   │   │   self._maybe_log_save_evaluate(tr_loss, model, trial, epoch, ignore_k  
                                                                          
│ /ChatGLM2-6B/ptuning/trainer.py:2221 in _maybe_log_save_evaluate                            
│ ❱ 2221 │   │   │   logs["learning_rate"] = self._get_learning_rate()                    
                                                                                           
│ /usr/local/lib/python3.8/dist-packages/transformers/trainer_pt_utils.py:841 in             
│ _get_learning_rate                                                                                                                                                 
│    840 def _get_learning_rate(self):                                                         
│ ❱  841 │   if self.is_deepspeed_enabled:                                                         

请问不知道我哪一步的配置有问题,，我只改动了train.sh和evaluate.sh

### Steps To Reproduce

下载官方文档中的ADGEN的数据集，然后按照文档进行配置和训练，在ptuning目录下运行./train.sh后，在8/3000左右报错。没有训练之前，除了openaiapi.py运行不了，其他都正常。
train.sh:
PRE_SEQ_LEN=128
LR=2e-2
NUM_GPUS=1
MODEL_NAME_OR_PATH=/ChatGLM2-6B/models/chatglm2-6b
torchrun --standalone --nnodes=1 --nproc-per-node=$NUM_GPUS main.py \
    --do_train \
    --train_file AdvertiseGen/train.json \
    --validation_file AdvertiseGen/dev.json \
    --preprocessing_num_workers 10 \
    --prompt_column content \
    --response_column summary \
    --overwrite_cache \
    --model_name_or_path $MODEL_NAME_OR_PATH \
    --output_dir output/train-chatglm2-6b-pt-$PRE_SEQ_LEN-$LR \
    --overwrite_output_dir \
    --max_source_length 64 \
    --max_target_length 128 \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 1 \
    --gradient_accumulation_steps 16 \
    --predict_with_generate \
    --max_steps 3000 \
    --logging_steps 10 \
    --save_steps 1000 \
    --learning_rate $LR \
    --pre_seq_len $PRE_SEQ_LEN \
    --quantization_bit 4

evaluate.sh:
PRE_SEQ_LEN=128
CHECKPOINT=train-chatglm2-6b-pt-128-2e-2
MODEL_NAME_OR_PATH=/ChatGLM2-6B/models/chatglm2-6b
STEP=3000
NUM_GPUS=1

torchrun --standalone --nnodes=1 --nproc-per-node=$NUM_GPUS main.py \
    --do_predict \
    --validation_file AdvertiseGen/dev.json \
    --test_file AdvertiseGen/dev.json \
    --overwrite_cache \
    --prompt_column content \
    --response_column summary \
    --model_name_or_path $MODEL_NAME_OR_PATH \
    --ptuning_checkpoint ./output/$CHECKPOINT/checkpoint-$STEP \
    --output_dir ./output/$CHECKPOINT \
    --overwrite_output_dir \
    --max_source_length 64 \
    --max_target_length 64 \
    --per_device_eval_batch_size 1 \
    --predict_with_generate \
    --pre_seq_len $PRE_SEQ_LEN \
    --quantization_bit 4

### Environment

```markdown
- OS:Ubuntu 20.04
- Python:3.8.10
- Transformers:4.30.2
- PyTorch:2.0.1
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :true
```

**Comment by Smilefish1** [comment]
相同的错误，哭哭

**Comment by shenmadouyaowen** [comment]
看这个帖子
#175
