### ISSUE TITLE
[BUG/Help] <title>是否可以复用ChatGLM-6B的方式做微调？性能如何？

### ISSUE THREAD

**Issue by yucc-leon** [THUDM/ChatGLM2-6B#2]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

指 ptuning-v2 的方式：https://github.com/THUDM/ChatGLM-6B/blob/main/ptuning/README.md 

### Steps To Reproduce

Not yet.

### Environment

```markdown
OS: Ubuntu 20.04
Python: 3.8
Transformers: 4.26.1
PyTorch: 1.12
CUDA Support: True
```

**Comment by dragononly** [comment]
同样的疑问，等回答

**Comment by wwngh1233** [comment]
能否公开若干测试集的评测脚本？

**Comment by qihangf** [comment]
cy

**Comment by SZ-ing** [comment]
同问，顺便想问下后续会开放33B的模型吗？

**Comment by liuhuapiaoyuan** [comment]
同样疑问，求解答

**Comment by Xzaohui** [comment]
目前看好像p tuning和lora都还没支持

**Comment by lcxxxasd** [comment]
同问

**Comment by Lumingous** [comment]
同问

**Comment by beyondguo** [comment]
https://github.com/beyondguo/LLM-Tuning

这里实现了 ChatGLM 和 ChatGLM2 的 LoRA 微调，两行命令就可以跑。

根据目前少量的特殊任务的实验，ChatGLM2 微调之后并没有比 ChatGLM 更好，不过只是我少量的、特殊的实验。

**Comment by duzx16** [comment]
https://github.com/THUDM/ChatGLM2-6B/tree/main/ptuning
已经实现了跟一代一样的 p-tuning v2 和 全参数微调

**Comment by nzinfo** [comment]
@duzx16 实验后，在 q4 量化的模型上进行 p-tuning v2 微调（其他参数同 train.sh），原有模型的知识出现了大量的遗忘，无法正确回答 “我是谁“ 以及输出过程中大量出现 UNK 。
