### ISSUE TITLE
支持清华chatGLM2-6B的另一版本指令微调模型BaiYang可顺利训练供大家研究

### ISSUE THREAD

**Issue by lilongxian** [THUDM/ChatGLM2-6B#203]
### Is your feature request related to a problem? Please describe.

基于清华chatGLM2-6B的指令微调模型LL-BaiYang 供大家参考。
https://github.com/lilongxian/LL-BaiYang

### Solutions

7月4日同一时间我也开源发布了一个基于清华chatGLM2-6B的指令微调模型LL-BaiYang，是自6月30日对chatGLM2-6B源代码网络建设、数据建模反向深入研究基础上，参考了清华chatGLM-6B高效微调方法搞出来的，由于清华GLM2使用的新技术很多，在GLM1基础上多了很大改进（MLP、RMSnorm、SDPA与MQA、Add残差链接点变化、32768旋转位置编码器与position_ids位置向量表征+qk信息融合、上三角att_mask机制、训练数据向量化建模【a句 [gmask][sop] b句 [eop]】、特殊token、tokenization的decode修复和build_inputs_with_special_tokens的ab句链接修复），反研过程不易，为方便大家学习和研究，进一步支持和扩大清华GLM大模型社区，在第一时间开源出来。
支持GPU量化高效训练、CPU全参数训练，
支持chatGLM数据格式和alpaca数据格式，
支持单任务知识挖掘、多任务知识挖掘、多轮对话。

后续还将参考伯克利的万级tokens支持算法，对比集成。

https://github.com/lilongxian/LL-BaiYang

**Comment by hlwgy** [comment]
先给你点赞！

**Comment by xldistance** [comment]
训练好的模型怎么加载啊
