### ISSUE TITLE
[BUG/Help]RuntimeError: The size of tensor a (1152) must match the size of tensor b (1024) at non-singleton dimension 3

### ISSUE THREAD

**Issue by ljch2018** [THUDM/ChatGLM2-6B#205]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

RuntimeError: The size of tensor a (1152) must match the size of tensor b (1024) at non-singleton dimension 3

### Expected Behavior

无异常

### Steps To Reproduce

sh evaluate.sh

### Environment

```markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by ljch2018** [comment]
PRE_SEQ_LEN=128
NUM_GPUS=1

BASE_MODEL=glm/chatglm2-6b
CHECKPOINT=output/intent-chatglm2-6b-pt/checkpoint-100

torchrun --standalone --nnodes=1 --nproc-per-node=$NUM_GPUS main.py \
    --do_predict \
    --validation_file IntentClassify/dev.json \
    --test_file IntentClassify/dev.json \
    --overwrite_cache \
    --prompt_column prompt \
    --response_column output \
    --model_name_or_path ${BASE_MODEL} \
    --ptuning_checkpoint ${CHECKPOINT} \
    --output_dir ./output/$CHECKPOINT \
    --overwrite_output_dir \
    --max_source_length 1024 \
    --max_target_length 128 \
    --per_device_eval_batch_size 16 \
    --predict_with_generate \
    --pre_seq_len $PRE_SEQ_LEN \
    --quantization_bit 4

**Comment by lilongxian** [comment]
增加输入长度整定，表示propmt和response的数据点tokens长度整定到你指定长度：
--max_source_length 1024
--max_target_length 128

**Comment by ljch2018** [comment]
从HF更新模型的配置和py文件，即可解决上述问题。

**Comment by NLPpupil** [comment]
> 

works for me

**Comment by LaylaYe** [comment]
> 从HF更新模型的配置和py文件，即可解决上述问题。

能具体说一下怎么操作的吗

**Comment by evyy1234** [comment]
> 从HF更新模型的配置和py文

HF在哪里呢？能具体点嘛
