### ISSUE TITLE
[help]模型文件中的full_attention_mask变量是啥含义？

### ISSUE THREAD

**Issue by stewnn-alt** [THUDM/ChatGLM2-6B#209]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Current Behavior

 这个变量是啥含义

### Steps To Reproduce

no response

### Environment

```markdown
no response
```

**Comment by duzx16** [comment]
对 attention score 使用的 attention_mask，区别于 `transformers` 中的 attention_mask 指的是 token 是否是有效的

**Comment by XiaokunDing** [comment]
> 

还是没有明白full_attention_mask 的作用， 看上去在预测的时候full_attention_mask 一直是空，并且替换掉了非空 的attention_mask，请问：这是做了什么优化吗？预测时候是不需要 maks吗？ --thanks
