### ISSUE TITLE
[BUG/Help] <title>RuntimeError: Internal: src/sentencepiece_processor.cc(1101) [model_proto->ParseFromArray(serialized.data(), serialized.size())] 

### ISSUE THREAD

**Issue by dongxinghua** [THUDM/ChatGLM2-6B#21]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

这个错误怎么出现的，怎么解决？ 看ChatGLM 是ice_text.model这个文件没下载对，但 huggingface  chatglm2 没看到这个文件 

### Expected Behavior

如何解决

### Steps To Reproduce

chatglm2

### Environment

```markdown
- OS:
- Python:3
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

### Anything else?

如何解决

**Comment by duzx16** [comment]
ChatGLM2-6B 里是 `tokenizer.model` 文件

**Comment by sungh66** [comment]
> ChatGLM2-6B 里是 `tokenizer.model` 文件

我有这个文件，但是还是会报这个错误，有什么解决方法吗

**Comment by yata0** [comment]
> > ChatGLM2-6B 里是 `tokenizer.model` 文件
> 
> 我有这个文件，但是还是会报这个错误，有什么解决方法吗

请问最后是怎么解决的

**Comment by songyongkang** [comment]
同问，我也遇到了相同的问题

**Comment by hellomaxwell** [comment]
ChatGLM2-6B 里是 tokenizer.model 文件  没看懂这句话啥意思？如何解决这个bug？

**Comment by chansonZ** [comment]
从这里：https://huggingface.co/THUDM/chatglm2-6b/tree/main
把~1M的文件手动下载过来，几秒钟即可：

![image](https://github.com/THUDM/ChatGLM2-6B/assets/5253350/007d90c0-6a98-4e78-9b41-d1828e250ec0)
