### ISSUE TITLE
[BUG/Help] RuntimeError: "addmm_impl_cpu_" not implemented for 'Half'怎么办

### ISSUE THREAD

**Issue by heiheiheibj** [THUDM/ChatGLM2-6B#211]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

chatglm2-6b-int4\quantization.py 显卡太差用的int4的模型+CPU出错

### Steps To Reproduce

  File "D:\ProgramData\Anaconda3\envs\chatgpt6b2\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\Administrator/.cache\huggingface\modules\transformers_modules\chatglm2-6b-int4\quantization.py", line 320, in forward
    output = W8A16LinearCPU.apply(input, self.weight, self.weight_scale, self.weight_bit_width)
  File "D:\ProgramData\Anaconda3\envs\chatgpt6b2\lib\site-packages\torch\autograd\function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "C:\Users\Administrator/.cache\huggingface\modules\transformers_modules\chatglm2-6b-int4\quantization.py", line 225, in forward
    output = inp.mm(weight.t())
RuntimeError: "addmm_impl_cpu_" not implemented for 'Half'

### Environment

```markdown
- OS:win10
- Python:3.10
- Transformers:
- PyTorch:2.01 CPU
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

### Anything else?

另外在ichatglm2-6b-int4下的config.json中好象有点问题，"_name_or_path": 应当写成 "THUDM/chatglm2-6b-int4"吧

**Comment by lilongxian** [comment]
@heiheiheibj   目前CPU运行似乎不支持FP16半精度加载，你可以把模型配置文件里的torch_type改为float32，在加载模型后注释掉 model.half() 试试。
1. 推荐使用GPU, 按照GLM官方文档操作即可以顺利执行。
2. 我在CPU上训练LLAMA时曾这样搞过（这个时候我没有改config,json，可以正常训练，消耗36G左右内存）：
model =  LlamaForCausalLM.from_pretrained(
        pretrained_model_name_or_path=model_args.model_name_or_path,
        load_in_8bit=False,
        config=glm_config,
        low_cpu_mem_usage=True,  # 使能cpu低使用率
        # torch_dtype=model_args.torch_dtype, 
        device_map='auto' 
    )
if device == torch.device('cpu'):
        model.float()
CPU训练时要全局禁用gpu，并且对于GLM模型，还要注释掉模型的量化方法（因为她需要GPU  CUDA）.

**Comment by lilongxian** [comment]
THUDM/chatglm2-6b-int4相关配置、权重等文件最好配套，下载好后GPU运行不需要修改config.json，模型config没问题

**Comment by heiheiheibj** [comment]
非常感谢
