### ISSUE TITLE
[BUG/Help] <title> 模型加载时设置config.pre_seq_len后预测有乱码。

### ISSUE THREAD

**Issue by lyhue1991** [THUDM/ChatGLM2-6B#213]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

chatglm2-6b加载模型时设置 config.pre_seq_len参数后，预测出现乱码。但老版本chatglm-6b是不受影响的。
怀疑该部分预测解码逻辑有问题，导致Ptuning效果很差。

模型加载部分修改如下：
<img width="600" alt="image" src="https://github.com/THUDM/ChatGLM2-6B/assets/30676974/23680a45-634a-4fe8-91d6-7cf78a09bd3c">

结果会出现乱码：

<img width="629" alt="image" src="https://github.com/THUDM/ChatGLM2-6B/assets/30676974/52f358ef-a5aa-472f-a65c-f3b77635b7d4">

### Steps To Reproduce

1，加载模型时 设置  config.pre_seq_len 
2，调用model.chat方法

### Environment

```markdown
- OS:
- Python: 3.8
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by duzx16** [comment]
设置了 `pre_seq_len` 之后相当于 ptuning的参数是随机初始化的，一定会影响到生成内容。如果是要加载 ptuning 后的 checkpoint 请参考 https://github.com/THUDM/ChatGLM2-6B/tree/main/ptuning#%E6%A8%A1%E5%9E%8B%E9%83%A8%E7%BD%B2

**Comment by lyhue1991** [comment]
@duzx16 但是chatglm-6b 是可以这样加载的，并且预测不会有乱码。这个是为什么呢？
