### ISSUE TITLE
请告诉我这个提示是什么意思？ Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.

### ISSUE THREAD

**Issue by WangShunzhiDQ** [THUDM/ChatGLM2-6B#22]
### Solutions

Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.   如何修改参数？

**Comment by 70557dzqc** [comment]
pad_token_id和eos_token_id相同，都为2

**Comment by huashiyiqike** [comment]
怎么取消这个提示？

**Comment by gongye19** [comment]
model.config.pad_token_id = model.config.eos_token_id

**Comment by huashiyiqike** [comment]
> model.config.pad_token_id = model.config.eos_token_id

这个试了没用，先改用输出重定向了

**Comment by QuantumDriver** [comment]
直白的意思就是说两个参数设置成2就完了。`model.chat(tokenizer, prompt, history=[], eos_token_id=2, pad_token_id=2)`
详细解释可以看这个：https://stackoverflow.com/questions/69609401/suppress-huggingface-logging-warning-setting-pad-token-id-to-eos-token-id

**Comment by gongye19** [comment]
> , eos_token_id=2, pad_token_id=2

牛的 解决了

**Comment by sujianwei1** [comment]
这个可以
`outputs = model.generate(**inputs, max_new_tokens=2048, use_cache=True, pad_token_id=tokenizer.eos_token_id)`

**Comment by sujianwei1** [comment]
> > model.config.pad_token_id = model.config.eos_token_id
> 
> 这个试了没用，先改用输出重定向了

确实没用
