### ISSUE TITLE
[BUG/Help] 不是很理解ChatGLMTokenizer的encode函数，或者build_inputs_with_special_tokens函数

### ISSUE THREAD

**Issue by yongzhuo** [THUDM/ChatGLM2-6B#221]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Tokenizer的，encode函数，或者build_inputs_with_special_tokens函数
测试：
    tokenizer = ChatGLMTokenizer("tokenizer.model")
    tokenizer.padding_side = "left"
    max_length = 128
    source = "你好"
    target = "你好"
    a_ids = tokenizer.encode(text=source, add_special_tokens=True, truncation=True,
                             max_length=max_length)
    b_ids = tokenizer.encode(text=target, add_special_tokens=False, truncation=True,
                             max_length=max_length)
    input_ids = a_ids + b_ids + [tokenizer.eos_token_id]

    print(a_ids)
    print(b_ids)
    print(input_ids)
输出：
    [64790, 64792, 36474, 54591]
    [36474, 54591]
    [64790, 64792, 36474, 54591, 36474, 54591, 2]

### Expected Behavior

build_inputs_with_special_tokens;

不是很理解为什么是 [ID_gMASK, ID_SOP] + text_1 + text_2 + [ID_EOS]的编码，

感觉上应该是  text_1 + [ID_gMASK, ID_SOP] + text_2 + [ID_EOS]

或者是[ID_gMASK, ID_SOP] + text_1 + [ID_gMASK, ID_SOP] + text_2 + [ID_EOS]？

### Steps To Reproduce

不是很理解为什么是 [ID_gMASK, ID_SOP] + text_1 + text_2 + [ID_EOS]的编码，

感觉上应该是  text_1 + [ID_gMASK, ID_SOP] + text_2 + [ID_EOS]

或者是[ID_gMASK, ID_SOP] + text_1 + [ID_gMASK, ID_SOP] + text_2 + [ID_EOS]？

### Environment

```markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by yongzhuo** [comment]
看起来是不能这么改了
问题：1+1=
拼接：[gMASK, sop] + token_ids_0 #### 答案1: 1+1=2。
拼接：token_ids_0 + [gMASK, sop] #### 答案2.1: Hello! How can I assist you today?
拼接：token_ids_0 + [gMASK, sop] #### 答案2.2: 【问题】 【解答： 没有，tected，没有。 解答：protected，所以没有。
拼接：[gMASK, sop] + token_ids_0 + [gMASK, sop] #### 答案3.1: the sum of 1 and 1 is 2.
拼接：[gMASK, sop] + token_ids_0 + [gMASK, sop] #### 答案3.2: of course, 1+1=2
拼接：[gMASK, sop] + token_ids_0 + [gMASK, sop] #### 答案3.3: 1+1=2。
拼接：[gMASK, sop] + token_ids_0 + [BOS=1] #### 答案4.1: ""

**Comment by fxb392** [comment]
chatGLM2的词表中的bos和eos换成了sop和eop了吗？
