### ISSUE TITLE
[BUG/Help] <title>Help,运行train.sh后报错

### ISSUE THREAD

**Issue by HBdingdang** [THUDM/ChatGLM2-6B#222]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![屏幕截图 2023-07-05 220300](https://github.com/THUDM/ChatGLM2-6B/assets/130053388/7ab668f8-8f00-4e59-a36c-b13298baa151)
出现该报错怎么办

### Steps To Reproduce

相关依赖已安装，改变了模型路径为本地路径，train后出现该错误
![屏幕截图 2023-07-06 144605](https://github.com/THUDM/ChatGLM2-6B/assets/130053388/ccc9ffb1-1064-4890-88d3-4e977abb98d5)

### Environment

```markdown
- OS:20.04
- Python:3.8
- Transformers:4.30.2
- PyTorch:2.0.1
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by lilongxian** [comment]
从hf拉取最新的模型代码，支持注意力前置编码器的。transformers建议 4.27.1---4.29.2

**Comment by HBdingdang** [comment]
已解决，可以训练了，感谢
