### ISSUE TITLE
[Feature] <title>AttributeError: 'Seq2SeqTrainer' object has no attribute 'is_deepspeed_enabled'

### ISSUE THREAD

**Issue by Alionisme** [THUDM/ChatGLM2-6B#223]
### Is your feature request related to a problem? Please describe.

<img width="1109" alt="image" src="https://github.com/THUDM/ChatGLM2-6B/assets/14228939/c55744cb-0af4-4e46-a69c-c781450829a8">
训练固定10/3000报错

### Solutions

<img width="1109" alt="image" src="https://github.com/THUDM/ChatGLM2-6B/assets/14228939/294639ad-21d9-4ff1-8422-aacaec7fd37c">
高效参数微调报错

**Comment by w1130150306** [comment]
transformers降级
pip install transformers==4.27.1

**Comment by Alionisme** [comment]
降级 transformer 到 4.29解决了。
pip uninstall transformers
pip install transformers==4.29.0

**Comment by duzx16** [comment]
请使用仓库中最新的代码
