### ISSUE TITLE
[BUG/Help] <title>chatglm2 ptuning train.sh 代码错误，请订正

### ISSUE THREAD

**Issue by deepwebney** [THUDM/ChatGLM2-6B#225]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

ptuning 代码train.sh这行torchrun --standalone --nnodes=1 --nproc-per-node=$NUM_GPUS main.py \有错，应该是下划线，原来文档写成减号了，所以torchrun会报unrecognized arguments

### Steps To Reproduce

bash train.sh

### Environment

```markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by duzx16** [comment]
没看懂什么意思，你觉得应该改成什么？

**Comment by deepwebney** [comment]
> 没看懂什么意思，你觉得应该改成什么？

--nproc-per-node 改成--nproc_per_node

**Comment by vip68** [comment]
没错啊，是你的版本有问题吧

**Comment by duzx16** [comment]
> --nproc_per_node

这个是 pytorch 官方推荐的使用方法 https://pytorch.org/docs/stable/elastic/run.html#usage

**Comment by leacoleaco** [comment]
请问后来是怎么解决的呀~ 我也报了这个错误

**Comment by SHITIANYU-hue** [comment]
--nproc-per-node 改成--nproc_per_node
改成这样我的可以跑了
