### ISSUE TITLE
[BUG/Help] <运行 ds_train_finetune.sh文件报错'Seq2SeqTrainer' object has no attribute 'accelerator'>

### ISSUE THREAD

**Issue by LittleXu1998** [THUDM/ChatGLM2-6B#233]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /hy-tmp/ChatGLM2-6B/ptuning/main.py:412 in <module>                                              │
│                                                                                                  │
│   409                                                                                            │
│   410                                                                                            │
│   411 if __name__ == "__main__":                                                                 │
│ ❱ 412 │   main()                                                                                 │
│   413                                                                                            │
│                                                                                                  │
│ /hy-tmp/ChatGLM2-6B/ptuning/main.py:351 in main                                                  │
│                                                                                                  │
│   348 │   │   #     checkpoint = last_checkpoint                                                 │
│   349 │   │   model.gradient_checkpointing_enable()                                              │
│   350 │   │   model.enable_input_require_grads()                                                 │
│ ❱ 351 │   │   train_result = trainer.train(resume_from_checkpoint=checkpoint)                    │
│   352 │   │   # trainer.save_model()  # Saves the tokenizer too for easy upload                  │
│   353 │   │                                                                                      │
│   354 │   │   metrics = train_result.metrics                                                     │
│                                                                                                  │
│ /hy-tmp/ChatGLM2-6B/ptuning/trainer.py:1635 in train                                             │
│                                                                                                  │
│   1632 │   │   inner_training_loop = find_executable_batch_size(                                 │
│   1633 │   │   │   self._inner_training_loop, self._train_batch_size, args.auto_find_batch_size  │
│   1634 │   │   )                                                                                 │
│ ❱ 1635 │   │   return inner_training_loop(                                                       │
│   1636 │   │   │   args=args,                                                                    │
│   1637 │   │   │   resume_from_checkpoint=resume_from_checkpoint,                                │
│   1638 │   │   │   trial=trial,                                                                  │
│                                                                                                  │
│ /hy-tmp/ChatGLM2-6B/ptuning/trainer.py:1704 in _inner_training_loop                              │
│                                                                                                  │
│   1701 │   │   │   or self.fsdp is not None                                                      │
│   1702 │   │   )                                                                                 │
│   1703 │   │   if args.deepspeed:                                                                │
│ ❱ 1704 │   │   │   deepspeed_engine, optimizer, lr_scheduler = deepspeed_init(                   │
│   1705 │   │   │   │   self, num_training_steps=max_steps, inference=resume_from_checkpoint      │
│   1706 │   │   │   )                                                                             │
│   1707 │   │   │   self.model = deepspeed_engine.module                                          │
│                                                                                                  │
│ /usr/local/miniconda3/envs/chatglm6/lib/python3.10/site-packages/transformers/deepspeed.py:340   │
│ in deepspeed_init                                                                                │
│                                                                                                  │
│   337 │   model = trainer.model                                                                  │
│   338 │   args = trainer.args                                                                    │
│   339 │                                                                                          │
│ ❱ 340 │   hf_deepspeed_config = trainer.accelerator.state.deepspeed_plugin.hf_ds_config          │
│   341 │                                                                                          │
│   342 │   # resume config update - some bits like `model` and `num_training_steps` only become   │
│   343 │   hf_deepspeed_config.trainer_config_finalize(args, model, num_training_steps)           │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'Seq2SeqTrainer' object has no attribute 'accelerator'

### Steps To Reproduce

envs:
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    defaults
_openmp_mutex             5.1                       1_gnu    defaults
accelerate                0.20.2                   pypi_0    pypi
aiofiles                  23.1.0                   pypi_0    pypi
aiohttp                   3.8.4                    pypi_0    pypi
aiosignal                 1.3.1                    pypi_0    pypi
altair                    5.0.0                    pypi_0    pypi
anyio                     3.6.2                    pypi_0    pypi
appdirs                   1.4.4                    pypi_0    pypi
argon2-cffi               21.3.0                   pypi_0    pypi
argon2-cffi-bindings      21.2.0                   pypi_0    pypi
arrow                     1.2.3                    pypi_0    pypi
asttokens                 2.2.1                    pypi_0    pypi
async-timeout             4.0.2                    pypi_0    pypi
attrs                     23.1.0                   pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
beautifulsoup4            4.12.2                   pypi_0    pypi
bitsandbytes              0.39.0                   pypi_0    pypi
bleach                    6.0.0                    pypi_0    pypi
bzip2                     1.0.8                h7b6447c_0    defaults
ca-certificates           2023.01.10           h06a4308_0    defaults
certifi                   2022.12.7                pypi_0    pypi
cffi                      1.15.1                   pypi_0    pypi
charset-normalizer        2.1.1                    pypi_0    pypi
click                     8.1.3                    pypi_0    pypi
cmake                     3.25.0                   pypi_0    pypi
comm                      0.1.3                    pypi_0    pypi
contourpy                 1.0.7                    pypi_0    pypi
cpm-kernels               1.0.11                   pypi_0    pypi
cycler                    0.11.0                   pypi_0    pypi
datasets                  2.10.1                   pypi_0    pypi
debugpy                   1.6.7                    pypi_0    pypi
decorator                 5.1.1                    pypi_0    pypi
deepspeed                 0.9.5                    pypi_0    pypi
defusedxml                0.7.1                    pypi_0    pypi
dill                      0.3.6                    pypi_0    pypi
docker-pycreds            0.4.0                    pypi_0    pypi
et-xmlfile                1.1.0                    pypi_0    pypi
executing                 1.2.0                    pypi_0    pypi
fastapi                   0.95.1                   pypi_0    pypi
fastjsonschema            2.16.3                   pypi_0    pypi
ffmpy                     0.3.0                    pypi_0    pypi
filelock                  3.9.0                    pypi_0    pypi
fonttools                 4.39.4                   pypi_0    pypi
fqdn                      1.5.1                    pypi_0    pypi
frozenlist                1.3.3                    pypi_0    pypi
fsspec                    2023.5.0                 pypi_0    pypi
gitdb                     4.0.10                   pypi_0    pypi
gitpython                 3.1.31                   pypi_0    pypi
gradio                    3.30.0                   pypi_0    pypi
gradio-client             0.2.4                    pypi_0    pypi
h11                       0.14.0                   pypi_0    pypi
hjson                     3.1.0                    pypi_0    pypi
httpcore                  0.17.0                   pypi_0    pypi
httpx                     0.24.0                   pypi_0    pypi
huggingface-hub           0.14.1                   pypi_0    pypi
idna                      3.4                      pypi_0    pypi
ipykernel                 6.23.1                   pypi_0    pypi
ipython                   8.13.2                   pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
ipywidgets                8.0.6                    pypi_0    pypi
isoduration               20.11.0                  pypi_0    pypi
jedi                      0.18.2                   pypi_0    pypi
jieba                     0.42.1                   pypi_0    pypi
jinja2                    3.1.2                    pypi_0    pypi
joblib                    1.2.0                    pypi_0    pypi
jsonpointer               2.3                      pypi_0    pypi
jsonschema                4.17.3                   pypi_0    pypi
jupyter                   1.0.0                    pypi_0    pypi
jupyter-client            8.2.0                    pypi_0    pypi
jupyter-console           6.6.3                    pypi_0    pypi
jupyter-core              5.3.0                    pypi_0    pypi
jupyter-events            0.6.3                    pypi_0    pypi
jupyter-server            2.5.0                    pypi_0    pypi
jupyter-server-terminals  0.4.4                    pypi_0    pypi
jupyterlab-pygments       0.2.2                    pypi_0    pypi
jupyterlab-widgets        3.0.7                    pypi_0    pypi
kiwisolver                1.4.4                    pypi_0    pypi
latex2mathml              3.75.5                   pypi_0    pypi
ld_impl_linux-64          2.38                 h1181459_1    defaults
libffi                    3.4.4                h6a678d5_0    defaults
libgcc-ng                 11.2.0               h1234567_1    defaults
libgomp                   11.2.0               h1234567_1    defaults
libstdcxx-ng              11.2.0               h1234567_1    defaults
libuuid                   1.41.5               h5eee18b_0    defaults
linkify-it-py             2.0.2                    pypi_0    pypi
lit                       15.0.7                   pypi_0    pypi
loralib                   0.1.1                    pypi_0    pypi
markdown                  3.4.3                    pypi_0    pypi
markdown-it-py            2.2.0                    pypi_0    pypi
markdown2                 2.4.8                    pypi_0    pypi
markupsafe                2.1.2                    pypi_0    pypi
matplotlib                3.7.1                    pypi_0    pypi
matplotlib-inline         0.1.6                    pypi_0    pypi
mdit-py-plugins           0.3.3                    pypi_0    pypi
mdtex2html                1.2.0                    pypi_0    pypi
mdurl                     0.1.2                    pypi_0    pypi
mistune                   2.0.5                    pypi_0    pypi
mpmath                    1.2.1                    pypi_0    pypi
multidict                 6.0.4                    pypi_0    pypi
multiprocess              0.70.14                  pypi_0    pypi
nbclassic                 1.0.0                    pypi_0    pypi
nbclient                  0.7.4                    pypi_0    pypi
nbconvert                 7.4.0                    pypi_0    pypi
nbformat                  5.8.0                    pypi_0    pypi
ncurses                   6.4                  h6a678d5_0    defaults
nest-asyncio              1.5.6                    pypi_0    pypi
networkx                  3.0                      pypi_0    pypi
ninja                     1.11.1                   pypi_0    pypi
nltk                      3.8.1                    pypi_0    pypi
notebook                  6.5.4                    pypi_0    pypi
notebook-shim             0.2.3                    pypi_0    pypi
numpy                     1.24.1                   pypi_0    pypi
openpyxl                  3.1.2                    pypi_0    pypi
openssl                   1.1.1t               h7f8727e_0    defaults
orjson                    3.8.12                   pypi_0    pypi
packaging                 23.1                     pypi_0    pypi
pandas                    2.0.1                    pypi_0    pypi
pandocfilters             1.5.0                    pypi_0    pypi
parso                     0.8.3                    pypi_0    pypi
pathtools                 0.1.2                    pypi_0    pypi
peft                      0.3.0                    pypi_0    pypi
pexpect                   4.8.0                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    9.3.0                    pypi_0    pypi
pip                       23.0.1          py310h06a4308_0    defaults
platformdirs              3.5.1                    pypi_0    pypi
prometheus-client         0.16.0                   pypi_0    pypi
prompt-toolkit            3.0.38                   pypi_0    pypi
protobuf                  4.23.0                   pypi_0    pypi
psutil                    5.9.5                    pypi_0    pypi
ptyprocess                0.7.0                    pypi_0    pypi
pure-eval                 0.2.2                    pypi_0    pypi
py-cpuinfo                9.0.0                    pypi_0    pypi
pyarrow                   12.0.1                   pypi_0    pypi
pycparser                 2.21                     pypi_0    pypi
pydantic                  1.10.7                   pypi_0    pypi
pydub                     0.25.1                   pypi_0    pypi
pygments                  2.15.1                   pypi_0    pypi
pyparsing                 3.0.9                    pypi_0    pypi
pyrsistent                0.19.3                   pypi_0    pypi
pysocks                   1.7.1                    pypi_0    pypi
python                    3.10.11              h7a1cb2a_2    defaults
python-dateutil           2.8.2                    pypi_0    pypi
python-json-logger        2.0.7                    pypi_0    pypi
python-multipart          0.0.6                    pypi_0    pypi
pytz                      2023.3                   pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
pyzmq                     25.0.2                   pypi_0    pypi
qtconsole                 5.4.3                    pypi_0    pypi
qtpy                      2.3.1                    pypi_0    pypi
readline                  8.2                  h5eee18b_0    defaults
regex                     2023.5.5                 pypi_0    pypi
requests                  2.28.1                   pypi_0    pypi
responses                 0.18.0                   pypi_0    pypi
rfc3339-validator         0.1.4                    pypi_0    pypi
rfc3986-validator         0.1.1                    pypi_0    pypi
rich                      13.4.2                   pypi_0    pypi
rouge-chinese             1.0.3                    pypi_0    pypi
safetensors               0.3.1                    pypi_0    pypi
scikit-learn              1.2.2                    pypi_0    pypi
scipy                     1.10.1                   pypi_0    pypi
semantic-version          2.10.0                   pypi_0    pypi
send2trash                1.8.2                    pypi_0    pypi
sentencepiece             0.1.99                   pypi_0    pypi
sentry-sdk                1.25.1                   pypi_0    pypi
setproctitle              1.3.2                    pypi_0    pypi
setuptools                67.8.0          py310h06a4308_0    defaults
six                       1.16.0                   pypi_0    pypi
smmap                     5.0.0                    pypi_0    pypi
sniffio                   1.3.0                    pypi_0    pypi
soupsieve                 2.4.1                    pypi_0    pypi
sqlite                    3.41.2               h5eee18b_0    defaults
sse-starlette             1.6.1                    pypi_0    pypi
stack-data                0.6.2                    pypi_0    pypi
starlette                 0.26.1                   pypi_0    pypi
svgwrite                  1.4.3                    pypi_0    pypi
sympy                     1.11.1                   pypi_0    pypi
terminado                 0.17.1                   pypi_0    pypi
threadpoolctl             3.1.0                    pypi_0    pypi
tinycss2                  1.2.1                    pypi_0    pypi
tk                        8.6.12               h1ccaba5_0    defaults
tokenizers                0.13.3                   pypi_0    pypi
toolz                     0.12.0                   pypi_0    pypi
torch                     2.0.1+cu118              pypi_0    pypi
torchaudio                2.0.2+cu118              pypi_0    pypi
torchvision               0.15.2+cu118             pypi_0    pypi
tornado                   6.3.1                    pypi_0    pypi
tqdm                      4.65.0                   pypi_0    pypi
traitlets                 5.9.0                    pypi_0    pypi
transformers              4.30.2                   pypi_0    pypi
triton                    2.0.0                    pypi_0    pypi
typing-extensions         4.4.0                    pypi_0    pypi
tzdata                    2023.3                   pypi_0    pypi
uc-micro-py               1.0.2                    pypi_0    pypi
uri-template              1.2.0                    pypi_0    pypi
urllib3                   1.26.13                  pypi_0    pypi
uvicorn                   0.22.0                   pypi_0    pypi
wandb                     0.15.4                   pypi_0    pypi
wavedrom                  2.0.3.post3              pypi_0    pypi
wcwidth                   0.2.6                    pypi_0    pypi
webcolors                 1.13                     pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
websocket-client          1.5.1                    pypi_0    pypi
websockets                11.0.3                   pypi_0    pypi
wheel                     0.38.4          py310h06a4308_0    defaults
widgetsnbextension        4.0.7                    pypi_0    pypi
xxhash                    3.2.0                    pypi_0    pypi
xz                        5.4.2                h5eee18b_0    defaults
yarl                      1.9.2                    pypi_0    pypi
zlib                      1.2.13               h5eee18b_0    defaults

### Environment

```markdown
- OS:Ubuntu 18.04
- Python:3.9
- Transformers:4.30.2
- PyTorch:2.0.1+cu118
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :True
```

### Anything else?

我查看了下，目标py文件中没有accelerator

**Comment by traveler-vee** [comment]
我也遇到了，我把transformer改成4.29.2可以

**Comment by duzx16** [comment]
Please pull the repo to use the latest code.
