### ISSUE TITLE
C-eval的评估代码可以开源一下吗

### ISSUE THREAD

**Issue by zhangfan-algo** [THUDM/ChatGLM2-6B#234]
### Solutions

自己微调了一版模型.想看下微调后对通用能力是不是影响

**Comment by duzx16** [comment]
已经开源了 https://github.com/THUDM/ChatGLM2-6B/tree/main/evaluation

**Comment by 15904550933** [comment]
@duzx16 您好，请问一下这个代码使用测试集测试的结果保存在哪里？

**Comment by 15904550933** [comment]
@duzx16 您好，请问一下这个代码使用测试集测试的题目答案保存在哪里？
