### ISSUE TITLE
[BUG/Help] <title> Tokenizer class ChatGLMTokenizer does not exist or is not currently imported.

### ISSUE THREAD

**Issue by Astrallee** [THUDM/ChatGLM2-6B#243]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

我离线下载了huggingface上发布的模型   ，网址：https://huggingface.co/THUDM/chatglm2-6b/tree/main

在运行web_demo.py文件时将
#tokenizer = AutoTokenizer.from_pretrained('THUDM/chatglm2-6b' , trust_remote_code=True)
#model = AutoModel.from_pretrained('THUDM/chatglm2-6b' , trust_remote_code=True).cuda()
改为了
tokenizer = AutoTokenizer.from_pretrained('E:\workspace\ChatGLM2\chatglm2-6b')
model = AutoModel.from_pretrained('E:\workspace\ChatGLM2\chatglm2-6b').cuda()

在运行时得到了
Traceback (most recent call last):
  File "E:\workspace\ChatGLM2\web_demo.py", line 10, in <module>
    tokenizer = AutoTokenizer.from_pretrained('E:\workspace\ChatGLM2\chatglm2-6b')
  File "D:\anaconda\envs\glm2\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 688, in from_pretrained
    raise ValueError(
ValueError: Tokenizer class ChatGLMTokenizer does not exist or is not currently imported.

### Steps To Reproduce

1.离线下载了huggingface上发布的模型   ，网址：https://huggingface.co/THUDM/chatglm2-6b/tree/main

2.在运行web_demo.py文件时将
tokenizer = AutoTokenizer.from_pretrained('THUDM/chatglm2-6b' , trust_remote_code=True)
model = AutoModel.from_pretrained('THUDM/chatglm2-6b' , trust_remote_code=True).cuda()
改为了自己的路径
tokenizer = AutoTokenizer.from_pretrained('E:\workspace\ChatGLM2\chatglm2-6b')
model = AutoModel.from_pretrained('E:\workspace\ChatGLM2\chatglm2-6b').cuda()

在运行时得到了
Traceback (most recent call last):
  File "E:\workspace\ChatGLM2\web_demo.py", line 10, in <module>
    tokenizer = AutoTokenizer.from_pretrained('E:\workspace\ChatGLM2\chatglm2-6b')
  File "D:\anaconda\envs\glm2\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 688, in from_pretrained
    raise ValueError(
ValueError: Tokenizer class ChatGLMTokenizer does not exist or is not currently imported.

### Environment

```markdown
- OS:win10
- Python:3.10.6
- Transformers:4.30.2
- PyTorch:2.0.1
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :11.8
```

**Comment by duzx16** [comment]
初始化的时候必须有 `trust_remote_code=True` 参数
