### ISSUE TITLE
使用ptuning微调时报错

### ISSUE THREAD

**Issue by guiniao** [THUDM/ChatGLM2-6B#244]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

使用ptuning微调时报错，AttributeError：'Seq2SeqTrainer' object has no attribute 'is_deepspeed_enabled'

### Steps To Reproduce

无

### Environment

```markdown
- OS:centos7
- Python:3.8
- Transformers:4.30.2
- PyTorch:2.0.1
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :11.8
```

**Comment by wangwang194** [comment]
Transformers版本降下来

**Comment by duzx16** [comment]
请使用本仓库最新的代码
