### ISSUE TITLE
加载模型chatglm2-6b-int4 出错

### ISSUE THREAD

**Issue by shuifuture** [THUDM/ChatGLM2-6B#246]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

在运行cli_demo.py 文件时出现错误 

tokenizer = AutoTokenizer.from_pretrained("model/chatglm2-6b-int4", trust_remote_code=True)
model = AutoModel.from_pretrained("model/chatglm2-6b-int4", trust_remote_code=True).float()

Traceback (most recent call last):
  File "/home/censoft/ysc/code/ChatGLM2-6B/cli_demo.py", line 8, in <module>
    model = AutoModel.from_pretrained("model/chatglm2-6b-int4", trust_remote_code=True).float()
  File "/home/censoft/anaconda3/envs/yolo/lib/python3.7/site-packages/transformers/models/auto/auto_factory.py", line 480, in from_pretrained
    pretrained_model_name_or_path, *model_args, config=config, **hub_kwargs, **kwargs
  File "/home/censoft/anaconda3/envs/yolo/lib/python3.7/site-packages/transformers/modeling_utils.py", line 2896, in from_pretrained
    keep_in_fp32_modules=keep_in_fp32_modules,
  File "/home/censoft/anaconda3/envs/yolo/lib/python3.7/site-packages/transformers/modeling_utils.py", line 3278, in _load_pretrained_model
    raise RuntimeError(f"Error(s) in loading state_dict for {model.__class__.__name__}:\n\t{error_msg}")
RuntimeError: Error(s) in loading state_dict for ChatGLMForConditionalGeneration:
	size mismatch for transformer.encoder.layers.0.self_attention.query_key_value.weight: copying a param with shape torch.Size([4608, 2048]) from checkpoint, the shape in current model is torch.Size([4608, 4096]).
	size mismatch for transformer.encoder.layers.0.self_attention.dense.weight: copying a param with shape torch.Size([4096, 2048]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
	size mismatch for transformer.encoder.layers.0.mlp.dense_h_to_4h.weight: copying a param with shape torch.Size([27392, 2048]) from checkpoint, the shape in current model is torch.Size([27392, 4096]).
	size mismatch for transformer.encoder.layers.0.mlp.dense_4h_to_h.weight: copying a param with shape torch.Size([4096, 6848]) from checkpoint, the shape in current model is torch.Size([4096, 13696]).
	size mismatch for transformer.encoder.layers.1.self_attention.query_key_value.weight: copying a param with shape torch.Size([4608, 2048]) from checkpoint, the shape in current model is torch.Size([4608, 4096]).
	size mismatch for transformer.encoder.layers.1.self_attention.dense.weight: copying a param with shape torch.Size([4096, 2048]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
	size mismatch for transformer.encoder.layers.1.mlp.dense_h_to_4h.weight: copying a param with shape torch.Size([27392, 2048]) from checkpoint, the shape in current model is torch.Size([27392, 4096]).
	size mismatch for transformer.encoder.layers.1.mlp.dense_4h_to_h.weight: copying a param with shape torch.Size([4096, 6848]) from checkpoint, the shape in current model is torch.Size([4096, 13696]).
	size mismatch for transformer.encoder.layers.2.self_attention.query_key_value.weight: copying a param with shape torch.Size([4608, 2048]) from checkpoint, the shape in current model is torch.Size([4608, 4096]).
	size mismatch for transformer.encoder.layers.2.self_attention.dense.weight: copying a param with shape torch.Size([4096, 2048]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
	size mismatch for transformer.encoder.layers.2.mlp.dense_h_to_4h.weight: copying a param with shape torch.Size([27392, 2048]) from checkpoint, the shape in current model is torch.Size([27392, 4096]).
	size mismatch for transformer.encoder.layers.2.mlp.dense_4h_to_h.weight: copying a param with shape torch.Size([4096, 6848]) from checkpoint, the shape in current model is torch.Size([4096, 13696]).
	size mismatch for transformer.encoder.layers.3.self_attention.query_key_value.weight: copying a param with shape torch.Size([4608, 2048]) from checkpoint, the shape in current model is torch.Size([4608, 4096]).
	size mismatch for transformer.encoder.layers.3.self_attention.dense.weight: copying a param with shape torch.Size([4096, 2048]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
	size mismatch for transformer.encoder.layers.3.mlp.dense_h_to_4h.weight: copying a param with shape torch.Size([27392, 2048]) from checkpoint, the shape in current model is torch.Size([27392, 4096]).
	size mismatch for transformer.encoder.layers.3.mlp.dense_4h_to_h.weight: copying a param with shape torch.Size([4096, 6848]) from checkpoint, the shape in current model is torch.Size([4096, 13696]).
	size mismatch for transformer.encoder.layers.4.self_attention.query_key_value.weight: copying a param with shape torch.Size([4608, 2048]) from checkpoint, the shape in current model is torch.Size([4608, 4096]).
	size mismatch for transformer.encoder.layers.4.self_attention.dense.weight: copying a param with shape torch.Size([4096, 2048]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
	size mismatch for transformer.encoder.layers.4.mlp.dense_h_to_4h.weight: copying a param with shape torch.Size([27392, 2048]) from checkpoint, the shape in current model is torch.Size([27392, 4096]).
	size mismatch for transformer.encoder.layers.4.mlp.dense_4h_to_h.weight: copying a param with shape torch.Size([4096, 6848]) from checkpoint, the shape in current model is torch.Size([4096, 13696]).
	size mismatch for transformer.encoder.layers.5.self_attention.query_key_value.weight: copying a param with shape torch.Size([4608, 2048]) from checkpoint, the shape in current model is torch.Size([4608, 4096]).
	size mismatch for transformer.encoder.layers.5.self_attention.dense.weight: copying a param with shape torch.Size([4096, 2048]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
	size mismatch for transformer.encoder.layers.5.mlp.dense_h_to_4h.weight: copying a param with shape torch.Size([27392, 2048]) from checkpoint, the shape in current model is torch.Size([27392, 4096]).
	size mismatch for transformer.encoder.layers.5.mlp.dense_4h_to_h.weight: copying a param with shape torch.Size([4096, 6848]) from checkpoint, the shape in current model is torch.Size([4096, 13696]).
	size mismatch for transformer.encoder.layers.6.self_attention.query_key_value.weight: copying a param with shape torch.Size([4608, 2048]) from checkpoint, the shape in current model is torch.Size([4608, 4096]).
	size mismatch for transformer.encoder.layers.6.self_attention.dense.weight: copying a param with shape torch.Size([4096, 2048]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
	size mismatch for transformer.encoder.layers.6.mlp.dense_h_to_4h.weight: copying a param with shape torch.Size([27392, 2048]) from checkpoint, the shape in current model is torch.Size([27392, 4096]).
	size mismatch for transformer.encoder.layers.6.mlp.dense_4h_to_h.weight: copying a param with shape torch.Size([4096, 6848]) from checkpoint, the shape in current model is torch.Size([4096, 13696]).
	size mismatch for transformer.encoder.layers.7.self_attention.query_key_value.weight: copying a param with shape torch.Size([4608, 2048]) from checkpoint, the shape in current model is torch.Size([4608, 4096]).
	size mismatch for transformer.encoder.layers.7.self_attention.dense.weight: copying a param with shape torch.Size([4096, 2048]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
	size mismatch for transformer.encoder.layers.7.mlp.dense_h_to_4h.weight: copying a param with shape torch.Size([27392, 2048]) from checkpoint, the shape in current model is torch.Size([27392, 4096]).
	size mismatch for transformer.encoder.layers.7.mlp.dense_4h_to_h.weight: copying a param with shape torch.Size([4096, 6848]) from checkpoint, the shape in current model is torch.Size([4096, 13696]).
	size mismatch for transformer.encoder.layers.8.self_attention.query_key_value.weight: copying a param with shape torch.Size([4608, 2048]) from checkpoint, the shape in current model is torch.Size([4608, 4096]).
	size mismatch for transformer.encoder.layers.8.self_attention.dense.weight: copying a param with shape torch.Size([4096, 2048]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
	size mismatch for transformer.encoder.layers.8.mlp.dense_h_to_4h.weight: copying a param with shape torch.Size([27392, 2048]) from checkpoint, the shape in current model is torch.Size([27392, 4096]).
	size mismatch for transformer.encoder.layers.8.mlp.dense_4h_to_h.weight: copying a param with shape torch.Size([4096, 6848]) from checkpoint, the shape in current model is torch.Size([4096, 13696]).
	size mismatch for transformer.encoder.layers.9.self_attention.query_key_value.weight: copying a param with shape torch.Size([4608, 2048]) from checkpoint, the shape in current model is torch.Size([4608, 4096]).
	size mismatch for transformer.encoder.layers.9.self_attention.dense.weight: copying a param with shape torch.Size([4096, 2048]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
	size mismatch for transformer.encoder.layers.9.mlp.dense_h_to_4h.weight: copying a param with shape torch.Size([27392, 2048]) from checkpoint, the shape in current model is torch.Size([27392, 4096]).
	size mismatch for transformer.encoder.layers.9.mlp.dense_4h_to_h.weight: copying a param with shape torch.Size([4096, 6848]) from checkpoint, the shape in current model is torch.Size([4096, 13696]).
	size mismatch for transformer.encoder.layers.10.self_attention.query_key_value.weight: copying a param with shape torch.Size([4608, 2048]) from checkpoint, the shape in current model is torch.Size([4608, 4096]).
	size mismatch for transformer.encoder.layers.10.self_attention.dense.weight: copying a param with shape torch.Size([4096, 2048]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
	size mismatch for transformer.encoder.layers.10.mlp.dense_h_to_4h.weight: copying a param with shape torch.Size([27392, 2048]) from checkpoint, the shape in current model is torch.Size([27392, 4096]).
	size mismatch for transformer.encoder.layers.10.mlp.dense_4h_to_h.weight: copying a param with shape torch.Size([4096, 6848]) from checkpoint, the shape in current model is torch.Size([4096, 13696]).
	size mismatch for transformer.encoder.layers.11.self_attention.query_key_value.weight: copying a param with shape torch.Size([4608, 2048]) from checkpoint, the shape in current model is torch.Size([4608, 4096]).
	size mismatch for transformer.encoder.layers.11.self_attention.dense.weight: copying a param with shape torch.Size([4096, 2048]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
	size mismatch for transformer.encoder.layers.11.mlp.dense_h_to_4h.weight: copying a param with shape torch.Size([27392, 2048]) from checkpoint, the shape in current model is torch.Size([27392, 4096]).
	size mismatch for transformer.encoder.layers.11.mlp.dense_4h_to_h.weight: copying a param with shape torch.Size([4096, 6848]) from checkpoint, the shape in current model is torch.Size([4096, 13696]).
	size mismatch for transformer.encoder.layers.12.self_attention.query_key_value.weight: copying a param with shape torch.Size([4608, 2048]) from checkpoint, the shape in current model is torch.Size([4608, 4096]).
	size mismatch for transformer.encoder.layers.12.self_attention.dense.weight: copying a param with shape torch.Size([4096, 2048]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
	size mismatch for transformer.encoder.layers.12.mlp.dense_h_to_4h.weight: copying a param with shape torch.Size([27392, 2048]) from checkpoint, the shape in current model is torch.Size([27392, 4096]).
	size mismatch for transformer.encoder.layers.12.mlp.dense_4h_to_h.weight: copying a param with shape torch.Size([4096, 6848]) from checkpoint, the shape in current model is torch.Size([4096, 13696]).
	size mismatch for transformer.encoder.layers.13.self_attention.query_key_value.weight: copying a param with shape torch.Size([4608, 2048]) from checkpoint, the shape in current model is torch.Size([4608, 4096]).
	size mismatch for transformer.encoder.layers.13.self_attention.dense.weight: copying a param with shape torch.Size([4096, 2048]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
	size mismatch for transformer.encoder.layers.13.mlp.dense_h_to_4h.weight: copying a param with shape torch.Size([27392, 2048]) from checkpoint, the shape in current model is torch.Size([27392, 4096]).
	size mismatch for transformer.encoder.layers.13.mlp.dense_4h_to_h.weight: copying a param with shape torch.Size([4096, 6848]) from checkpoint, the shape in current model is torch.Size([4096, 13696]).
	size mismatch for transformer.encoder.layers.14.self_attention.query_key_value.weight: copying a param with shape torch.Size([4608, 2048]) from checkpoint, the shape in current model is torch.Size([4608, 4096]).
	size mismatch for transformer.encoder.layers.14.self_attention.dense.weight: copying a param with shape torch.Size([4096, 2048]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
	size mismatch for transformer.encoder.layers.14.mlp.dense_h_to_4h.weight: copying a param with shape torch.Size([27392, 2048]) from checkpoint, the shape in current model is torch.Size([27392, 4096]).
	size mismatch for transformer.encoder.layers.14.mlp.dense_4h_to_h.weight: copying a param with shape torch.Size([4096, 6848]) from checkpoint, the shape in current model is torch.Size([4096, 13696]).
	size mismatch for transformer.encoder.layers.15.self_attention.query_key_value.weight: copying a param with shape torch.Size([4608, 2048]) from checkpoint, the shape in current model is torch.Size([4608, 4096]).
	size mismatch for transformer.encoder.layers.15.self_attention.dense.weight: copying a param with shape torch.Size([4096, 2048]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
	size mismatch for transformer.encoder.layers.15.mlp.dense_h_to_4h.weight: copying a param with shape torch.Size([27392, 2048]) from checkpoint, the shape in current model is torch.Size([27392, 4096]).
	size mismatch for transformer.encoder.layers.15.mlp.dense_4h_to_h.weight: copying a param with shape torch.Size([4096, 6848]) from checkpoint, the shape in current model is torch.Size([4096, 13696]).
	size mismatch for transformer.encoder.layers.16.self_attention.query_key_value.weight: copying a param with shape torch.Size([4608, 2048]) from checkpoint, the shape in current model is torch.Size([4608, 4096]).
	size mismatch for transformer.encoder.layers.16.self_attention.dense.weight: copying a param with shape torch.Size([4096, 2048]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
	size mismatch for transformer.encoder.layers.16.mlp.dense_h_to_4h.weight: copying a param with shape torch.Size([27392, 2048]) from checkpoint, the shape in current model is torch.Size([27392, 4096]).
	size mismatch for transformer.encoder.layers.16.mlp.dense_4h_to_h.weight: copying a param with shape torch.Size([4096, 6848]) from checkpoint, the shape in current model is torch.Size([4096, 13696]).
	size mismatch for transformer.encoder.layers.17.self_attention.query_key_value.weight: copying a param with shape torch.Size([4608, 2048]) from checkpoint, the shape in current model is torch.Size([4608, 4096]).
	size mismatch for transformer.encoder.layers.17.self_attention.dense.weight: copying a param with shape torch.Size([4096, 2048]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
	size mismatch for transformer.encoder.layers.17.mlp.dense_h_to_4h.weight: copying a param with shape torch.Size([27392, 2048]) from checkpoint, the shape in current model is torch.Size([27392, 4096]).
	size mismatch for transformer.encoder.layers.17.mlp.dense_4h_to_h.weight: copying a param with shape torch.Size([4096, 6848]) from checkpoint, the shape in current model is torch.Size([4096, 13696]).
	size mismatch for transformer.encoder.layers.18.self_attention.query_key_value.weight: copying a param with shape torch.Size([4608, 2048]) from checkpoint, the shape in current model is torch.Size([4608, 4096]).
	size mismatch for transformer.encoder.layers.18.self_attention.dense.weight: copying a param with shape torch.Size([4096, 2048]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
	size mismatch for transformer.encoder.layers.18.mlp.dense_h_to_4h.weight: copying a param with shape torch.Size([27392, 2048]) from checkpoint, the shape in current model is torch.Size([27392, 4096]).
	size mismatch for transformer.encoder.layers.18.mlp.dense_4h_to_h.weight: copying a param with shape torch.Size([4096, 6848]) from checkpoint, the shape in current model is torch.Size([4096, 13696]).
	size mismatch for transformer.encoder.layers.19.self_attention.query_key_value.weight: copying a param with shape torch.Size([4608, 2048]) from checkpoint, the shape in current model is torch.Size([4608, 4096]).
	size mismatch for transformer.encoder.layers.19.self_attention.dense.weight: copying a param with shape torch.Size([4096, 2048]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
	size mismatch for transformer.encoder.layers.19.mlp.dense_h_to_4h.weight: copying a param with shape torch.Size([27392, 2048]) from checkpoint, the shape in current model is torch.Size([27392, 4096]).
	size mismatch for transformer.encoder.layers.19.mlp.dense_4h_to_h.weight: copying a param with shape torch.Size([4096, 6848]) from checkpoint, the shape in current model is torch.Size([4096, 13696]).
	size mismatch for transformer.encoder.layers.20.self_attention.query_key_value.weight: copying a param with shape torch.Size([4608, 2048]) from checkpoint, the shape in current model is torch.Size([4608, 4096]).
	size mismatch for transformer.encoder.layers.20.self_attention.dense.weight: copying a param with shape torch.Size([4096, 2048]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
	size mismatch for transformer.encoder.layers.20.mlp.dense_h_to_4h.weight: copying a param with shape torch.Size([27392, 2048]) from checkpoint, the shape in current model is torch.Size([27392, 4096]).
	size mismatch for transformer.encoder.layers.20.mlp.dense_4h_to_h.weight: copying a param with shape torch.Size([4096, 6848]) from checkpoint, the shape in current model is torch.Size([4096, 13696]).
	size mismatch for transformer.encoder.layers.21.self_attention.query_key_value.weight: copying a param with shape torch.Size([4608, 2048]) from checkpoint, the shape in current model is torch.Size([4608, 4096]).
	size mismatch for transformer.encoder.layers.21.self_attention.dense.weight: copying a param with shape torch.Size([4096, 2048]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
	size mismatch for transformer.encoder.layers.21.mlp.dense_h_to_4h.weight: copying a param with shape torch.Size([27392, 2048]) from checkpoint, the shape in current model is torch.Size([27392, 4096]).
	size mismatch for transformer.encoder.layers.21.mlp.dense_4h_to_h.weight: copying a param with shape torch.Size([4096, 6848]) from checkpoint, the shape in current model is torch.Size([4096, 13696]).
	size mismatch for transformer.encoder.layers.22.self_attention.query_key_value.weight: copying a param with shape torch.Size([4608, 2048]) from checkpoint, the shape in current model is torch.Size([4608, 4096]).
	size mismatch for transformer.encoder.layers.22.self_attention.dense.weight: copying a param with shape torch.Size([4096, 2048]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
	size mismatch for transformer.encoder.layers.22.mlp.dense_h_to_4h.weight: copying a param with shape torch.Size([27392, 2048]) from checkpoint, the shape in current model is torch.Size([27392, 4096]).
	size mismatch for transformer.encoder.layers.22.mlp.dense_4h_to_h.weight: copying a param with shape torch.Size([4096, 6848]) from checkpoint, the shape in current model is torch.Size([4096, 13696]).
	size mismatch for transformer.encoder.layers.23.self_attention.query_key_value.weight: copying a param with shape torch.Size([4608, 2048]) from checkpoint, the shape in current model is torch.Size([4608, 4096]).
	size mismatch for transformer.encoder.layers.23.self_attention.dense.weight: copying a param with shape torch.Size([4096, 2048]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
	size mismatch for transformer.encoder.layers.23.mlp.dense_h_to_4h.weight: copying a param with shape torch.Size([27392, 2048]) from checkpoint, the shape in current model is torch.Size([27392, 4096]).
	size mismatch for transformer.encoder.layers.23.mlp.dense_4h_to_h.weight: copying a param with shape torch.Size([4096, 6848]) from checkpoint, the shape in current model is torch.Size([4096, 13696]).
	size mismatch for transformer.encoder.layers.24.self_attention.query_key_value.weight: copying a param with shape torch.Size([4608, 2048]) from checkpoint, the shape in current model is torch.Size([4608, 4096]).
	size mismatch for transformer.encoder.layers.24.self_attention.dense.weight: copying a param with shape torch.Size([4096, 2048]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
	size mismatch for transformer.encoder.layers.24.mlp.dense_h_to_4h.weight: copying a param with shape torch.Size([27392, 2048]) from checkpoint, the shape in current model is torch.Size([27392, 4096]).
	size mismatch for transformer.encoder.layers.24.mlp.dense_4h_to_h.weight: copying a param with shape torch.Size([4096, 6848]) from checkpoint, the shape in current model is torch.Size([4096, 13696]).
	size mismatch for transformer.encoder.layers.25.self_attention.query_key_value.weight: copying a param with shape torch.Size([4608, 2048]) from checkpoint, the shape in current model is torch.Size([4608, 4096]).
	size mismatch for transformer.encoder.layers.25.self_attention.dense.weight: copying a param with shape torch.Size([4096, 2048]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
	size mismatch for transformer.encoder.layers.25.mlp.dense_h_to_4h.weight: copying a param with shape torch.Size([27392, 2048]) from checkpoint, the shape in current model is torch.Size([27392, 4096]).
	size mismatch for transformer.encoder.layers.25.mlp.dense_4h_to_h.weight: copying a param with shape torch.Size([4096, 6848]) from checkpoint, the shape in current model is torch.Size([4096, 13696]).
	size mismatch for transformer.encoder.layers.26.self_attention.query_key_value.weight: copying a param with shape torch.Size([4608, 2048]) from checkpoint, the shape in current model is torch.Size([4608, 4096]).
	size mismatch for transformer.encoder.layers.26.self_attention.dense.weight: copying a param with shape torch.Size([4096, 2048]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
	size mismatch for transformer.encoder.layers.26.mlp.dense_h_to_4h.weight: copying a param with shape torch.Size([27392, 2048]) from checkpoint, the shape in current model is torch.Size([27392, 4096]).
	size mismatch for transformer.encoder.layers.26.mlp.dense_4h_to_h.weight: copying a param with shape torch.Size([4096, 6848]) from checkpoint, the shape in current model is torch.Size([4096, 13696]).
	size mismatch for transformer.encoder.layers.27.self_attention.query_key_value.weight: copying a param with shape torch.Size([4608, 2048]) from checkpoint, the shape in current model is torch.Size([4608, 4096]).
	size mismatch for transformer.encoder.layers.27.self_attention.dense.weight: copying a param with shape torch.Size([4096, 2048]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
	size mismatch for transformer.encoder.layers.27.mlp.dense_h_to_4h.weight: copying a param with shape torch.Size([27392, 2048]) from checkpoint, the shape in current model is torch.Size([27392, 4096]).
	size mismatch for transformer.encoder.layers.27.mlp.dense_4h_to_h.weight: copying a param with shape torch.Size([4096, 6848]) from checkpoint, the shape in current model is torch.Size([4096, 13696]).
	You may consider adding `ignore_mismatched_sizes=True` in the model `from_pretrained` method.

### Steps To Reproduce

使用python 3.7  torch =1.12   cuda =11.4

### Environment

```markdown
- OS:ubuntu
- Python:307
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by duzx16** [comment]
请确保 `model/chatglm2-6b-int4` 下面的文件都是从 https://huggingface.co/THUDM/chatglm2-6b-int4 下载的

**Comment by mmdzzh** [comment]
> 请确保 `model/chatglm2-6b-int4` 下面的文件都是从 https://huggingface.co/THUDM/chatglm2-6b-int4 下载的

我也遇上了这个问题，从清华云盘下载的模型和model，https://cloud.tsinghua.edu.cn/d/674208019e314311ab5c/?p=%2Fchatglm2-6b-int4&mode=list，然后把web_demo.py里路径改为权重和model路径tokenizer = AutoTokenizer.from_pretrained("D:\chatglm\hugging_face_glm\chatglm2-6b", trust_remote_code=True)
model = AutoModel.from_pretrained("D:\chatglm\hugging_face_glm\chatglm2-6b", trust_remote_code=True).cuda()

**Comment by well-zt** [comment]
我也遇到了一样的问题，求解答

**Comment by mmdzzh** [comment]
我没有解决



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月24日(周日) 下午2:35
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [THUDM/ChatGLM2-6B] 加载模型chatglm2-6b-int4 出错 (Issue #246)




 
我也遇到了一样的问题，求解答

**Comment by chenguangming** [comment]
chatglm2-6b和chatglm2-6b-int4下面的文件不能混用
