### ISSUE TITLE
[Help] ptuning出现‘ChatGLMModel’ object has no attribute 'prefix_encoder'"

### ISSUE THREAD

**Issue by IenTan2023** [THUDM/ChatGLM2-6B#255]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

把模型下载到本地路径，然后执行train.sh. 
    if model_args.pre_seq_len is not None:
        # P-tuning v2
        model = model.half()
  -->model.transformer.prefix_encoder.float()
执行到这个位置的时候出现提示："‘ChatGLMModel’ object has no attribute 'prefix_encoder'", 然后跳出。
我通过dir(model.transformer)检查发现确实没有prefix_encoder。这是什么情况？

备注：本地路径的模型在cli_demo.py和web_demo.py中正常运行

### Steps To Reproduce

在train.sh中模型路径为本地路径，然后运行train.sh

### Environment

```markdown
-Debian11
-python3.9
-requirement.txt里的所有安装和依赖。
```

**Comment by duzx16** [comment]
更新一下本地的模型实现

**Comment by xxcoco763** [comment]
请问解决了吗？同样出现了该问题

**Comment by pingyuan2016** [comment]
https://huggingface.co/THUDM/chatglm2-6b/tree/main

用一下最新的配置文件，替换一下解决
![image](https://github.com/THUDM/ChatGLM2-6B/assets/25808622/1a4d60ef-3307-4e66-aa62-a38869bcfdec)
