### ISSUE TITLE
[BUG/Help] web_demo.py 服务器端口问题

### ISSUE THREAD

**Issue by xieeryihe** [THUDM/ChatGLM2-6B#257]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

我在使用VSCode的ssh插件来访问我的服务器，上面运行了web demo的gradio版本。
调用的代码为：demo.queue().launch(share=False, inbrowser=True)
现在假设我的服务器ip为1.1.1.1

- 此时没有设置server_name，默认为127.0.0.1；没有设置server_port，默认为7860。我可以通过127.0.0.1:7860，1.1.1.1:80正确访问web demo，但是通过1.1.1.1:7860 却访问不到。
- 当我手动设置server_name为1.1.1.1时，在本机上可以通过1.1.1.1:7860访问，但是1.1.1.1:80又访问不了了。

请问这是为什么？

### Steps To Reproduce

None

### Environment

```markdown
- OS:Ubuntu 22.04
- Python:3.9
- Transformers:4.29
- PyTorch:2.0.1
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :True
```

**Comment by Selenium39** [comment]
@xieeryihe 我也遇到了这个问题，你是怎么解决的？
