### ISSUE TITLE
[BUG/Help] 介绍上说支持 cpu，其实不支持

### ISSUE THREAD

**Issue by lidanger** [THUDM/ChatGLM2-6B#26]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

介绍上说支持 cpu，其实不支持，连相关文件都没得了
复制 1 中的相关文件过去，还是不行。
发现 quantization.py 中根本没有 cpu 相关内容
quantization.py 替换成老的，运行提示：

AttributeError: 'GLMTransformer' object has no attribute 'device'

### Expected Behavior

支持纯 cpu 运行

### Steps To Reproduce

web_demo.py 中修改为
model = AutoModel.from_pretrained("THUDM/chatglm2-6b-int4", trust_remote_code=True).float()
然后运行
python .\web_demo.py

### Environment

```markdown
- OS: Windows 11
- Python: 3.10.0
- Transformers: 4.27.1
- PyTorch: 2.0.0
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) : False
```

**Comment by gazerhuang** [comment]
我本地加载模型是能跑起来的，我记得1之前也有这个问题，CPU跑需要本地模型，你试试看

**Comment by duzx16** [comment]
已增加 CPU 上运行量化模型的支持。

**Comment by Alan-JW** [comment]
使用cpu运行会报这个错误，RuntimeError: "arange_cpu" not implemented for 'Half'，请问是什么原因呀？ @duzx16 @lidanger

**Comment by angrad** [comment]
报错：`RuntimeError: "arange_cpu" not implemented for 'Half'`
解决方式之一：如果是想在cpu跑的话，改成
`model = AutoModel.from_pretrained("THUDM/chatglm2-6b", trust_remote_code=True, device="cpu").float()#.cuda()`
环境：
`
transformers                  4.27.1
`
`
torch                         1.10.0
`
