### ISSUE TITLE
[BUG/Help] <模仿demo中的adgen进行ptuning之后，无法加载>

### ISSUE THREAD

**Issue by bxjxxyy** [THUDM/ChatGLM2-6B#260]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [01:47<00:00, 15.41s/it]
2023-07-10 09:34:56.460 Uncaught app exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/streamlit/runtime/caching/cache_utils.py", line 263, in _get_or_create_cached_value
    cached_result = cache.read_result(value_key)
  File "/usr/local/lib/python3.8/dist-packages/streamlit/runtime/caching/cache_resource_api.py", line 500, in read_result
    raise CacheKeyNotFoundError()
streamlit.runtime.caching.cache_errors.CacheKeyNotFoundError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/streamlit/runtime/caching/cache_utils.py", line 311, in _handle_cache_miss
    cached_result = cache.read_result(value_key)
  File "/usr/local/lib/python3.8/dist-packages/streamlit/runtime/caching/cache_resource_api.py", line 500, in read_result
    raise CacheKeyNotFoundError()
streamlit.runtime.caching.cache_errors.CacheKeyNotFoundError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/streamlit/runtime/scriptrunner/script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
  File "/root/ChatGLM2-6B/web_demo2.py", line 82, in <module>
    st.session_state["state"] = predict(prompt_text, max_length, top_p, temperature, st.session_state["state"])
  File "/root/ChatGLM2-6B/web_demo2.py", line 36, in predict
    tokenizer, model = get_model()
  File "/usr/local/lib/python3.8/dist-packages/streamlit/runtime/caching/cache_utils.py", line 211, in wrapper
    return cached_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/streamlit/runtime/caching/cache_utils.py", line 240, in __call__
    return self._get_or_create_cached_value(args, kwargs)
  File "/usr/local/lib/python3.8/dist-packages/streamlit/runtime/caching/cache_utils.py", line 266, in _get_or_create_cached_value
    return self._handle_cache_miss(cache, value_key, func_args, func_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/streamlit/runtime/caching/cache_utils.py", line 320, in _handle_cache_miss
    computed_value = self._info.func(*func_args, **func_kwargs)
  File "/root/ChatGLM2-6B/web_demo2.py", line 23, in get_model
    model.transformer.prefix_encoder.load_state_dict(new_prefix_state_dict)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'ChatGLMModel' object has no attribute 'prefix_encoder'`

### Steps To Reproduce

窝弄了个自己的数据集，{"content": "xxxx", "summary": "xxxx"}格式的，放在了AdvertiseGen目录下，文件名为train.json。由于没有验证数据集，所以我用train.json代替了dev.json。修改后的train.sh和evaluate.sh文件如下：
train.sh
`PRE_SEQ_LEN=128
LR=2e-2
NUM_GPUS=1

torchrun --standalone --nnodes=1 --nproc-per-node=$NUM_GPUS main.py \
    --do_train \
    --train_file AdvertiseGen/train.json \
    --validation_file AdvertiseGen/train.json \
    --preprocessing_num_workers 10 \
    --prompt_column content \
    --response_column summary \
    --overwrite_cache \
    --model_name_or_path THUDM/chatglm2-6b \
    --output_dir output/adgen-chatglm2-6b-pt-$PRE_SEQ_LEN-$LR \
    --overwrite_output_dir \
    --max_source_length 64 \
    --max_target_length 128 \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 1 \
    --gradient_accumulation_steps 16 \
    --predict_with_generate \
    --max_steps 1000 \
    --logging_steps 10 \
    --save_steps 100 \
    --learning_rate $LR \
    --pre_seq_len $PRE_SEQ_LEN \
    --quantization_bit 4
`
evaluate.sh
`PRE_SEQ_LEN=128
CHECKPOINT=adgen-chatglm2-6b-pt-128-2e-2
STEP=3000
NUM_GPUS=1

torchrun --standalone --nnodes=1 --nproc-per-node=$NUM_GPUS main.py \
    --do_predict \
    --validation_file AdvertiseGen/train.json \
    --test_file AdvertiseGen/train.json \
    --overwrite_cache \
    --prompt_column content \
    --response_column summary \
    --model_name_or_path THUDM/chatglm2-6b \
    --ptuning_checkpoint ./output/$CHECKPOINT/checkpoint-$STEP \
    --output_dir ./output/$CHECKPOINT \
    --overwrite_output_dir \
    --max_source_length 64 \
    --max_target_length 64 \
    --per_device_eval_batch_size 1 \
    --predict_with_generate \
    --pre_seq_len $PRE_SEQ_LEN \
    --quantization_bit 4`
训练后，根据文档修改了web_demo2.py的get_model()部分
![image](https://github.com/THUDM/ChatGLM2-6B/assets/26214176/ce53f0fd-a0f7-42cb-94e7-edaad2b80162)

### Environment

```markdown
- OS:Ubuntu 20.04
- Python:3.8
pip install -r requirements.txt
```

### Anything else?

我是什么地方出错了？

**Comment by onetwo12cn** [comment]
同问，请问解决了吗

**Comment by bxjxxyy** [comment]
> 同问，请问解决了吗

还没

**Comment by mxzgn** [comment]
去[h](https://huggingface.co/THUDM/chatglm2-6b/tree/main)更新最新的*.py,*.json,*.model文件

**Comment by YXShan** [comment]
你这边在加载模型的时候没有设置config中的pre_seq_len参数，默认是None，此时构造出来的模型没有prefix_encoder模块，因此你下面加载你训练参数的时候会显示没有此模块。
你应该要设置config中的pre_seq_len与你训练时候的一致，再进行模型的加载，此时config要作为加载模型的参数之一。

**Comment by bxjxxyy** [comment]
> 同问，请问解决了吗

https://blog.csdn.net/Together_CZ/article/details/131340838
我按照这个倒是解决了。只有一个问题是自动下载的模型有好几个configuration_chatglm.py我不知道应该修改哪个，就全给修改了

**Comment by xiaofeihhu** [comment]
configuration_chatglm.py中改了如下两行：
pre_seq_len=128,
self.pre_seq_len = 128
再运行streamlit run web_demo2.py又出现下面的异常：
Traceback (most recent call last):
  File "/home/cims/conda2/lib/python3.8/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
  File "/home/cims/github/ChatGLM2-6B/web_demo2.py", line 25, in <module>
    tokenizer, model = get_model()
  File "/home/cims/conda2/lib/python3.8/site-packages/streamlit/runtime/caching/cache_utils.py", line 211, in wrapper
    return cached_func(*args, **kwargs)
  File "/home/cims/conda2/lib/python3.8/site-packages/streamlit/runtime/caching/cache_utils.py", line 240, in __call__
    return self._get_or_create_cached_value(args, kwargs)
  File "/home/cims/conda2/lib/python3.8/site-packages/streamlit/runtime/caching/cache_utils.py", line 266, in _get_or_create_cached_value
    return self._handle_cache_miss(cache, value_key, func_args, func_kwargs)
  File "/home/cims/conda2/lib/python3.8/site-packages/streamlit/runtime/caching/cache_utils.py", line 320, in _handle_cache_miss
    computed_value = self._info.func(*func_args, **func_kwargs)
  File "/home/cims/github/ChatGLM2-6B/web_demo2.py", line 19, in get_model
    model = load_model_on_gpus("/home/cims/model/chatglm2-6b", num_gpus=2)
  File "/home/cims/github/ChatGLM2-6B/utils.py", line 57, in load_model_on_gpus
    model = dispatch_model(model, device_map=device_map)
  File "/home/cims/conda2/lib/python3.8/site-packages/accelerate/big_modeling.py", line 330, in dispatch_model
    check_device_map(model, device_map)
  File "/home/cims/conda2/lib/python3.8/site-packages/accelerate/utils/modeling.py", line 902, in check_device_map
    raise ValueError(
ValueError: The device_map provided does not give any device for the following parameters: transformer.prefix_encoder.embedding.weight

**Comment by xiao1014** [comment]
> configuration_chatglm.py中改了如下两行： pre_seq_len=128, self.pre_seq_len = 128 再运行streamlit run web_demo2.py又出现下面的异常： Traceback (most recent call last): File "/home/cims/conda2/lib/python3.8/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 552, in _run_script exec(code, module.**dict**) File "/home/cims/github/ChatGLM2-6B/web_demo2.py", line 25, in tokenizer, model = get_model() File "/home/cims/conda2/lib/python3.8/site-packages/streamlit/runtime/caching/cache_utils.py", line 211, in wrapper return cached_func(*args, **kwargs) File "/home/cims/conda2/lib/python3.8/site-packages/streamlit/runtime/caching/cache_utils.py", line 240, in **call** return self._get_or_create_cached_value(args, kwargs) File "/home/cims/conda2/lib/python3.8/site-packages/streamlit/runtime/caching/cache_utils.py", line 266, in _get_or_create_cached_value return self._handle_cache_miss(cache, value_key, func_args, func_kwargs) File "/home/cims/conda2/lib/python3.8/site-packages/streamlit/runtime/caching/cache_utils.py", line 320, in _handle_cache_miss computed_value = self._info.func(*func_args, **func_kwargs) File "/home/cims/github/ChatGLM2-6B/web_demo2.py", line 19, in get_model model = load_model_on_gpus("/home/cims/model/chatglm2-6b", num_gpus=2) File "/home/cims/github/ChatGLM2-6B/utils.py", line 57, in load_model_on_gpus model = dispatch_model(model, device_map=device_map) File "/home/cims/conda2/lib/python3.8/site-packages/accelerate/big_modeling.py", line 330, in dispatch_model check_device_map(model, device_map) File "/home/cims/conda2/lib/python3.8/site-packages/accelerate/utils/modeling.py", line 902, in check_device_map raise ValueError( ValueError: The device_map provided does not give any device for the following parameters: transformer.prefix_encoder.embedding.weight



> configuration_chatglm.py中改了如下两行： pre_seq_len=128, self.pre_seq_len = 128 再运行streamlit run web_demo2.py又出现下面的异常： Traceback (most recent call last): File "/home/cims/conda2/lib/python3.8/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 552, in _run_script exec(code, module.**dict**) File "/home/cims/github/ChatGLM2-6B/web_demo2.py", line 25, in tokenizer, model = get_model() File "/home/cims/conda2/lib/python3.8/site-packages/streamlit/runtime/caching/cache_utils.py", line 211, in wrapper return cached_func(*args, **kwargs) File "/home/cims/conda2/lib/python3.8/site-packages/streamlit/runtime/caching/cache_utils.py", line 240, in **call** return self._get_or_create_cached_value(args, kwargs) File "/home/cims/conda2/lib/python3.8/site-packages/streamlit/runtime/caching/cache_utils.py", line 266, in _get_or_create_cached_value return self._handle_cache_miss(cache, value_key, func_args, func_kwargs) File "/home/cims/conda2/lib/python3.8/site-packages/streamlit/runtime/caching/cache_utils.py", line 320, in _handle_cache_miss computed_value = self._info.func(*func_args, **func_kwargs) File "/home/cims/github/ChatGLM2-6B/web_demo2.py", line 19, in get_model model = load_model_on_gpus("/home/cims/model/chatglm2-6b", num_gpus=2) File "/home/cims/github/ChatGLM2-6B/utils.py", line 57, in load_model_on_gpus model = dispatch_model(model, device_map=device_map) File "/home/cims/conda2/lib/python3.8/site-packages/accelerate/big_modeling.py", line 330, in dispatch_model check_device_map(model, device_map) File "/home/cims/conda2/lib/python3.8/site-packages/accelerate/utils/modeling.py", line 902, in check_device_map raise ValueError( ValueError: The device_map provided does not give any device for the following parameters: transformer.prefix_encoder.embedding.weight

在utils.py的device_map设置transformer.prefix_encoder.embedding.weight将解决此错误
    device_map = {
        'transformer.embedding.word_embeddings': 0,
        'transformer.encoder.final_layernorm': 0,
        'transformer.prefix_encoder.embedding.weight': 0,
        'transformer.output_layer': 0,
        'transformer.rotary_pos_emb': 0,
        'lm_head': 0
    }
