### ISSUE TITLE
[Feature]  It's very cool, chatglm2-6b,  DB-GPT中提供了炫酷的前端界面

### ISSUE THREAD

**Issue by csunny** [THUDM/ChatGLM2-6B#275]
### Is your feature request related to a problem? Please describe.

https://github.com/THUDM/ChatGLM2-6B/assets/17919400/534bfe42-2a09-4609-9f0a-771488d4d8ee

开源项目地址: https://github.com/csunny/DB-GPT

### Solutions

当前chatglm2-6b 缺少前端输出，在使用中比较不便。  DB-GPT项目基于chatglm2-6b 提供了各种炫酷的前端，以及打造了知识库等能力。 

![image](https://github.com/THUDM/ChatGLM2-6B/assets/17919400/2ab367d6-1df8-4dad-abc9-b7989408e9a8)

![image](https://github.com/THUDM/ChatGLM2-6B/assets/17919400/5f58fd6f-fd7d-499e-b5a6-8803b0e95f57)

**Comment by hiliuxg** [comment]
chatglm2其实对于NLP2SQL的能力还很弱

**Comment by csunny** [comment]
@hiliuxg  https://github.com/csunny/DB-GPT-Hub  Text-to-SQL 可以关注我们这个项目 😄，我们是一套组合拳
