### ISSUE TITLE
[Help] <执行python .\web_demo.py 后 c盘爆满>

### ISSUE THREAD

**Issue by Loveyless** [THUDM/ChatGLM2-6B#284]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

c盘爆满了 而且找不到哪里删除 我项目代码在别的盘 模型也在当前项目下 但是c盘莫名红了

### Steps To Reproduce

1

### Environment

```markdown
win10
```

**Comment by duzx16** [comment]
在 `from_pretrained` 的时候加上 `cache_dir=<your cache path>`
