### ISSUE TITLE
[BUG/Help] 如何在ChatGLM2使用System Prompts

### ISSUE THREAD

**Issue by zhangmianhongni** [THUDM/ChatGLM2-6B#286]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

如何在ChatGLM2使用System Prompts，在哪里进行传参

### Steps To Reproduce

如何在ChatGLM2使用System Prompts，在哪里进行传参

### Environment

```markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by duzx16** [comment]
目前还不支持 system prompts。但是你可以把对模型的要求加在 prompt 的最前面
