### ISSUE TITLE
[BUG/Help] <chatglm2的词表为什么减少了呢？>

### ISSUE THREAD

**Issue by echoht** [THUDM/ChatGLM2-6B#288]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

chatglm2的vocab_size 是64794；chatglm1的vocab_size是130005，为啥变少了呢？

### Steps To Reproduce

无

### Environment

```markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by duzx16** [comment]
重新训练了一个 tokenizer，词表太大对于小模型来说时间开销会比较大

**Comment by floating19** [comment]
> 重新训练了一个 tokenizer，词表太大对于小模型来说时间开销会比较大

请教下，tokenizer的大小是64794， 而模型的word_embedding 和 output layer 都是 65024， 模型里多出来的230个word是预留/无用的吗
