### ISSUE TITLE
ChatGLM2 可以替换 VisualGLM 中的ChatGLM v1 模型吗

### ISSUE THREAD

**Issue by llliuxz** [THUDM/ChatGLM2-6B#293]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

如果能够替换，能否给一个大致的替换步骤和需要注意的问题。用V2版本替换之后，有如下报错：
normalizer.cc(50) LOG(INFO) precompiled_charsmap is empty. use identity normalization.
Traceback (most recent call last):
  File "infer_test.py", line 69, in <module>
    main()
  File "infer_test.py", line 62, in main
    invalid_slices=[slice(63823, 130000)] if args.english else []
  File "/root/paddlejob/workspace/env_run/code/model/chat.py", line 167, in chat
    bog = output.index(tokenizer.bos_token_id)
ValueError: None is not in list

### Environment

```markdown
OS: Ubuntu 20.04
Python: 3.8
Transformers: 4.26.1
PyTorch: 1.12
CUDA Support: True
```

**Comment by duzx16** [comment]
不能替换，可以等 VisualGLM 更新

**Comment by llliuxz** [comment]
> 不能替换，可以等 VisualGLM 更新

好的，谢谢解答。
请问VIsualGLM 模型的更新大概会到什么时候呢
