### ISSUE TITLE
请问商用是付费的还是免费的啊

### ISSUE THREAD

**Issue by rayvzn119** [THUDM/ChatGLM2-6B#3]
### Solutions

如题

**Comment by ainndejj11** [comment]
同问，可以免费商用了么？

**Comment by hu-qi** [comment]
> 同问，可以免费商用了么？

好像文档中有说明：

> 申请商用许可与捐赠请联系 [yiwen.xu@zhipuai.cn](mailto:yiwen.xu@zhipuai.cn)

**Comment by yar2001** [comment]
希望能免费商用。大模型是基础设施，很多团队可能宁愿用差一点的模型，也不敢把资源投资到专有技术上。
可以像MongoDB那样，允许模型及模型的衍生品部署给自己企业用，但不允许部署成 API 对外提供服务。这样可以消除下游用户对被供应商锁定的担忧，也能吸引更多小团队使用 GLM 的 MaaS 平台

**Comment by runningBolin** [comment]
二代6b模型商用不是免费的，参考https://open.bigmodel.cn/pricing

**Comment by Alex-Zuo-One** [comment]
> 二代6b模型商用不是免费的，参考https://open.bigmodel.cn/pricing

这个只是api调用的定价，不代表自己本地部署也要收费

**Comment by cristianohello** [comment]
@Alex-Zuo-One 
收费的！本地私有化部署要钱，官网上写的呢

**Comment by Alex-Zuo-One** [comment]
> @Alex-Zuo-One 收费的！本地私有化部署要钱，官网上写的呢

那是别人帮你部署要钱，你自己部署的话发邮件获得批准就好

**Comment by runningBolin** [comment]
> > @Alex-Zuo-One 收费的！本地私有化部署要钱，官网上写的呢
> 
> 那是别人帮你部署要钱，你自己部署的话发邮件获得批准就好

完全自主私有化部署授权30w一年，写的明明白白的

**Comment by kingwpf** [comment]
> > > @Alex-Zuo-One 收费的！本地私有化部署要钱，官网上写的呢
> > 
> > 
> > 那是别人帮你部署要钱，你自己部署的话发邮件获得批准就好
> 
> 完全自主私有化部署授权30w一年，写的明明白白的

<img width="746" alt="image" src="https://github.com/THUDM/ChatGLM2-6B/assets/10610290/85fe3886-7d7a-4a47-b722-02194128446e">
