### ISSUE TITLE
[BUG/Help] <title>在do-predict时候报错了 ValueError: Hypothesis is empty.

### ISSUE THREAD

**Issue by qihangf** [THUDM/ChatGLM2-6B#300]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

在do_predict所有进度走完得时候就会遇到这个bug。
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/wyxx/warBackup/ner/ChatGLM2-6B/ptuning/main.py:411 in <module>                             │
│                                                                                                  │
│   408                                                                                            │
│   409                                                                                            │
│   410 if __name__ == "__main__":                                                                 │
│ ❱ 411 │   main()                                                                                 │
│   412                                                                                            │
│                                                                                                  │
│ /home/wyxx/warBackup/ner/ChatGLM2-6B/ptuning/main.py:377 in main                                 │
│                                                                                                  │
│   374 │                                                                                          │
│   375 │   if training_args.do_predict:                                                           │
│   376 │   │   logger.info("*** Predict ***")                                                     │
│ ❱ 377 │   │   predict_results = trainer.predict(predict_dataset, metric_key_prefix="predict",    │
│   378 │   │   metrics = predict_results.metrics                                                  │
│   379 │   │   max_predict_samples = (                                                            │
│   380 │   │   │   data_args.max_predict_samples if data_args.max_predict_samples is not None e   │
│                                                                                                  │
│ /home/wyxx/warBackup/ner/ChatGLM2-6B/ptuning/trainer_seq2seq.py:136 in predict                   │
│                                                                                                  │
│   133 │   │   self._gen_kwargs = gen_kwargs                                                      │
│   134 │   │                                                                                      │
│   135 │   │                                                                                      │
│ ❱ 136 │   │   return super().predict(test_dataset, ignore_keys=ignore_keys, metric_key_prefix=   │
│   137 │                                                                                          │
│   138 │   def prediction_step(                                                                   │
│   139 │   │   self,                                                                              │
│                                                                                                  │
│ /data/software/anaconda3/lib/python3.9/site-packages/transformers/trainer.py:3129 in predict     │
│                                                                                                  │
│   3126 │   │   start_time = time.time()                                                          │
│   3127 │   │                                                                                     │
│   3128 │   │   eval_loop = self.prediction_loop if self.args.use_legacy_prediction_loop else se  │
│ ❱ 3129 │   │   output = eval_loop(                                                               │
│   3130 │   │   │   test_dataloader, description="Prediction", ignore_keys=ignore_keys, metric_k  │
│   3131 │   │   )                                                                                 │
│   3132 │   │   total_batch_size = self.args.eval_batch_size * self.args.world_size               │
│                                                                                                  │
│ /data/software/anaconda3/lib/python3.9/site-packages/transformers/trainer.py:3353 in             │
│ evaluation_loop                                                                                  │
│                                                                                                  │
│   3350 │   │   │   │   │   EvalPrediction(predictions=all_preds, label_ids=all_labels, inputs=a  │
│   3351 │   │   │   │   )                                                                         │
│   3352 │   │   │   else:                                                                         │
│ ❱ 3353 │   │   │   │   metrics = self.compute_metrics(EvalPrediction(predictions=all_preds, lab  │
│   3354 │   │   else:                                                                             │
│   3355 ���   │   │   metrics = {}                                                                  │
│   3356                                                                                           │
│                                                                                                  │
│ /home/wyxx/warBackup/ner/ChatGLM2-6B/ptuning/main.py:308 in compute_metrics                      │
│                                                                                                  │
│   305 │   │   │   hypothesis = list(jieba.cut(pred))                                             │
│   306 │   │   │   reference = list(jieba.cut(label))                                             │
│   307 │   │   │   rouge = Rouge()                                                                │
│ ❱ 308 │   │   │   scores = rouge.get_scores(' '.join(hypothesis) , ' '.join(reference))          │
│   309 │   │   │   result = scores[0]                                                             │
│   310 │   │   │                                                                                  │
│   311 │   │   │   for k, v in result.items():                                                    │
│                                                                                                  │
│ /data/software/anaconda3/lib/python3.9/site-packages/rouge_chinese/rouge.py:116 in get_scores    │
│                                                                                                  │
│   113 │   │   assert(len(hyps) == len(refs))                                                     │
│   114 │   │                                                                                      │
│   115 │   │   if not avg:                                                                        │
│ ❱ 116 │   │   │   return self._get_scores(hyps, refs)                                            │
│   117 │   │   return self._get_avg_scores(hyps, refs)                                            │
│   118 │                                                                                          │
│   119 │   def _get_scores(self, hyps, refs):                                                     │
│                                                                                                  │
│ /data/software/anaconda3/lib/python3.9/site-packages/rouge_chinese/rouge.py:129 in _get_scores   │
│                                                                                                  │
│   126 │   │   │                                                                                  │
│   127 │   │   │   for m in self.metrics:                                                         │
│   128 │   │   │   │   fn = Rouge.AVAILABLE_METRICS[m]                                            │
│ ❱ 129 │   │   │   │   sc = fn(                                                                   │
│   130 │   │   │   │   │   hyp,                                                                   │
│   131 │   │   │   │   │   ref,                                                                   │
│   132 │   │   │   │   │   raw_results=self.raw_results,                                          │
│                                                                                                  │
│ /data/software/anaconda3/lib/python3.9/site-packages/rouge_chinese/rouge.py:54 in <lambda>       │
│                                                                                                  │
│    51 class Rouge:                                                                               │
│    52 │   DEFAULT_METRICS = ["rouge-1", "rouge-2", "rouge-l"]                                    │
│    53 │   AVAILABLE_METRICS = {                                                                  │
│ ❱  54 │   │   "rouge-1": lambda hyp, ref, **k: rouge_score.rouge_n(hyp, ref, 1, **k),            │
│    55 │   │   "rouge-2": lambda hyp, ref, **k: rouge_score.rouge_n(hyp, ref, 2, **k),            │
│    56 │   │   "rouge-3": lambda hyp, ref, **k: rouge_score.rouge_n(hyp, ref, 3, **k),            │
│    57 │   │   "rouge-4": lambda hyp, ref, **k: rouge_score.rouge_n(hyp, ref, 4, **k),            │
│                                                                                                  │
│ /data/software/anaconda3/lib/python3.9/site-packages/rouge_chinese/rouge_score.py:253 in rouge_n │
│                                                                                                  │
│   250 │     ValueError: raises exception if a param has len <= 0                                 │
│   251 │   """                                                                                    │
│   252 │   if len(evaluated_sentences) <= 0:                                                      │
│ ❱ 253 │   │   raise ValueError("Hypothesis is empty.")                                           │
│   254 │   if len(reference_sentences) <= 0:                                                      │
│   255 │   │   raise ValueError("Reference is empty.")                                            │
│   256                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ValueError: Hypothesis is empty.
100%|██████████████████████████████████████████████████████████████████████| 915/915 [59:40<00:00,  3.91s/it]
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 1892) of binary: /data/software/anaconda3/bin/python
Traceback (most recent call last):
  File "/data/software/anaconda3/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/data/software/anaconda3/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/data/software/anaconda3/lib/python3.9/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/data/software/anaconda3/lib/python3.9/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/data/software/anaconda3/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/data/software/anaconda3/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
main.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-07-14_10:00:24
  host      : iZbp1akf2t5wvuwotqdpbtZ
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 1892)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html

### Steps To Reproduce

bash evaluate.sh

### Environment

```markdown
- OS:Ubuntu 20.04
- Python:3.10
- Transformers:4.30.2
- PyTorch:2.01
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by lilongxian** [comment]
这段代码：  

preds, labels = eval_preds
if isinstance(preds, tuple):
        preds = preds[0]
decoded_preds = tokenizer.batch_decode(preds, skip_special_tokens=True)  

 for pred, label in zip(decoded_preds, decoded_labels):
            hypothesis = list(jieba.cut(pred))
            reference = list(jieba.cut(label))
            rouge = Rouge()
            scores = rouge.get_scores(' '.join(hypothesis), ' '.join(reference))
            result = scores[0]

这是pred为空了，模型对某个text的预测回复为空，当pred=[]时就会包这样的错误，
你可以检查一下你的输入句有没有空的，另外最简单的修改就是：
 for pred, label in zip(decoded_preds, decoded_labels):
      if not pred and not label:
            continue

**Comment by sharemen** [comment]
同样遇到这个问题，我确认我的训练数据没有为空的项

**Comment by Qiuxida** [comment]
debug看了label有值，pred值为空字符，有无大佬遇到这问题

**Comment by 1181000705** [comment]
同样的问题，训练数据没有为空的项

**Comment by AliceShen122** [comment]
我也有这个问题

**Comment by AlexYoung757** [comment]
> 我也遇到了同样的问题，我可以确认我的训练数据没有空项。但是如果自己手动编辑少量数据就没有问题。

+1，还特意检查了一遍数据，确认无误。但是我是evaluate的时候出现的

**Comment by zzwtop1** [comment]
这是因为预测的时候生成了一个空值，也就是啥都没预测出来，类似这种格式：{"labels": "1", "predict": ""}，加上这行代码就行了：
if not pred or not label:
continue
就算标签不为空，预测结果为空值也能输出出来

**Comment by Skywalker-Harrison** [comment]
> 这段代码：
> 
> preds, labels = eval_preds if isinstance(preds, tuple): preds = preds[0] decoded_preds = tokenizer.batch_decode(preds, skip_special_tokens=True)
> 
> for pred, label in zip(decoded_preds, decoded_labels): hypothesis = list(jieba.cut(pred)) reference = list(jieba.cut(label)) rouge = Rouge() scores = rouge.get_scores(' '.join(hypothesis), ' '.join(reference)) result = scores[0]
> 
> 这是pred为空了，模型对某个text的预测回复为空，当pred=[]时就会包这样的错误， 你可以检查一下你的输入句有没有空的，另外最简单的修改就是： for pred, label in zip(decoded_preds, decoded_labels): if not pred and not label: continue

这里应该是if not pred or not label, 不然pred无，label有的情况也会报错

**Comment by Chic-star** [comment]
你好，解决了吗，我使用上述方案并没有解决问题

**Comment by yanyujian** [comment]
如果不是数据集的问题，那么加大验证时的step就行了。训练的步数太少，然后着急忙慌的去验证，结果预测结果为空了。仔细看堆栈，也会说是len(evaluated_setences)<=0 然后就抛出那个异常了。

**Comment by Chic-star** [comment]
我已收到。

**Comment by syyou3** [comment]
> 我已收到。

请问下你的问题解决了吗？我按照上面的方法还是不行

**Comment by Chic-star** [comment]
我已收到。

**Comment by Schmerle-Cki** [comment]
查了下rouge.py源码，这里：

```
def _get_avg_scores(self, hyps, refs):
        scores = {m: {s: 0 for s in self.stats} for m in self.metrics}
        if self.return_lengths:
            scores["lengths"] = {"hyp": 0, "ref": 0}

        count = 0
        for (hyp, ref) in zip(hyps, refs):
            # 注意此处分隔符
            hyp = [" ".join(_.split()) for _ in hyp.split(".") if len(_) > 0]
            ref = [" ".join(_.split()) for _ in ref.split(".") if len(_) > 0]

            for m in self.metrics:
                fn = Rouge.AVAILABLE_METRICS[m]
                sc = fn(hyp, ref, exclusive=self.exclusive)
```

所以除了空串外，还应当排查“."

**Comment by Chic-star** [comment]
我已收到。
