### ISSUE TITLE
能发布未经微调的glm2的参数吗

### ISSUE THREAD

**Issue by wn1652400018** [THUDM/ChatGLM2-6B#301]
### Solutions

能发布未经微调的glm2的参数吗

**Comment by lilongxian** [comment]
商用发布的话好像需要GLM官方授权吧，这个最好得确认一下

**Comment by wn1652400018** [comment]
我是想问问作者能不能发布原始的glm2模型参数。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年7月14日(周五) 下午4:12
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [THUDM/ChatGLM2-6B] 能发布未经微调的glm2的参数吗 (Issue #301)




 
商用发布的话好像需要GLM官方授权吧，这个最好得确认一下

**Comment by lilongxian** [comment]
哦哦，哈哈，刚才没理解清楚，
在这里官方开源的有模型权重参数、配置参数、源代码都有，可以手动下，
https://huggingface.co/THUDM/chatglm2-6b/tree/main

**Comment by duzx16** [comment]
Duplicate of #4
