### ISSUE TITLE
[BUG] 多卡部署pt训练后的模型时，启动streamlit run web_demo2.py报错“AttributeError: 'ChatGLMModel' object has no attribute 'prefix_encoder'”

### ISSUE THREAD

**Issue by xiaofeihhu** [THUDM/ChatGLM2-6B#303]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

执行ptuning下的train.sh进行训练微调后，修改web_demo2.py中多显卡部分代码。
启动streamlit run web_demo2.py时出现以下异常：
]
2023-07-14 11:46:00.648 Uncaught app exception
Traceback (most recent call last):
  File "/home/cims/conda2/lib/python3.8/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
  File "/home/cims/github/ChatGLM2-6B/web_demo2.py", line 33, in <module>
    model.transformer.prefix_encoder.load_state_dict(new_prefix_state_dict)
  File "/home/cims/conda2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'ChatGLMModel' object has no attribute 'prefix_encoder'

**web_demo2.py**代码：
from transformers import AutoConfig, AutoModel, AutoTokenizer
import torch,os
import streamlit as st

st.set_page_config(
    page_title="ChatGLM2-6b 演示",
    page_icon=":robot:",
    layout='wide'
)

@st.cache_resource
def get_model():
    config = AutoConfig.from_pretrained("/home/cims/model/chatglm2-6b", trust_remote_code=True, pre_seq_len=128)
    tokenizer = AutoTokenizer.from_pretrained("/home/cims/model/chatglm2-6b", trust_remote_code=True)
    #model = AutoModel.from_pretrained("/home/cims/model/chatglm2-6b", config=config, trust_remote_code=True).cuda()
    # 多显卡支持，使用下面两行代替上面一行，将num_gpus改为你实际的显卡数量
    from utils import load_model_on_gpus
    model = load_model_on_gpus("/home/cims/model/chatglm2-6b", num_gpus=2)
	
    model = model.eval()
    return tokenizer, model

tokenizer, model = get_model()
#config = AutoConfig.from_pretrained("/home/cims/model/chatglm2-6b", trust_remote_code=True, pre_seq_len=128)
#model = AutoModel.from_pretrained("/home/cims/model/chatglm2-6b", config=config, trust_remote_code=True).cuda()
prefix_state_dict = torch.load(os.path.join("/home/cims/github/ChatGLM2-6B/ptuning/output-LCSTS_new/adgen-chatglm2-6b-pt-128-2e-2/checkpoint-3000/", "pytorch_model.bin"))
new_prefix_state_dict = {}
for k, v in prefix_state_dict.items():
    if k.startswith("transformer.prefix_encoder."):
        new_prefix_state_dict[k[len("transformer.prefix_encoder."):]] = v
model.transformer.prefix_encoder.load_state_dict(new_prefix_state_dict)

st.title("ChatGLM2-6B")
.....................................

### Steps To Reproduce

streamlit run web_demo2.py

### Environment

```markdown
- OS:Centos7
- Python:3.8
- Transformers:4.30.2
- PyTorch:2.0.1 
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :true
```

**Comment by lilongxian** [comment]
chatGLM2-6B模型网络源码更新过一次，6月25日版本中GLM模型没有前置编码器，是后来增加的。你可以从hf从新下载以下最新的模型py脚本再试试。新代码中的相关变量在此：
class ChatGLMForConditionalGeneration(ChatGLMPreTrainedModel):
    def __init__(self, config: ChatGLMConfig, empty_init=True, device=None):
        super().__init__(config)
。。。。。。。。
        self.transformer = ChatGLMModel(config, empty_init=empty_init, device=device)

class ChatGLMModel(ChatGLMPreTrainedModel):
    def __init__(self, config: ChatGLMConfig, device=None, empty_init=True):
        super().__init__(config)
       。。。。。。。。
        if self.pre_seq_len is not None:
           。。。。。。
            self.prefix_encoder = PrefixEncoder(config)

GLM1、2中，前置位置词嵌入编码器是可选的，当启用时，在训练中会学习kv前置部分的词嵌入，学习机制是通过ATT机制中的两次dot实现的（数学上是dot(q,k^T)升维--dot(k,v)降维的思想，因此不影响ATT的最终输出形态），清华GLM这样的设计可谓十分的秒哉！



言归正转，你可以这样试试看行不行：
1.  更新modeling_chatglm.py
2. 训练和模型应用中都要设置 --pre_seq_len 参数大于0，启动前置位置词嵌入编码器。

**Comment by bxjxxyy** [comment]
https://github.com/THUDM/ChatGLM2-6B/issues/260
我是单卡也遇到这个问题，后来在csdn解决了。
修改configuration_chatglm.py的pre_seq_len=None改为你的长度
