### ISSUE TITLE
基于清华chatGLM2-6B改进版：《弹性可压缩式位置标准化的旋转位置词嵌入编码器+LORA量化训练》新版本发布，欢迎大家关注交流！

### ISSUE THREAD

**Issue by lilongxian** [THUDM/ChatGLM2-6B#304]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

基于清华chatGLM2-6B改进版：《弹性可压缩式位置标准化的旋转位置词嵌入编码器+LORA量化训练》新版本发布，欢迎大家关注！

项目地址：https://github.com/lilongxian/BaiYang-chatGLM2-6B

优点：

1. 支持清华chatGLM-6B、alpaca指令微调训练数据格式。

2. 支持Lora量化训练，保留原始权重的能力。

3. 通过生成式的方法支持单任务和多任务知识挖掘类NLP任务。

4. 支持多轮对话、摘要、续写等知识生成类NLP任务。

5. 旋转位置词嵌入编码器支持2048区间弹性标准化压缩，以取得在万级tokens上的更好效果。

### Steps To Reproduce

项目地址：https://github.com/lilongxian/BaiYang-chatGLM2-6B

优点：

1. 支持清华chatGLM-6B、alpaca指令微调训练数据格式。

2. 支持Lora量化训练，保留原始权重的能力。

3. 通过生成式的方法支持单任务和多任务知识挖掘类NLP任务。

4. 支持多轮对话、摘要、续写等知识生成类NLP任务。

5. 旋转位置词嵌入编码器支持2048区间弹性标准化压缩，以取得在万级tokens上的更好效果。

### Environment

```markdown
cuda 11.7
pytorch 1.13.1/2.0
python 3.7/3.8
transformers 4.27.1--4.29.2
```

**Comment by baronyang** [comment]
牛，这么快就出进化版了
