### ISSUE TITLE
[Help] nnodes, standalone, nproc-per-node和注意力模块中partition是什么呢？

### ISSUE THREAD

**Issue by binary-husky** [THUDM/ChatGLM2-6B#306]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

问题咨询，非bug

nnodes, standalone, nproc-per-node 三个参数，代码中似乎没有用到？

以及注意力模块中的partition，注意到代码中使用了多头、多组注意力，但是partition似乎只有一个？partition这个概念是来自哪篇文献呢？

### Steps To Reproduce

问题咨询，非bug

### Environment

```markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA Support
```

**Comment by duzx16** [comment]
前三个请参考 https://pytorch.org/docs/stable/elastic/run.html
partition 是 tensor parallel 的维度，不过实现的都是单卡的所以是 1
