### ISSUE TITLE
对模型推理过程的一些使用感想

### ISSUE THREAD

**Issue by CannedHerringIsSweet** [THUDM/ChatGLM2-6B#309]
### Solutions

1、模型常对于提问中附带的假设默认为真，并以此为前提继续推理。
模型太相信 包含在使用者交互中的信息，会在具有误导性的上下文中继续推理，而不是直接停止，或者反而向提问者提问获得更清晰的信息。

2、模型的推理链对用户显示 
如果我说：如果你不确信你的回答，你可以说不知道。
但是即使如此模型从来不会说不知道。
他会先根据我说的内容，比如我提到了某个名词，他会对这个名词做出名词解释，然后在这个基础上继续推理，然后给出一个不一定让人满意的回答。
对这些推理涉及的概念作出解释这一步没有问题，这是一种信息检索，但有时候检索到了这些信息也没有得出答案，或者没有得出一个置信度较高的答案，这些推理链应该就没用了，被废弃了，而不是展示出来，否则阅读很长一段文字获得的信息密度还不如一句‘我不知道’高。

结合1和2，我建议 在实际部署中 
模型先在一个用户看不到的上下文中推理--→得到一个答案，如果置信度高，则发送，否则针对缺失的关键信息进行提问，或进行否定回答，并以此创建一个数据集进行针对性训练。

**Comment by duzx16** [comment]
感谢建议。如果有实现的话可以提 pr

**Comment by thsno02** [comment]
GPT-4 也会有这个问题，我怀疑是因为模型在某一个阶段训练的时候，学到了某种原则，比如”讨好用户“或者是”一定要响应“。根据回答判断，我个人更倾向于”讨好用户“这个倾向。

**Comment by hhy150** [comment]
生成模型的话要怎样看置信度呢？
