### ISSUE TITLE
提取姓名时，有时会把提示history中的结果带回来

### ISSUE THREAD

**Issue by czhcc** [THUDM/ChatGLM2-6B#31]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

history = [("张三出生于北京。","姓名:[张三]"),
          ("李四接见五五","姓名:[李四，王五]")]

当传入这样的提示时，提取的姓名中会把张三，李四和王五返回

### Steps To Reproduce

text = """
这里是长度为2k的文本
"""
query_cn = f"""
{text}\n\n
你是一个优秀的语言学家，任务是从给定的句子中标记多个人实体。你从上面的文本中，提取人的姓名，以例子中的格式输出。
"""
history = [("张三出生于北京。","姓名:[张三]"),
          ("李四接见五五","姓名:[李四，王五]")]
data = {"query": query_cn, "history": history}

返回的结果中，除text中的姓名外，还会带有张三，李四，王五

### Environment

```markdown
- OS:Ubuntu 20.04
- Python:3.8
- Transformers:4.27.1
- PyTorch:2.0.0
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :True
```

**Comment by duzx16** [comment]
感谢反馈
