### ISSUE TITLE
M1芯片Mac加载模型时报错

### ISSUE THREAD

**Issue by dzgdp888** [THUDM/ChatGLM2-6B#32]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

通过mps后端加载
    tokenizer = AutoTokenizer.from_pretrained("/本地路径示例/chatglm-6b", trust_remote_code=True)
    model = AutoModel.from_pretrained("/本地路径示例/chatglm-6b", trust_remote_code=True).half().to('mps')

提示：UserWarning: MPS: no support for int64 min/max ops, casting it to int32
然后系统就一直卡住了，没有输出
<img width="1390" alt="image" src="https://github.com/THUDM/ChatGLM2-6B/assets/13160185/cb24122b-b7aa-4c30-ac61-73531fdb54f2">

已安装mps
<img width="566" alt="image" src="https://github.com/THUDM/ChatGLM2-6B/assets/13160185/209bcfbe-964c-415e-9ecd-f78e5b5fe1e7">

### Steps To Reproduce

111

### Environment

```markdown
- OS:MacOS Ventura
- Python:3.10
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :False
```

**Comment by duzx16** [comment]
我只在 M2 芯片上测试过。看截图是在运行 `api.py`，你可以先尝试运行 `cli_demo.py`。如果不行的话再把 pytorch-nightly 升级到最新版本？

**Comment by dzgdp888** [comment]
你用的mac内存是多大的？
我已经按照1.0里的文档升级到了 pytorch-nightly最新版本，还是一样的问题
<img width="639" alt="image" src="https://github.com/THUDM/ChatGLM2-6B/assets/13160185/71c5901a-c45e-4515-a778-de1b350a65b9">

用cli_demo.py提示IndexError: piece id is out of range.

**Comment by duzx16** [comment]
@dzgdp888 32GB. 16GB 的话确实会放不下

**Comment by dzgdp888** [comment]
升级下64GM1 max，问题没有复现了

**Comment by stoneLee81** [comment]
> 升级下64GM1 max，问题没有复现了

请问，你是使用的pytorch-nightly和python版本号是什么，我也用的是m1max,在运行到model.chat就一直卡住不动了。我用的Python: 3.9.7， Transformers:4.30.2， PyTorch: 2.1.0.dev20230629

**Comment by dzgdp888** [comment]
@stoneLee81 
python:3.10.11  transformer:4.30.2 torch:2.1.0.dev20230626
