### ISSUE TITLE
[BUG/Help] 今天突然报错，环境和模型没有任何调整:TypeError: transformers.tokenization_utils.PreTrainedTokenizer.init() got multiple values for keyword argument 'clean_up_tokenization_spaces'

### ISSUE THREAD

**Issue by show88118** [THUDM/ChatGLM2-6B#321]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

super().__init__(padding_side=padding_side, clean_up_tokenization_spaces=False, **kwargs)
TypeError: transformers.tokenization_utils.PreTrainedTokenizer.__init__() got multiple values for keyword argument 'clean_up_tokenization_spaces'

### Steps To Reproduce

今天突然报错，环境和模型没有任何调整

### Environment

```markdown
- OS:
- Python:3.9
- Transformers:4.30.2
- PyTorch:2.0
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :True
```

**Comment by lilongxian** [comment]
这种问题要考虑一下你掉用本函数时的位置参数赋值是不是错位了，尽量用位置参数明赋值错不了。

解决办法：
 官方代码新增加了参数，导致参数位置变动，你应该从hf从新更新一下tokenization脚本。

**Comment by duzx16** [comment]
AutoTokenizer 初始化的时候去掉 clean_up_tokenization_spaces
或者使用最新版的模型实现也没有这个问题
