### ISSUE TITLE
RuntimeError: "arange_cpu" not implemented for 'Half'

### ISSUE THREAD

**Issue by Sunnylee0101** [THUDM/ChatGLM2-6B#33]
### Is your feature request related to a problem? Please describe.

有朋友报这种错吗，是因为torch版本不对导致的吗

### Solutions

有朋友报这种错吗，是因为torch版本不对导致的吗

### Additional context

有朋友报这种错吗，是因为torch版本不对导致的吗

**Comment by pvop** [comment]
一样的错误，torch升级到2.0.0的版本就行了

**Comment by mosay95** [comment]
device='cuda:0'
model = AutoModel.from_pretrained(model_dir, trust_remote_code=True, device=device).half().cuda()
我这样改就能跑了

**Comment by duzx16** [comment]
已经修复了，没有在 PyTorch 2.0 以前的版本测试过

**Comment by Sunnylee0101** [comment]
兄弟们  昨天已经可以了 忘记了说，torch升级到2.0.1.transformers升级到4.30就可以了

**Comment by HelixPark** [comment]
> 已经修复了，没有在 PyTorch 2.0 以前的版本测试过

请问，能指出修复位置吗，谢谢

**Comment by Sunnylee0101** [comment]
> 

torch2.0以下的版本显存不到13G跑不起来，哪怕int4的版本都不行。解决方案：更新你的显卡驱动到最新版（这样才支持更新的cuda），再安装一下新的cuda，最好是cuda12 以及对应的cudnn，这里可以安装多个cuda版本并存的（参考：https://blog.csdn.net/m0_37605642/article/details/117932717），然后再安装torch2.0.1版本和transformers4.30版本  改一下代码：model = AutoModel.from_pretrained("I:\\chatglm2-6b", trust_remote_code=True).quantize(4).cuda()就可以了（我这里的模型是从hugging face上下载到本地的）

**Comment by HelixPark** [comment]
> > 
> 
> torch2.0以下的版本显存不到13G跑不起来，哪怕int4的版本都不行。解决方案：更新你的显卡驱动到最新版（这样才支持更新的cuda），再安装一下新的cuda，最好是cuda12 以及对应的cudnn，这里可以安装多个cuda版本并存的（参考：[https://blog.csdn.net/m0_37605642/article/details/117932717），然后再安装torch2.0.1版本和transformers4.30版本](https://blog.csdn.net/m0_37605642/article/details/117932717%EF%BC%89%EF%BC%8C%E7%84%B6%E5%90%8E%E5%86%8D%E5%AE%89%E8%A3%85torch2.0.1%E7%89%88%E6%9C%AC%E5%92%8Ctransformers4.30%E7%89%88%E6%9C%AC) 改一下代码：model = AutoModel.from_pretrained("I:\chatglm2-6b", trust_remote_code=True).quantize(4).cuda()就可以了（我这里的模型是从hugging face上下载到本地的）

我的海光GPU 32G多卡+编译的torch 1.10，单卡能跑、多卡报这个错误；我在英伟达服务器上，一切都OK（用的torch 2.0）

**Comment by sduGuyu** [comment]
我按照这个操作处理后确实能跑了，但我是10G的显卡，这样有什么影响吗
