### ISSUE TITLE
[BUG]一个逻辑推理题回答错误

### ISSUE THREAD

**Issue by 137-rick** [THUDM/ChatGLM2-6B#35]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

假设有一个池塘，里面有无穷多的水。现有2个空水壶，容积分别为5升和6升。问题是如何只用这2个水壶从池塘里取得3升的水。

可以按照以下步骤只用这两个水壶从池塘里取得3升水:
1. 用容积为6升的水壶装满水。
2. 将6升水壶中的水倒入容积为5升的水壶中,此时容积为5升的水壶中有1升水。
3. 将池塘中的水倒入容积为6升的水壶中,此时容积为6升的水壶中有1升水。
4. 容积为6升的水壶中还剩余1升水。
5. 将池塘中的水倒入容积为6升的水壶中,此时容积为6升的水壶中有2升水。
6. 容积为6升的水壶中还剩余1升水。
7. 将池塘中的水倒入容积为6升的水壶中,此时容积为6升的水壶中有3升水。
8. 此时容积为6升的水壶中没有剩余的水。
通过以上步骤,我们可以只用这两个水壶从池塘里取得3升水。

### Expected Behavior

第二步错了，应该是6升里面剩余1升

### Steps To Reproduce

input the question on the 

### Environment

```markdown
- OS:linux
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by 137-rick** [comment]
提这个只是样本参考，其他逻辑推理结果很棒

**Comment by duzx16** [comment]
感谢指出，反馈已经收到
