### ISSUE TITLE
想请问下，为啥transformers 版本 找不到4.30.2呢？[BUG/Help] <title>

### ISSUE THREAD

**Issue by nuaahuang** [THUDM/ChatGLM2-6B#356]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

pip install的时候，为什么transformers 4.30.2的发布版本找不到呢
![image](https://github.com/THUDM/ChatGLM2-6B/assets/4338137/70bc75a4-085e-4951-a2d0-bf18b316c54a)

### Steps To Reproduce

pip install requirements.txt 4.30.2版本找不到
![image](https://github.com/THUDM/ChatGLM2-6B/assets/4338137/914df32d-4dbe-48cc-bc53-dc7f1a11ee76)

### Environment

```markdown
- OS: 7.8.2003
- Python: Python 3.7.2
```

**Comment by TheHonestBob** [comment]
这种情况貌似是python版本不够导致的，我的是3.9

**Comment by nuaahuang** [comment]
> 这种情况貌似是python版本不够导致的，我的是3.9
是的 是版本不够，还要注意安装时候pip的版本也的3.9。

**Comment by nuaahuang** [comment]
已解决
