### ISSUE TITLE
[BUG/Help] 本地部署的推理结果和网页demo的结果不一致

### ISSUE THREAD

**Issue by delltower** [THUDM/ChatGLM2-6B#361]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

本地下载模型，并用api.py部署，推理时参数如下：
temperature 0.95
top_p 0.8
max_length 4096
history []
prompt："请给以下文章进行类目标签分类。文章标题：空气悬架液压悬架电磁悬架哪一种汽车悬架更好？。文章内容：空气悬架液压悬架电磁悬架哪一种汽车悬架更好？选项是：['智能与主动安全','结构材料与碰撞安全','动力与行驶','静态体验']，请回答："
返回结果是：response:"'汽车悬架'"
模型并没有按照指令从选项里面选取答案。
官网https://chatglm.cn/detail 
使用同样的prompt 回答是 “该文章应该归类到选项 '动力与行驶'。因为文章主要讨论了不同类型的汽车悬架，而悬架系统是影响汽车行驶舒适性和操控性能的重要因素之一，因此该文章的主要内容与汽车的动力和行驶方面相关”
请问应该怎么调整才能和官网保持一致呢

### Steps To Reproduce

temperature 0.95
top_p 0.8
max_length 4096
history []
prompt："请给以下文章进行类目标签分类。文章标题：空气悬架液压悬架电磁悬架哪一种汽车悬架更好？。文章内容：空气悬架液压悬架电磁悬架哪一种汽车悬架更好？选项是：['智能与主动安全','结构材料与碰撞安全','动力与行驶','静态体验']，请回答："

### Environment

```markdown
OS: Ubuntu 20.04
Python: 3.9
Transformers: 4.30.2
PyTorch: 2.0.1
CUDA Support: True
```

**Comment by MOLIZHU2023** [comment]
你的本地模型才6B，肯定和网页的大模型不一样

**Comment by delltower** [comment]
> 你的本地模型才6B，肯定和网页的大模型不一样

网页的大模型是多大的

**Comment by ralgond** [comment]
> > 你的本地模型才6B，肯定和网页的大模型不一样
> 
> 网页的大模型是多大的

应该是130B
