### ISSUE TITLE
请问如何做Zero Shot多分类任务

### ISSUE THREAD

**Issue by ralgond** [THUDM/ChatGLM2-6B#362]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

您好

比如我有一个问句：

'''给定一个句子:"中信信托不讲武德,贵州黔南政信信托延期,带头大哥想扑街". 给定风险类型列表为{'高层变更','债务违约','债务展期','无法表示意见','授信额度减少','不确定'}. 请问这个句子的风险类型是？'''

现在网页版的答案是：这个句子的风险类型是无法表示意见。

### Expected Behavior

但实际上正确的答案是“债务展期”。我现在不知道用花括号来封装标签列表是否正确。

### Steps To Reproduce

在网页版输入

'''给定一个句子:"中信信托不讲武德,贵州黔南政信信托延期,带头大哥想扑街". 给定风险类型列表为{'高层变更','债务违约','债务展期','无法表示意见','授信额度减少','不确定'}. 请问这个句子的风险类型是？'''

### Environment

```markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by on1you** [comment]
老哥是如何解决的，我也限定了分类，但是输出有时候分类错误，有时候回复分类以外的内容

**Comment by hurner** [comment]
个人觉得以chatGLM的能力还做不到zero Shot， 应该他达不到gpt3.5与gpt4的理解推理能力。
