### ISSUE TITLE
[BUG/Help] 无法正常调用model.get_input_embeddings()

### ISSUE THREAD

**Issue by tingxinli1** [THUDM/ChatGLM2-6B#37]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

无法正常调用model.get_input_embeddings()，原因是AttributeError: 'ChatGLMModel' object has no attribute 'transformer'。由于huggingface官方给了getattr()函数一个默认值，导致错误信息比较少，只返回一个not implemented error。删掉默认值就可以发现真正错误原因。
目测get_input_embeddings()方法是通过transformer这个属性作为路径往回找embedding，但新版的模型失去了这个路径，所以取不到embedding。求修复！

### Steps To Reproduce

具体的错误复现很简单，只要加载chatglm2版本的模型，再使用model.get_input_embeddings()就可以。

### Environment

```markdown
- OS: linux
- Python: 3.9
- Transformers: 4.30.1
- PyTorch: 2+
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by duzx16** [comment]
已经实现了 https://huggingface.co/THUDM/chatglm2-6b/commit/189e5df1609cdbd1704e7d0204301ad4c7791f61

**Comment by tingxinli1** [comment]
> 已经实现了 https://huggingface.co/THUDM/chatglm2-6b/commit/189e5df1609cdbd1704e7d0204301ad4c7791f61
感谢大佬，我发现set_input_embeddings()方法也没有实现，然后我pr到huggingface上了，看看对嘛。
