### ISSUE TITLE
[Feature] <title>如何在多张显卡上指定一张训练，以下指定local_rank无效

### ISSUE THREAD

**Issue by happboy2030** [THUDM/ChatGLM2-6B#389]
### Solutions

PRE_SEQ_LEN=1024
LR=2e-2
CUDA_VISIBLE_DEVICES=1
torchrun    --standalone   --nnodes=1 --nproc-per-node=1  main.py \
    --do_train \
    --local_rank 1 \
    --train_file AdvertiseGen/train.json \
    --validation_file AdvertiseGen/dev.json \
    --preprocessing_num_workers 10 \
    --prompt_column content \
    --response_column summary \
    --overwrite_cache \
    --model_name_or_path model \
    --output_dir output/adgen-chatglm2-6b-pt-$PRE_SEQ_LEN-$LR \
    --overwrite_output_dir \
    --max_source_length 712 \
    --max_target_length 312 \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 1 \
    --gradient_accumulation_steps 16 \
    --predict_with_generate \
    --max_steps 10000 \
    --logging_steps 20 \
    --save_steps 2000 \
    --learning_rate $LR \
    --pre_seq_len $PRE_SEQ_LEN

**Comment by nativexie** [comment]
add 3 lines in python file:
import os
os.environ["CUDA_DEVICE_ORDER"]="PCI_BUS_ID"
os.environ["CUDA_VISIBLE_DEVICES"]="1"  # 0--first GPU, 1--second GPU

**Comment by happboy2030** [comment]
太感谢了，已经好了.The problem is ok.

**Comment by happboy2030** [comment]
ok
