### ISSUE TITLE
[BUG/Help] 长文本时，指令如果放在前面会被忽略

### ISSUE THREAD

**Issue by 137-rick** [THUDM/ChatGLM2-6B#40]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

在头部写 总结下下面文章

在尾部写一个提问

实际回答了提问，没有理会头部总结下面文章

### Expected Behavior

或者有什么技巧隔离开资料和指令

### Steps To Reproduce

same up

### Environment

```markdown
- OS:linux
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

### Anything else?

none

**Comment by starphantom666** [comment]
头尾都给指令

**Comment by thsno02** [comment]
1. 结构化 prompt；
2. 使用指示符包裹长文本。
  
	```
	任务：根据给定文本回答问题，文本使用 &&& 进行包裹。
	问题1：总结文本。
	问题2：“xxx”在文本中什么意思？
	文本： &&& {} &&&
	```

**Comment by 137-rick** [comment]
ok
