### ISSUE TITLE
api.py和web_demo.py单卡OK，怎么多卡部署？

### ISSUE THREAD

**Issue by HelixPark** [THUDM/ChatGLM2-6B#41]
### Is your feature request related to a problem? Please describe.

使用ChatGLM-6B里面的Utils.py进行多卡部署，device_map报错

### Solutions

11

### Additional context

11

**Comment by HelixPark** [comment]
> 我提交了一个PR是解决多卡部署的：#23

多谢，已解决！

**Comment by duzx16** [comment]
已经 merge 了
