### ISSUE TITLE
[Feature] <title>web.py加入重复惩罚与多轮对话会更好

### ISSUE THREAD

**Issue by win10ogod** [THUDM/ChatGLM2-6B#43]
### Is your feature request related to a problem? Please describe.

web.py有加入重复惩罚与多轮对话的计画吗?

### Solutions

加入重复惩罚与多轮对话

**Comment by duzx16** [comment]
web demo 支持多轮对话
重复惩罚的话，可以给 `chat` 或者 `stream_chat` 接口传入 `repetition_penalty` 参数，具体含义见 https://huggingface.co/docs/transformers/main_classes/text_generation#transformers.GenerationConfig.repetition_penalty

**Comment by hwb96** [comment]
> web demo 支持多轮对话 重复惩罚的话，可以给 `chat` 或者 `stream_chat` 接口传入 `repetition_penalty` 参数，具体含义见 https://huggingface.co/docs/transformers/main_classes/text_generation#transformers.GenerationConfig.repetition_penalty

牛牪犇
