### ISSUE TITLE
为嘛微调之后2不如1好呢？

### ISSUE THREAD

**Issue by xxm1668** [THUDM/ChatGLM2-6B#44]
### Solutions

为嘛微调之后2不如1好呢？

**Comment by Mou-Mou-L** [comment]
用的ptuning微调么  ？我的为啥2微调不了 报错ChatGLMModel' object has no attribute 'prefix_encoder'

**Comment by CXLiang123** [comment]
我也是报错ChatGLMModel' object has no attribute 'prefix_encoder'

**Comment by CXLiang123** [comment]
> 我也是报错ChatGLMModel' object has no attribute 'prefix_encoder'

可能是你模型引用不对。看一下那个教程

**Comment by Mou-Mou-L** [comment]
> > 我也是报错ChatGLMModel' object has no attribute 'prefix_encoder'
> 
> 可能是你模型引用不对。看一下那个教程

@CXLiang123 大佬现在可以用ptuning微调了么？我更新了项目和模型的最新内容这个错误跳过了  不过又出了新的错误。

**Comment by CXLiang123** [comment]
> > > 我也是报错ChatGLMModel' object has no attribute 'prefix_encoder'
> > 
> > 
> > 可能是你模型引用不对。看一下那个教程
> 
> @CXLiang123 大佬现在可以用ptuning微调了么？我更新了项目和模型的最新内容这个错误跳过了 不过又出了新的错误。

嗷嗷 我也小菜鸡的 我2用的lora
