### ISSUE TITLE
分布式训练无法实现

### ISSUE THREAD

**Issue by feipengheart** [THUDM/ChatGLM2-6B#442]
### Is your feature request related to a problem? Please describe.

ptuning中，无法进行分布式训练，无论是torchrun 还是deepspeed，都无法实现分布式训练，当指定多个gpu时，每个gpu都是分别加载全量数据，感觉毫无意义啊。导致当出现cuda out时，多卡情况下无法通过分布式训练分摊显存占用量解决额这个问题。

### Solutions

如果不支持分布式训练，那么为什么要使用deepspeed或在torchrun
所以到底是我哪里搞错了，还是就不支持，如果支持是否要修改代码？

**Comment by feipengheart** [comment]
x-special/nautilus-clipboard
copy
file:///home/ypli/Desktop/QQ20230809-175825.png

**Comment by feipengheart** [comment]
![QQ20230809-175825](https://github.com/THUDM/ChatGLM2-6B/assets/66514726/7340b3e8-42e4-4627-8173-b3a86e25e1be)

**Comment by feipengheart** [comment]
close

**Comment by zoelearner** [comment]
这个问题解决了？

**Comment by sxm7078** [comment]
> close
是已经解决了吗

**Comment by Chtholly1** [comment]
不光是不支持3D并行，好像数据并行也不支持。。。
