### ISSUE TITLE
可以让chatglm用固定的方式或者二选一的方式，回答问题吗？比如返回的结果的是或者否。

### ISSUE THREAD

**Issue by thehzzz** [THUDM/ChatGLM2-6B#444]
可以让chatglm用固定的方式或者二选一的方式，回答问题吗？比如返回的结果的是或者否。

_Originally posted by @thehzzz in https://github.com/THUDM/ChatGLM2-6B/discussions/392_

**Comment by zizhec** [comment]
看项目代码库里https://github.com/THUDM/ChatGLM2-6B/blob/main/evaluation/evaluate_ceval.py 的代码，就是达到了这个目的。

**Comment by thehzzz** [comment]
非常感谢
