### ISSUE TITLE
[BUG/Help] ptuning微调时出现 datasets.arrow_writer.SchemaInferenceError: Please pass `features` or at least one example when writing data

### ISSUE THREAD

**Issue by LMC117** [THUDM/ChatGLM2-6B#446]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

运行 bash train.sh，提示 datasets.arrow_writer.SchemaInferenceError: Please pass features or at least one example when writing data

![image](https://github.com/THUDM/ChatGLM2-6B/assets/30344258/508a66ea-1c3b-4d02-916f-e6cf6109f138)
![image](https://github.com/THUDM/ChatGLM2-6B/assets/30344258/1d2e8fa5-d58d-414a-82be-18015d7f0f49)
![image](https://github.com/THUDM/ChatGLM2-6B/assets/30344258/1e65e4a8-8717-412a-8ff0-5ab86e846918)

### Steps To Reproduce

bash train.sh

### Environment

```markdown
- OS: Linux version 3.10.0-1160.90.1.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC) )
- Python: 3.10
- Transformers: 4.30.2
- PyTorch: 2.0.1
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) : True
```

**Comment by ybs10086** [comment]
我正常尝试微调这么模型，但是发生同样的事情，请问您这里解决了吗，什么原因

**Comment by LMC117** [comment]
可以检查一下脚本中微调数据放置的路径是否正确，应该是数据路径错误造成的问题。

**Comment by liuhaiyang007** [comment]
我也出现了同样的问题，请问数据路径怎么放呢

**Comment by LMC117** [comment]
修改ptuning/train.sh中的--train_file与--validation_file参数的路径即可

**Comment by liuhaiyang007** [comment]
我把AdvertiseGen文件放在ptuning文件夹下了，    --train_file AdvertiseGen/train.json \
    --validation_file AdvertiseGen/dev.json \ 不对吗

**Comment by LMC117** [comment]
我是误删了符号导致路径错误，改正后就没遇到这个问题了。排查过程中我还将datasets的版本降低至了2.10.0，你试试这样做看看能不能解决？

**Comment by FelixLiu1996** [comment]
我也遇到了这个问题，改了一下json就出问题 用AdvertiseGen的数据就没有问题
