### ISSUE TITLE
评测

### ISSUE THREAD

**Issue by yuquanle** [THUDM/ChatGLM2-6B#45]
### Is your feature request related to a problem? Please describe.

请问评测脚本的demo计划开源吗？

### Solutions

评测脚本开源可以帮助大家快速上手评测。

**Comment by duzx16** [comment]
https://github.com/THUDM/ChatGLM2-6B/tree/main/evaluation 提供了 C-Eval 验证集上的评测脚本。不过实际评测使用的是内部的并行实现，结果会有轻微波动
