### ISSUE TITLE
[Help] 调用openapi报错404

### ISSUE THREAD

**Issue by Yif-Liu-Github** [THUDM/ChatGLM2-6B#457]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://github.com/THUDM/ChatGLM2-6B/assets/54025962/d89710fa-700d-48ec-a41b-022f65fbdef4)
我在服务器中的容器中起了chatglm2-6b的openai_api服务，我在笔记本电脑上调用时，日志确实滚动跟新了，但是返回的内容是404

### Expected Behavior

无

### Steps To Reproduce

无

### Environment

```markdown
- OS:Ubuntu 20.04
- Python:3.10
```

### Anything else?

无

**Comment by aurxs** [comment]
我也遇到了这个问题，请问楼主解决了吗

**Comment by YunFenLei** [comment]
我也遇到了，今天新开的 Ubuntu22.04  py3.9，同样的问题，另外一个模型调用openai接口也是 404！

**Comment by Yif-Liu-Github** [comment]
> 我也遇到了这个问题，请问楼主解决了吗

还没

**Comment by Yif-Liu-Github** [comment]
python openai_api.py启动服务后使用下面代码进行调用

```
import openai
if __name__ == "__main__":
    openai.api_base = "http://218.92.223.105:50080/chatglmopenapi/v1"
    openai.api_key = "none"
    for chunk in openai.ChatCompletion.create(
        model="chatglm2-6b",
        messages=[
            {"role": "user", "content": "你好"}
        ],
        stream=True
    ):
        if hasattr(chunk.choices[0].delta, "content"):
            print(chunk.choices[0].delta.content, end="", flush=True)
```
