### ISSUE TITLE
[BUG/Help] <ConnectionResetError: [Errno 104] Connection reset by peer>

### ISSUE THREAD

**Issue by mikestut** [THUDM/ChatGLM2-6B#47]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://github.com/THUDM/ChatGLM2-6B/assets/88723510/2cd8301f-935c-4c2f-aebf-5179aae18e30)

### Expected Behavior

ConnectionResetError: [Errno 104] Connection reset by peer
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
报了3个错误！如上图！！

### Steps To Reproduce

1、git clone https://github.com/THUDM/ChatGLM2-6B
2、cd ChatGLM2-6B
3、pip install -r requirements.txt
4、python web_demo.py

之前安装过ChatGLM-6B，可以正常使用。

求支持！！

### Environment

```markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by pansinm** [comment]
文件太大，网盘无法打包下载，可以用下面命令一键下载 chatglm-6b
```bash
curl "https://cloud.tsinghua.edu.cn/api/v2.1/share-links/674208019e314311ab5c/dirents/?thumbnail_size=48&path=%2Fchatglm-6b%2F" | jq  ".dirent_list[].file_name" | xargs -I {}  wget https://cloud.tsinghua.edu.cn/seafhttp/files/5ea6bba5-d11e-4eea-b64d-2aa1bf2c8ef7/{}
```

**Comment by rebuilder945** [comment]
用自己本地的模型加载，或者替换成缓存模型的本地路径
