### ISSUE TITLE
[Feature] 能提供模型的国内下载源吗？

### ISSUE THREAD

**Issue by H9990HH969** [THUDM/ChatGLM2-6B#49]
### Is your feature request related to a problem? Please describe.

能提供模型的国内下载源吗？

### Solutions

提供一个网盘地址的下载源

**Comment by sgyh** [comment]
https://github.com/THUDM/ChatGLM2-6B/issues/14

刚看了下，清华云盘的模型文件已经上传完了

**Comment by duzx16** [comment]
https://cloud.tsinghua.edu.cn/d/674208019e314311ab5c/
