### ISSUE TITLE
[Help] <CPU模型运行时，如何提升核利用率>

### ISSUE THREAD

**Issue by sgyh** [THUDM/ChatGLM2-6B#50]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

模型在CPU上启动起来后，每次进行chat，观察机器的CPU利用率恰好是50%

比如服务器是12个CPU core，在chat过程中，同时只有6个core在进行计算

### Expected Behavior

调整哪个参数可以提高chat时的CPU利用率？

### Steps To Reproduce

1. 按教程运行demo或者api
2. 发起chat
3. 观察服务器CPU利用率情况

### Environment

```markdown
- OS:CentOS
- Python:3.9
- Transformers:4.30.2
- PyTorch:2.0.1
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :False
```

**Comment by sgyh** [comment]
@duzx16 求问大佬🙏

**Comment by zdevc** [comment]
以下代码，可以提升核心利用率，但是似乎并没有提升多少性能

import os
import torch

cpu_num = 24 # 这里设置成你想运行的CPU个数
torch.set_num_threads(cpu_num)
os.environ ['OMP_NUM_THREADS'] = str(cpu_num)
os.environ ['MKL_NUM_THREADS'] = str(cpu_num)
os.environ ['OPENBLAS_NUM_THREADS'] = str(cpu_num)
os.environ ['VECLIB_MAXIMUM_THREADS'] = str(cpu_num)
os.environ ['NUMEXPR_NUM_THREADS'] = str(cpu_num)

**Comment by sgyh** [comment]
谢谢~
