### ISSUE TITLE
chatglm2-6b-int4的模型，为什么需要12G以上GPU内存？

### ISSUE THREAD

**Issue by landxman** [THUDM/ChatGLM2-6B#52]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

chatglm-6b-int4只需要7G的GPU内存，就可以运行。
但是chatglm2-6b-int4实测需要12G以上的GPU内存。
有没有办法可以降低到7G左右的GPU内存?

### Steps To Reproduce

===web_demo.py===
tokenizer = AutoTokenizer.from_pretrained("/data/chatglm/chatglm2-6b-int4", trust_remote_code=True)
model = AutoModel.from_pretrained("/data/chatglm/chatglm2-6b-int4", trust_remote_code=True, device='cuda')
===web_demo.py===

python web_demo.py

### Environment

```markdown
- OS:Ubuntu 22.04.1 LTS
- Python:3.9.17
- Transformers:4.27.1
- PyTorch:2.0.1+cu117
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by duzx16** [comment]
我这边测试的最大内存占用是 4-5 GB，你可以试着把 transformers 升级到 4.30.2？

**Comment by Sunnylee0101** [comment]
把torch升级到2.0.1 以及transformers升级到4.30  6G显存就可以运行了，当然，6G非常慢，我是RTX3070  8G显存，效果不错，速度很快

**Comment by JulyFinal** [comment]
`model = AutoModel.from_pretrained("/data/chatglm/chatglm2-6b-int4", trust_remote_code=True, device='cuda')`
 修改为
```model = AutoModel.from_pretrained("/data/chatglm/chatglm2-6b-int4", trust_remote_code=True)
model.cuda()
```

**Comment by landxman** [comment]
> 

按照JulyFinal的方法，解决内存的问题了。
