### ISSUE TITLE
微调时torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 报错

### ISSUE THREAD

**Issue by ZCQ0628** [THUDM/ChatGLM2-6B#520]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

错误信息：Loading checkpoint shards:  57% 4/7 [00:40<00:29,  9.96s/it]ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -9) local_rank: 0 (pid: 31631) of binary: /usr/bin/python3
Traceback (most recent call last):
  File "/usr/local/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
======================================================
main.py FAILED
------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-09-04_07:49:11
  host      : 42d85289a29a
  rank      : 0 (local_rank: 0)
  exitcode  : -9 (pid: 31631)
  error_file: <N/A>
  traceback : Signal 9 (SIGKILL) received by PID 31631
======================================================

### Steps To Reproduce

执行的以下报错：
PRE_SEQ_LEN=128
LR=2e-2
NUM_GPUS=1

torchrun --standalone --nnodes=1 --nproc-per-node=$NUM_GPUS main.py \
    --do_train \
    --train_file /content/ChatGLM2-6B/ptuning/json-new.json \
    --validation_file /content/ChatGLM2-6B/ptuning/json-new.json \
    --preprocessing_num_workers 10 \
    --prompt_column query \
    --response_column response \
    --overwrite_cache \
    --model_name_or_path THUDM/chatglm2-6b \
    --output_dir output/adgen-chatglm2-6b-pt-$PRE_SEQ_LEN-$LR \
    --overwrite_output_dir \
    --max_source_length 128 \
    --max_target_length 128 \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 1 \
    --gradient_accumulation_steps 10 \
    --predict_with_generate \
    --max_steps 2000 \
    --logging_steps 10 \
    --save_steps 1000 \
    --learning_rate $LR \
    --pre_seq_len $PRE_SEQ_LEN \
    --quantization_bit 4

### Environment

```markdown
- OS:linux
- Python:Python 3.10.12
- Transformers:4.30.2
- PyTorch:2.0.1+cu118
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by ZCQ0628** [comment]
数据量调小才可以 大了还没尝试 先关了

**Comment by jidandan666** [comment]
解决了吗 我也遇到了
