### ISSUE TITLE
mac电脑m1芯片报错 IndexError: piece id is out of range. 

### ISSUE THREAD

**Issue by douyamv** [THUDM/ChatGLM2-6B#55]
mac m1芯片运行报错 
raise IndexError('piece id is out of range.')
IndexError: piece id is out of range.

使用的是显卡 .to('mps')
如果换成cpu模式 .float()就没有问题，但是太慢了，求支持下mac电脑m1芯片

**Comment by TommyTT1993** [comment]
同mac m1，也遇到这个问题了。

**Comment by dzgdp888** [comment]
我是16G内存就会报这个错误，换成M1 max 64G内存就好了

**Comment by douyamv** [comment]
我是楼主，我已经解决了，重新使用VirtualEnv创建环境就好了，使用的是python3.8。

**Comment by LeToNode** [comment]
> 我是16G内存就会报这个错误，换成M1 max 64G内存就好了

我是64G内存仍然有这个错误信息。
