### ISSUE TITLE
[BUG/Help] <title>

### ISSUE THREAD

**Issue by lullabies777** [THUDM/ChatGLM2-6B#56]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://github.com/THUDM/ChatGLM2-6B/assets/67683748/16e4e19b-5130-49ed-be48-9e34c8b800df)

### Expected Behavior

看了下tokenizer的代码，和1不太一样。这块为什么会prefix_tokens加tokens_ids_0呢,然后token_ids_0和token_ids_1之间没有任何区分的token，这么写是出于什么考虑呢？

### Steps To Reproduce

SFT model

### Environment

```markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by duzx16** [comment]
为了符合预训练的时候 GLM 的输入格式

**Comment by lullabies777** [comment]
> 为了符合预训练的时候 GLM 的输入格式

感谢回复，想问一下那如果在进行sft微调的时候为了区分prompt和response，是不是需要人为改一下，在prompt和response之间加gmask token和sop token呢（和Chatglm-6B一致）？
