### ISSUE TITLE
目前最大长度8192  ， 为什么返回的字数每次最多在566个字左右？

### ISSUE THREAD

**Issue by Song367** [THUDM/ChatGLM2-6B#58]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

使用web_demo.py 

### Steps To Reproduce

1. windows GPU
2. int4 模型
3. torch2.0.1
4. python 3.10

### Environment

```markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by duzx16** [comment]
默认的最大长度设置的是 2048，已经修改了
