### ISSUE TITLE
[Feature] 能否增加多GPU加载的支持

### ISSUE THREAD

**Issue by freefoxcm** [THUDM/ChatGLM2-6B#63]
### Is your feature request related to a problem? Please describe.

能否增加多GPU加载的支持？

### Solutions

能否增加多GPU加载的支持？

**Comment by Mou-Mou-L** [comment]
> 已经增加了支持 https://github.com/THUDM/ChatGLM2-6B#%E5%A4%9A%E5%8D%A1%E9%83%A8%E7%BD%B2

大佬 这单卡运行显存占用 11.7  多卡 两个都是11.7  虽然支持了多卡，可是显存没有分配么？好奇怪
