### ISSUE TITLE
[BUG/Help] <title>最大长度输入问题

### ISSUE THREAD

**Issue by yw2278** [THUDM/ChatGLM2-6B#65]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

输入长度11k的文字，提示：Input length of input_ids is 11052, but `max_length` is set to 2048. This can lead to unexpected behavior. You should consider increasing `max_new_tokens`.
使用的cli_demo，想问下如果需要到32k长度的上下文，需要做什么配置么？

### Steps To Reproduce

1.pip intall -r requirement
2.python cli_demo.py
3.输入长文本文字

### Environment

```markdown
- OS: Ubuntu 20.04
- Python:3.8
- Transformers:4.30.2
- PyTorch:2.0
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) : 11.8
```

**Comment by yh7109** [comment]
需要加max_length参数，我也搞了半个小时才发现

**Comment by yangbisheng2009** [comment]
在哪里加？
