### ISSUE TITLE
处理结构化数据效果相比第一版降低

### ISSUE THREAD

**Issue by mide123** [THUDM/ChatGLM2-6B#68]
### Is your feature request related to a problem? Please describe.

首先非常感谢你们的开源模型，我在使用的时候发现新的版本对于结构化数据（比如Json）效果差了很多，chatglm我提取json数据的信息，全都正确了，但是用chatglm2的时候提取json数据基本上都不正确，这个是为什么呢

### Solutions

无

**Comment by mide123** [comment]
输入的json是因为编码格式问题导致的，问题已经解决

**Comment by Crayon-s7** [comment]
求个prompt
