### ISSUE TITLE
[Help] cpu启动量化，Ai回复速度很慢，正常吗？ 

### ISSUE THREAD

**Issue by csc226** [THUDM/ChatGLM2-6B#71]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

模型量化int4，CPU部署,提问问题，AI回复速度每分钟4-9个字，请问这个速度正常吗？有没有提速的方法？
提问 周树人和鲁迅是同一个人吗？
回复结果不是同一个人
![image](https://github.com/THUDM/ChatGLM2-6B/assets/58936146/b88e2b59-b5f4-41ff-b689-e1cf0a13b970)

### Steps To Reproduce

window10环境下，CPU部署模型量化，报错如图：
![image](https://github.com/THUDM/ChatGLM2-6B/assets/58936146/3052d457-5225-443d-b327-e0a135841c80)
模型可以正常启动

### Environment

```markdown
- OS:window10
- Python:3.11.4
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by OneiroXL** [comment]
你这是用CPU跑的吧  用CPU肯定满 正常

**Comment by OneiroXL** [comment]
你这是用CPU跑的吧 用CPU肯定慢 正常

**Comment by duzx16** [comment]
用 CPU 慢很正常

**Comment by lampda** [comment]
抱歉重新打开话题.

这个版本的CPU量化chatglm2-6b-int4的回复速度是比chatglm-6b-int4的量化版本慢了好几倍.
我的系统配置是16核CPU,内存充足.
备注: 网页端三个参数在两个版本中的设置一样.
