### ISSUE TITLE
[BUG/Help] <title>感觉推理是不是退步了？

### ISSUE THREAD

**Issue by WanJuWuGo** [THUDM/ChatGLM2-6B#73]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

用户：一只鸡和一只兔，总共多少腿

ChatGLM-6B：一只鸡和一只兔，总共两条腿。因为鸡有2条腿，兔子有4条腿。

### Steps To Reproduce

下载最新版本模型

### Environment

```markdown
显卡v100
```

**Comment by arkerwu** [comment]
![image](https://github.com/THUDM/ChatGLM2-6B/assets/22535148/91072561-df58-43f7-9ded-71b2db0dc8ee)
回答不太稳定,10次又一次错的;可以把Temperature改成1试试

**Comment by xiningnlp** [comment]
![image](https://github.com/THUDM/ChatGLM2-6B/assets/87839299/01bac9b9-f604-47c3-9e7c-4f5ff30b4987)

**Comment by Mou-Mou-L** [comment]
可以用ptuning微调么  大佬
