### ISSUE TITLE
[Feature] <title>您好，想问一下模型的源码在哪里

### ISSUE THREAD

**Issue by DeerEyre** [THUDM/ChatGLM2-6B#74]
### Is your feature request related to a problem? Please describe.

比较想研究一下本模型是如何实现muti-query-attention的，想问一下可以在哪里查看该实现

### Solutions

给出一个py文件或者项目地址即可

**Comment by duzx16** [comment]
https://huggingface.co/THUDM/chatglm2-6b

**Comment by DeerEyre** [comment]
万分感谢，想明白模型代码里的multi_query_group_num参数是如何确定为2的，为什么不是论文里介绍的1呢
