### ISSUE TITLE
tokenization_chatglm.py里面build_inputs_with_special_tokens是不是写错了 gmask怎么加在最前面了？？？？？

### ISSUE THREAD

**Issue by Siegfried-qgf** [THUDM/ChatGLM2-6B#80]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

啥情况啥情况啥情况

### Steps To Reproduce

dd

### Environment

```markdown
- OS:Ubuntu 20.04
- Python:3.8
- Transformers: 4.26.1
- PyTorch:1.12
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) : True
```

**Comment by Siegfried-qgf** [comment]
prefix_tokens = self.get_prefix_tokens()
        token_ids_0 = prefix_tokens +token_ids_0
        if token_ids_1 is not None:
            token_ids_0 = token_ids_0 + token_ids_1 + [self.get_command("<eos>")]
        return token_ids_0

**Comment by duzx16** [comment]
出于 #16 中提到的原因，在进行 chat 模型训练的时候使用的是单向注意力，也就是 GLM 论文里 unidirectional setting
