### ISSUE TITLE
请问下MQA可以只在推理时使用，训练时不用吗？

### ISSUE THREAD

**Issue by dingjingzhen** [THUDM/ChatGLM2-6B#81]
### Solutions

如题，还是说必须训练和推理都得同时使用MQA

**Comment by duzx16** [comment]
不可以。训练和推理的时候计算方式必须保持一致。

**Comment by dingjingzhen** [comment]
> 不可以。训练和推理的时候计算方式必须保持一致。

感谢回复，顺带问一下，你们在推理时的加速手段主要是哪些，MQA、flash attention吗？量化对于推理速度提升大吗？还有就是lyraChatGLM这个对于推理有很大的加速吗
